### ISSUE TITLE
Why does Ragas require a llm model when evaluating on datasets with answers and questions?

### ISSUE THREAD

**Issue by HighEndStar** [explodinggradients/ragas#1007]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
Why does Ragas require a llm model when evaluating on datasets with answers and questions?

I don't know why llm is needed when calculating indicators such as context_precision or context_recall for datasets with both question and ground_truth and answer and context

**Code Examples**
from ragas import evaluate
result = evaluate(
    test_dataset,
    metrics=[
        context_precision,
    ]
)

this code requires an error :
**ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)**

**Additional context**
I wonder what the role of LLM and Embeddings models is when evaluating the dataset with answer and question and ground truth and context already.

**Comment by jjmachan** [comment]
we use LLMs for evaluations 2 overcome 2 shortcomings
1. in generative system, the final answer need not be exactly the same as the ground_truth. So you need a smart way to see if both are correct. The [Answer Correctness | Ragas](https://docs.ragas.io/en/stable/concepts/metrics/answer_correctness.html) is a good example.
2. To augment data needed. for metrics like retriever, building a annotated dataset is extremely hard, using LLMs augments that. See [Context Recall | Ragas](https://docs.ragas.io/en/stable/concepts/metrics/context_recall.html) calculations
