### ISSUE TITLE
Ragas installation induced pandas segmentation fault 

### ISSUE THREAD

**Issue by aryamanpandya99** [explodinggradients/ragas#1017]
- [x] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
Once I install ragas via `pip install ragas` in my (otherwise clean) venv, I receive a segmentation fault when importing ragas or pandas. Prior to the ragas installation, I'm able to import pandas with no issues. This issue persists even when installing latest master of ragas. 

Ragas version: 0.19.0
Python version: 3.12.3 (also attempted on 3.11.8)

**Code to Reproduce**
Share code to reproduce the issue
In a clean venv with the above python version, 
```bash
pip install pandas
pip install ragas
```
In a python script/notebook:
```python
import pandas
```

**Error trace**
Segmentation fault: 11

**Expected behavior**
Clean import. 

**Additional context**

**Comment by jjmachan** [comment]
Unfortunately, I'm unsure if this is a Ragas issue because if you check [pyproject.toml](https://github.com/explodinggradients/ragas/blob/main/pyproject.toml) file you can see that we don't directly depend on pandas, we only use the available installation. 

this might be something specific to your virtualenv sadly.

**Comment by jjmachan** [comment]
which virtualenv are you using?

**Comment by aryamanpandya99** [comment]
Yeah, I did take a look at the toml. I've tried with multiple clean venvs, the first one was created using python3 in the vanilla way: `python -m venv /path/to/new/virtual/environment`. I then used conda to create a venv as well, where all I ran was `conda install pandas` and `pip install ragas`. When I did this I received the same error as specified in the issue.

**Comment by aryamanpandya99** [comment]
Since this is likely a platform/venv problem I'll close this issue out.
