### ISSUE TITLE
RagasOutputParser exception handler should work synchronously when is_async=False

### ISSUE THREAD

**Issue by BaptisteBtx** [explodinggradients/ragas#1019]
**Describe the Feature**

The `is_async` value chosen when calling the `evaluate` function should be used for the call to `generate` within `RagasoutputParser`.

```python
class RagasoutputParser(PydanticOutputParser):
    async def aparse(  # type: ignore
        self, result: str, prompt: PromptValue, llm: BaseRagasLLM, max_retries: int = 1
    ):
        try:
            output = super().parse(result)
        except OutputParserException:
            if max_retries != 0:
                p_value = FIX_OUTPUT_FORMAT.format(
                    prompt=prompt.to_string(), completion=result
                )
                output = await llm.generate(p_value)
                result = output.generations[0][0].text
                return await self.aparse(result, prompt, llm, max_retries - 1)
            else:
                logger.warning("Failed to parse output. Returning None.")
                return None
        return output
```
Currently in RagasoutputParser if parsing fail then an attempt is made to correct the JSON but it is not compatible with the ability to work synchronously if the llm does not support async because `is_async` is True by default in `llm.generate()`.

**Additional context**

Maybe #975 will solve this problem, if not I'd be happy to contribute if help is needed!

Thanks !

**Comment by jjmachan** [comment]
which LLM are you using @BaptisteBtx ?

but unfortunatly you are right. we will be removing `is_async` flag soon because we switched to only use async for LLM calls. 

is there anything I can do to help you in the mean time?
