### ISSUE TITLE
run_config missing 

### ISSUE THREAD

**Issue by Mtuthuko** [explodinggradients/ragas#1021]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
I got this error ``` TypeError: MetricWithLLM.init() missing 1 required positional argument: 'run_config' ``` when I was trying to calculate the ragas scores

Ragas version: 0.1.9
Python version: 3.11

**Code to Reproduce**
```py
from ragas import evaluate
from langchain_openai.chat_models import AzureChatOpenAI
from langchain_openai.embeddings import AzureOpenAIEmbeddings
from ragas.llms import LangchainLLMWrapper


from ragas.metrics import (
    answer_relevancy,
    faithfulness,
    ContextRelevancy,
)

azure_model = AzureChatOpenAI(
     deployment_name="xxxxxx",
     model="xxxxxx",
     api_version ="xxxxxx",
     openai_api_type="azure"
)

ragas_azure_model =LangchainLLMWrapper(azure_model)

azure_embeddings = AzureOpenAIEmbeddings(
    deployment="xxxxxx",
    model = "xxxxxx",
    api_version ="xxxxxx",
     openai_api_type="azure"
)

metrics = [
    faithfulness,
    answer_relevancy,
    ContextRelevancy
]

for m in metrics:
    m.__setattr__('llm',ragas_azure_model)

questions = df.Query.values
rag_answers = df.Answers.values
contexts = df.Context.values



from datasets import Dataset

data = {
    "question": questions,
    "answer": rag_answers,
    "contexts": contexts
}


dataset = Dataset.from_dict(data)


result = evaluate(dataset=dataset,
                  metrics=metrics,
                  llm = ragas_azure_model,
                  embeddings = azure_embeddings)
```

**Error trace**
<img width="579" alt="image" src="https://github.com/explodinggradients/ragas/assets/30107613/274ac35f-8765-4eea-a2c4-18185676b88e">

<img width="1116" alt="image" src="https://github.com/explodinggradients/ragas/assets/30107613/6f943fc9-0e1b-4ccb-a34b-43cab8699e6f">

**Expected behavior**
For the code to calculate the ragas scores.

**Comment by Sudhakar17** [comment]
@Mtuthuko  did you resolve this error? I am also facing the exact problem

**Comment by jjmachan** [comment]
hey @Mtuthuko were you able to fix this?

it seems like a small bug in the code

```py
from ragas.metrics import (
    answer_relevancy,
    faithfulness,
    # ContextRelevancy, # old
    content_relavancy
)

metrics = [
    faithfulness,
    answer_relevancy,
    context_relevancy
]
```

this should fix it. let me know if its still an issue

@Sudhakar17 could you share your code snippet? I'll check it
