### ISSUE TITLE
what does a context_relevancy of >1 mean?

### ISSUE THREAD

**Issue by vibha0411** [explodinggradients/ragas#103]
I created a small Dataset of my own and observed that the context_relevancy>1
Can I please know what this means?

**Comment by shahules786** [comment]
Hi @vibha0411 , this can be a bug. Can you please share the sample for which the context_relvancy score exceeded 1?

**Comment by vibha0411** [comment]
I am using ragas==0.0.11, following is the way i created the dataset:
```
from datasets import Dataset
def gen():
    yield {"question": "What is the Scope 1 Direct Emissions intensity for the year 2022?", "ground_truths":["The scope 1 emissions intensity for the year 2022 was 0.0157"],"answer":"The scope 1 emissions intensity for the year 2022 was 446,084","contexts":["Scope 2 Indirect Emissions in 2022 was 1,922,844","The scope 1 emissions for the year 2022 was 446,084","The scope 1 emmissions intensity was  0.0157"]}
ds = Dataset.from_generator(gen)
```

**Comment by Copticoder** [comment]
same issue here is this resolved or not ?

**Comment by Copticoder** [comment]
great ! 
can you please provide more details in the docs on these metrics ? like the methodology behind context_relevancy in details

**Comment by shahules786** [comment]
@Copticoder Sure, we are working on it. Will be able to update it before the next release.
