### ISSUE TITLE
[R-284] Use GPT-4o instead of GPT-4?

### ISSUE THREAD

**Issue by arainey2022** [explodinggradients/ragas#1035]
Would it be possible to use the GPT-4o model instead of GPT-4, would be much more cost effective and speedy for people.

Great product btw, thank you!

<sub>[R-284](https://linear.app/exploding-gradients/issue/R-284/use-gpt-4o-instead-of-gpt-4)</sub>

**Comment by jjmachan** [comment]
@arainey2022 thanks for the suggestion and the kind words. We should do this this week @shahules786 ?

**Comment by shahules786** [comment]
Hey @arainey2022 this was merged #1166
