### ISSUE TITLE
Discord server link in README.md is expired

### ISSUE THREAD

**Issue by nelsonauner** [explodinggradients/ragas#104]
Current link in `README.md` https://github.com/explodinggradients/ragas/blob/main/README.md points to https://discord.gg/5djav8GGNZ, which returns an invalid invite.

Hopefully you can refresh the invite link :). If you don't want people to join, probably should remove the link

<img width="987" alt="image" src="https://github.com/explodinggradients/ragas/assets/3402261/25ff8775-1053-4e62-b87d-6b553b081f8a">

**Comment by shahules786** [comment]
Hi @nelsonauner, Sorry for the inconvenience. I can see that the link was working until yesterday midnight, it might have expired after that. Here's the new link if you want to join now https://discord.gg/Je4W4rePCx

**Comment by nelsonauner** [comment]
Works, great, thanks!
