### ISSUE TITLE
Can anybody tell me the testset generator code given in RAGAS website what columns will it actually create i think we can only get questions and ground_truth ans from testset generator and the context and answer will be generated from our rag architecture

### ISSUE THREAD

**Issue by Saurabh8255** [explodinggradients/ragas#1054]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
what is unclear to you? What would you like to know?

**Code Examples**
This community speaks code. Share your code snippets to help us understand your question better.

**Additional context**
Anything else you want to share with us?

**Comment by jjmachan** [comment]
fixed with #1176. sry for the confusion 🙌🏽
