### ISSUE TITLE
can I use doubao? i have found qwen but can not find  doubao in chat_models ,doubao is cheap and performance as gpt-4 in chinese

### ISSUE THREAD

**Issue by hellostronger** [explodinggradients/ragas#1067]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
what is unclear to you? What would you like to know?

**Code Examples**
This community speaks code. Share your code snippets to help us understand your question better.

**Additional context**
Anything else you want to share with us?

**Comment by jjmachan** [comment]
this documentation should help @hellostronger [Bring Your Own LLMs and Embeddings | Ragas](https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html)?

**Comment by wangzhen38** [comment]
> this documentation should help [@hellostronger](https://github.com/hellostronger) [Bring Your Own LLMs and Embeddings | Ragas](https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html)?

The link is invalid now

**Comment by wangzhen38** [comment]
> > this documentation should help [@hellostronger](https://github.com/hellostronger) [Bring Your Own LLMs and Embeddings | Ragas](https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html)?
> 
> The link is invalid now

This doc can be refered, https://github.com/explodinggradients/ragas/blob/cb63a8266b80fcb5715b06fc97d1f9165bc49f93/docs/getstarted/rag_eval.md#basic-setup
