### ISSUE TITLE
Typo in results key -> context_ relevancy

### ISSUE THREAD

**Issue by ogencoglu** [explodinggradients/ragas#107]
`results.keys()` return

`dict_keys(['answer_relevancy', 'context_ relevancy', 'faithfulness', 'ragas_score'])`

where there is a whitespace in `context_ relevancy`

Due to https://github.com/explodinggradients/ragas/blob/9f54d016fd0743c4e6abac585cba76d36e3b1436/src/ragas/metrics/context_relevance.py#L110

**Comment by jjmachan** [comment]
Thanks a lot for pointing this out @ogencoglu, I've fixed it and will be out in the next release

Apologies for the delay from my end but do let us know your feedback on using ragas :)
