### ISSUE TITLE
Test data generation Answer column is missing

### ISSUE THREAD

**Issue by manojpraba** [explodinggradients/ragas#1084]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
when I creating test data using below code, answer column is missing not generated 

import nest_asyncio
nest_asyncio.apply()
generator = TestsetGenerator.from_langchain(
    generator_llm=azure_model, critic_llm=azure_model, embeddings=azure_embeddings
)

testset = generator.generate_with_langchain_docs(
    
    lchain_docs,
    test_size=2,
    raise_exceptions=False,
    is_async= True,
    with_debugging_logs=False,
    
    distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},

Ragas version:
Python version: 3.10

**Code to Reproduce**

**Error trace**
{
	"name": "ValueError",
	"message": "The metric [faithfulness] that that is used requires the following additional columns ['answer'] to be present in the dataset. ",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[178], line 3
      1 import nest_asyncio
      2 nest_asyncio.apply()
----> 3 result = evaluate(
      4     dataset1,metrics=metrics1, llm=azure_model, embeddings=azure_embeddings, raise_exceptions=False)

File c:\\DL projects\\ai-kb-bot\\.venv\\lib\\site-packages\\ragas\\evaluation.py:156, in evaluate(dataset, metrics, llm, embeddings, callbacks, in_ci, is_async, run_config, raise_exceptions, column_map)
    154 # validation
    155 dataset = handle_deprecated_ground_truths(dataset)
--> 156 validate_evaluation_modes(dataset, metrics)
    157 validate_column_dtypes(dataset)
    159 # set the llm and embeddings

File c:\\DL projects\\ai-kb-bot\\.venv\\lib\\site-packages\\ragas\\validation.py:97, in validate_evaluation_modes(ds, metrics, evalmode_to_columns)
     91 if (
     92     isinstance(m, ContextPrecision)
     93     and \"ground_truth\" not in available_columns
     94 ):
     95     extra_msg = \"Looks like you're trying to use 'context_precision' without ground_truth. Please use consider using  `context_utilization' instead.\"
---> 97 raise ValueError(
     98     f\"The metric [{m.name}] that that is used requires the following \"
     99     f\"additional columns {list(required_columns - available_columns)} \"
    100     f\"to be present in the dataset. {extra_msg}\"
    101 )

ValueError: The metric [faithfulness] that that is used requires the following additional columns ['answer'] to be present in the dataset. "
**Expected behavior**
Expecting workaround for generating answer column

**Additional context**
![image](https://github.com/explodinggradients/ragas/assets/37367345/48931983-fe66-4601-9d15-0ed71a7dae67)

**Comment by manojpraba** [comment]
@dosu what should be the value for query_engine if using azure open ai api

**Comment by Zzrjin** [comment]
same issue, do you solve this problem？

**Comment by Gwenn-LR** [comment]
As mentionned in the documentation, "Faithfulness - Measures the factual consistency of the answer to the context based on the question.". So you need to provide an answer for earch query in order to compute this metric.

To do so you need to generate responses with your RAG/LLM and append them to your dataset:
1. Generate responses 
> [!NOTE]  
> I'm using LangChain terminology, feel free to adapt my `llm.invoke(question).content` to your configuration - I've also taken your variable `generator` instanciated from `TestsetGenerator.from_langchain` class method:

```python
answers = [llm.invoke(question).content for question in generator["question"]]
```

2. Append them to your dataset
> [!NOTE]  
> Since `TestsetGenerator` doesn't seem to have a method to add a column, I've exported the `TestsetGenerator` object to a `pandas.Dataframe` object and I've added a "answer" column:
```python
generator_with_generated_answers = generator.to_pandas()
generator_with_generated_answers["answer"] = answers
```
>[!NOTE]
>According to the `datasets` API, `evaluate` method expects a `Dataset` object, so I've exported back to this type:
```python
from datasets import Dataset

generated_dataset = Dataset.from_pandas(generator_with_generated_answers)
```

Finally, you can use your new dataset to evaluate your RAG/LLM:
```python
results = evaluate(generated_dataset, metrics=metrics, llm=azure_model, embeddings=azure_embeddings, raise_exceptions=False)
```

> [!WARNING]  
> Since you use the same LLM to generate your synthetic dataset `ground_truth` and your `answer`, I think the results of this evaluation might be biased. I haven't realized a comparative study but it might be an issue which could have an impact on your interpretation.
