### ISSUE TITLE
ExceptionInRunner and RuntimeWarning Issues with Ragas Library

### ISSUE THREAD

**Issue by Elena4750** [explodinggradients/ragas#1088]
I am encountering an issue while using the Ragas library. Has anyone encountered a similar problem?
Environment: Python 3.10, latest version of Ragas library

![image](https://github.com/explodinggradients/ragas/assets/162958549/39126bb5-eb67-4a55-a17b-6a9cbd50b4c7)
![image (1)](https://github.com/explodinggradients/ragas/assets/162958549/06387cc4-ccbe-460d-90f0-e1cb0a3d891f)

**Comment by Elena4750** [comment]
Sad. Have tried, not worked.

**Comment by LDelPinoNT** [comment]
Getting a similar issue on Python 3.11 - latest version of RAGAS library, but when trying to generate a syntetic dataset with ".generate_with_langchain_docs".

Here is my traceback:
RuntimeWarning: coroutine 'as_completed.<locals>.sema_coro' was never awaited
  await self._event_pipe_gc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by Rugved2204** [comment]
I am also getting a similar issue while generating a synthetic dataset.  

Traceback:
File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 37, in sema_coro
    return await coro
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 109, in wrapped_callable_async
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ragas/executor.py", line 104, in wrapped_callable_async
    result = await callable(*args, **kwargs)
TypeError: object list can't be used in 'await' expression

**Comment by LDelPinoNT** [comment]
As additional info, I installed version 0.1.9 and the error disappeared.

**Comment by tuantuan-lin** [comment]
Hello, I have encountered the same situation, which has been successfully solved by the following methods.

https://github.com/explodinggradients/ragas/issues/1073

**Comment by damlitos** [comment]
> dataset

what python version did you use?

**Comment by damlitos** [comment]
> Hello, I have encountered the same situation, which has been successfully solved by the following methods.
> 
> #1073

what python version did you use?
