### ISSUE TITLE
Bug in context_relevancy _compute_score method

### ISSUE THREAD

**Issue by salman-khandu** [explodinggradients/ragas#1094]
I was debugging the code and found that if llm return "Insufficient Information" then tokenize on llm response is not correct as llm response contains no dot at the end and  comparison literal has dot at the end. 
See below screenshot of comparision
<img width="604" alt="image" src="https://github.com/user-attachments/assets/4c4fef7c-e882-4ba1-a8f7-8881ed384253">

Prompt instruction :
    instruction="""Please extract relevant sentences from the provided context that is absolutely required answer the following question. If no relevant sentences are found, or if you believe the question cannot be answered from the given context, return the phrase **"Insufficient Information"**.  While extracting candidate sentences you're not allowed to make any changes to sentences from given context.""",

**Comment by jjmachan** [comment]
thanks for reporting this! will be improve with #1012
