### ISSUE TITLE
[Questions] How to change the model based on the metrics?

### ISSUE THREAD

**Issue by zhuraromdev** [explodinggradients/ragas#1132]
Hello,

I hope, that you are doing well, I have a question, regarding metrics correlation to model quality. I have implemented all the metrics, which are provided. And now thinking in the way, how can I improve the model based on the metrics. Do you have any idea in which direction I need to take a look? So is it possible to have correlation between metrics and model "quality"?

For example, if some metric is low, I can make a conclusion, that the data for fine tuning of the model is in bad quality etc. Kinda get recommendation.

Thank you!

**Comment by jjmachan** [comment]
@zhuraromdev 
![](https://docs.ragas.io/en/stable/_static/imgs/component-wise-metrics.png)

this image might help you. The idea is you measure each component and figure out how to improve the generator part of retriever part
