### ISSUE TITLE
ValidationError with OpenAIEmbeddings in Ragas

### ISSUE THREAD

**Issue by SushmitaSingh96** [explodinggradients/ragas#1133]
A `ValidationError` occurs when trying to use the `evaluate` function from Ragas with the `OpenAIEmbeddings` model. The error message suggests using `AzureOpenAIEmbeddings` when using Azure, but I am using the standard OpenAI API.

**To Reproduce**

1. Use the following code from the Ragas documentation: [Metrics - Answer Correctness](https://docs.ragas.io/en/latest/concepts/metrics/answer_correctness.html)
2. Run the code, and observe the error.

```python
from datasets import Dataset 
from ragas.metrics import answer_correctness
from ragas import evaluate

data_samples = {
    'question': ['When was the first super bowl?', 'Who won the most super bowls?'],
    'answer': ['The first superbowl was held on Jan 15, 1967', 'The most super bowls have been won by The New England Patriots'],
    'ground_truth': ['The first superbowl was held on January 15, 1967', 'The New England Patriots have won the Super Bowl a record six times']
}
dataset = Dataset.from_dict(data_samples)
score = evaluate(dataset, metrics=[answer_correctness])
score.to_pandas()
```

**Error Message**

```...
  181 def embedding_factory(
  182     model: str = "text-embedding-ada-002", run_config: t.Optional[RunConfig] = None
  183 ) -> BaseRagasEmbeddings:
--> 184     openai_embeddings = OpenAIEmbeddings(model=model)
  185     if run_config is not None:
...
  343     object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for OpenAIEmbeddings
__root__
  If you are using Azure, please use the `AzureOpenAIEmbeddings` class. (type=value_error)
```

**Expected behavior**

The code should execute without errors, generating the evaluation scores and converting them to a pandas DataFrame.

**Suggested Workaround**

The issue seems to be related to the LangChain framework, and a suggested workaround can be found [here](https://github.com/langchain-ai/langchain/issues/18727).

The code change is:

```python
embeddings = OpenAIEmbeddings(openai_api_type="openai")
```

**Environment:**
- OS: MacOS
- Python version: 3.11.9
- Ragas version: 0.1.10
- langchain_openai version: 0.1.7
- openai version: 1.36.1

**Comment by jjmachan** [comment]
thanks for reporting this @SushmitaSingh96, seems like the fix you suggested should help but not sure why I don't see it in mine

have you set `OPENAI_API_TYPE` in your env ?

**Comment by Nandhini25S** [comment]
I encountered the same problem and tried the same code from dosubot. Even after running the exact code produced by it, I keep getting this error. Is this because of some discrepancy from my side? 

`pydantic_core._pydantic_core.ValidationError: 1 validation error for OpenAIEmbeddings
openai_api_key
  Extra inputs are not permitted [type=extra_forbidden, input_value='no-key', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/extra_forbidden
`
