### ISSUE TITLE
Include 'Reason/Justification' in the result along with scores

### ISSUE THREAD

**Issue by DincyKajol** [explodinggradients/ragas#1134]
I would like to know how to include justifications in the results along with the scores when using the evaluate function in the RAGAS framework. Currently, the function only returns the scores without any explanations or justifications, which makes it difficult to understand the reasoning behind the scores.

**Comment by jjmachan** [comment]
@DincyKajol are you using any tracing tools? can you check out the docs [Explainability through Logging and tracing | Ragas](https://docs.ragas.io/en/stable/howtos/applications/tracing.html) and let me know if that helps?
