### ISSUE TITLE
[R-288] Limit Evolution

### ISSUE THREAD

**Issue by ArjunBakhale** [explodinggradients/ragas#1143]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

Is there a way to add a arg to testset generation that sets max evolutions to something like 1 instead of 5

i.e
```py
run_config = RunConfig(timeout= 360, max_retries=2, max_wait=60, max_workers=32, log_tenacity=True, **max_evolutions=2**)

current_testset = generator.generate_with_langchain_docs(document, test_size=test_size_gen, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25}, run_config = run_config )
```

Thank you :)

<sub>[R-288](https://linear.app/exploding-gradients/issue/R-288/limit-evolution)</sub>

**Comment by jjmachan** [comment]
@ArjunBakhale that is a good suggestion but I'm not sure if we should do it like that (still thinking about it). Could you tell me the reasoning behind the suggestion to get some more context?

but alternatively this is what you should be able to do today
```py
# max_tries for each evolution
simple.max_tries = 1
reasoning.max_tries = 1
multi_context.max_tries = 1

current_testset = generator.generate_with_langchain_docs(
  document, 
  test_size=test_size_gen, 
  distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25}, 
  run_config = run_config 
)
```
what do you think of that? alternatively I'm thinking we should rename that to something like `max_evolutions` to make it easier to understand?
