### ISSUE TITLE
Support vLLM

### ISSUE THREAD

**Issue by sam-h-bean** [explodinggradients/ragas#115]
```
Exception: n=1 was passed to generate but the LLM VLLM
Params: {} does not support it. Raise an issue if you want support for {llm}.
```

Following the instructions from the exception.

**Comment by jjmachan** [comment]
Thank you for raising this and we are working on adding the feature to support this. Are you using this https://github.com/vllm-project/vllm directly or via huggingface?

Also, another thing to keep in mind is that all the tests have been done with openai so other opensource models might perform differently, which models are you considering using?

**Comment by ishaan-jaff** [comment]
@sam-h-bean made a PR for this https://github.com/explodinggradients/ragas/pull/118
