### ISSUE TITLE
Issue in Context Recall Metrics

### ISSUE THREAD

**Issue by Anjalisoni99-byte** [explodinggradients/ragas#1168]
According to Ragas docs, Context Recall is calculated based on ground truth and context. But in github repo , it is using question, context and answer (model response not the ground truth). 
<img width="440" alt="Screenshot 2024-08-05 125043" src="https://github.com/user-attachments/assets/d50b7485-f60c-41c1-98ca-57b9d0502fa6">
<img width="649" alt="Screenshot 2024-08-05 125138" src="https://github.com/user-attachments/assets/0c3dd5ad-e79f-4133-95e7-8d497369dee1">

Can anyone explain or whether I am interpreting incorrectly?

**Comment by Anjalisoni99-byte** [comment]
@dosu Can you justify the mismatch between doc and codebase?

**Comment by jjmachan** [comment]
@shahules786 can you take a look at this?

**Comment by shahules786** [comment]
Hi @Anjalisoni99-byte I have raised a fix for this https://github.com/explodinggradients/ragas/pull/1173
To expand it little more on why question is needed, there could be examples in your evaluation dataset like
```
'question': Wha is the capital of France?
"ground_truth":"Paris"
"Context":"France is in western.......nd Paris it's capital"
```
Here by also providing a question along with ground_truth, the LLM gets a better idea of the answer itself and it can rephrase the ground_truth to "Pairs is the capital of France" and do the inference against the provided context. Checkout a of few shot examples [here](https://github.com/explodinggradients/ragas/blob/d2486f117fd827dcfc3e196d4cf7798573c55b09/src/ragas/metrics/_context_recall.py#L75)

**Comment by sahusiddharth** [comment]
Hi @jjmachan and @shahules786, Correct me if I am wrong,


The way I understood context recall is it only takes context and answer and doesn't require the question. 

Have a look at the instruction prompt used in the codebase of context recall,
  
```python
instruction="""Given a context, and an answer, analyze each sentence in the answer and classify if the sentence can be attributed to the given context or not. Use only "Yes" (1) or "No" (0) as a binary classification. Output json with reason."""
```

**Comment by shahules786** [comment]
Checkout the few shot examples pointed in this comment [here](https://github.com/explodinggradients/ragas/issues/1168#issuecomment-2270353914)
Not only the instruction but also few shot examples influence results of LLMs.
