### ISSUE TITLE
Answer relevancy use custom embedding

### ISSUE THREAD

**Issue by starrywheat** [explodinggradients/ragas#117]
At the moment,  this metrics use OpenAIEmbedding by default.
Can we allow this to use custom embedding instead ?

**Comment by shahules786** [comment]
Hi @starrywheat , which metrics are you using? and which embedding are you planning to use instead of OpenAI embeddings?

**Comment by starrywheat** [comment]
Hi @shahules786, as the title suggests, I am looking at the answer relevancy  which I believe require sentence embedding for the answers comparison. 
And besides OpenAI, I want to be able to use open source embedding such as BAAI/bge-base-en. This would be a reasonable and better choice than text-embedding-ada-002, according to the [HF leaderboard](https://huggingface.co/spaces/mteb/leaderboard). Plus, having flexibility is often good.

**Comment by starrywheat** [comment]
@shahules786, I made it worked in my local branch by modifying a couple lines in the answer_relevancy.py.
I am happy to contribute to this.

**Comment by shahules786** [comment]
@starrywheat  great, you can raise PR if you already have the code. I will have to do some ablation studies before merging it, and the shorter max sequence length of Bge embedding is a concern. Even though I am sure that it's better than Ada.

**Comment by starrywheat** [comment]
@shahules786 sounds  great I will do that. 
And happy to further discuss the pros and cons of various embeddings  and how best to integrate  into the metrics  in  the PR

**Comment by starrywheat** [comment]
@shahules786  I don't think I have access to create new branch for PR. Can you help me with that

**Comment by shahules786** [comment]
@starrywheat Are you working on a forked version? If not I would suggest to fork the repo and then make your changes on it. Then you should be able to raise a PR from your forked ragas version to here. 
Here the [guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by lalehsg** [comment]
Hi all, I am interested in using bge-small-en-v1.5 instead of open ai ones, as mentioned in this issue. Seems that this capability has been added. I am looking for an example code snippet to how to wrap/calll the custom embeddings. I'd appreciate your help!

**Comment by shahules786** [comment]
Hi, please install ragas from source and follow https://docs.ragas.io/en/latest/howtos/customisations/embeddings.html

**Comment by lalehsg** [comment]
Hi @shahules786 This was very helpful and I was able to run locally easily. Now, I need to run it on a more restricted env. so, can't really do install from source. was wondering if this has been part of a recent version release. so that i just pip install, the usual way and get the feature. thanks again in advance!
