### ISSUE TITLE
ModuleNotFoundError: No module named 'ragas.cost'

### ISSUE THREAD

**Issue by CaduSantana** [explodinggradients/ragas#1172]
[X] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Description**
Tried running the code from [the cost calculation page on the documentation](https://docs.ragas.io/en/latest/howtos/applications/cost.html). When the interpreter reaches the expression `from ragas.cost import get_token_usage_for_openai`, I get an `ModuleNotFoundError: No module named 'ragas.cost'` error.

Ragas version: 0.1.12 (from Conda)
Python version: 3.11.9

**Code to Reproduce**

```python
# lets import a parser for OpenAI
from ragas.cost import get_token_usage_for_openai
``` 

**Error trace**
ModuleNotFoundError: No module named 'ragas.cost'

**Expected behavior**
Should import the method as usual.

**Additional context**
I also tried running this [notebook](https://github.com/explodinggradients/ragas/blob/d2486f117fd827dcfc3e196d4cf7798573c55b09/docs/howtos/applications/cost.ipynb#L7). Returns the same error.

**Comment by jjmachan** [comment]
dosu is right - but new release will be out in a couple of hours so that works too

**Comment by CaduSantana** [comment]
Thanks for the quick response!
It did work, as is, i managed to import and summon it, following the documentation. However, when reaching the evaluation part...

```python
from ragas import evaluate
from ragas.cost import get_token_usage_for_openai

result = evaluate(
    amnesty_qa["eval"],
    metrics=[
        context_precision,
        faithfulness,
        answer_relevancy,
        context_recall,
    ],
    llm=gpt4o,
    token_usage_parser=get_token_usage_for_openai
)
``` 
...i get the `TypeError: evaluate() got an unexpected keyword argument 'token_usage_parser'` error - which is weird, since the constructor appears correct here.

![image](https://github.com/user-attachments/assets/92d005d6-5968-4e16-9a22-38a5fa8039d2)

**Comment by CaduSantana** [comment]
> dosu is right - but new release will be out in a couple of hours so that works too. @CaduSantana do share you feedback on the cost module though would really appreciate it 🙂

@jjmachan Unfortunately I ran into another issue. Although I've followed [this page](https://docs.ragas.io/en/latest/howtos/applications/data_preparation.html), I get the `AttributeError: 'str' object has no attribute 'set_run_config'` error. As I stumbled on Issue #413, I thought it would be prudent to instead try the examples on the documentation first:

```python
from datasets import Dataset 

data_samples = {
    'question': ['When was the first super bowl?', 'Who won the most super bowls?'],
    'answer': ['The first superbowl was held on January 15, 1967', 'The most super bowls have been won by The New England Patriots'],
    'contexts' : [['The Super Bowl....season since 1966,','replacing the NFL...in February.'], 
    ['The Green Bay Packers...Green Bay, Wisconsin.','The Packers compete...Football Conference']],
    'ground_truth': ['The first superbowl was held on January 15, 1967', 'The New England Patriots have won the Super Bowl a record six times']
}
dataset = Dataset.from_dict(data_samples)
``` 

However, it still returns the same error (`AttributeError: 'str' object has no attribute 'set_run_config'`).

**Comment by jjmachan** [comment]
@CaduSantana could you share the trace for the same?

**Comment by CaduSantana** [comment]
@jjmachan Yes. As it follows:

```powershell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 12
      1 from datasets import Dataset 
      3 # data_samples = {
      4 #     'question': ['When was the first super bowl?', 'Who won the most super bowls?'],
      5 #     'answer': ['The first superbowl was held on January 15, 1967', 'The most super bowls have been won by The New England Patriots'],
   (...)
      9 # }
     10 # dataset_ = Dataset.from_dict(data_samples)
---> 12 result = evaluate(
     13     dataset_,
     14     llm="gpt-4o-mini",
     15     token_usage_parser=get_token_usage_for_openai,
     16 )

File ~/anaconda3/envs/rag_venv/lib/python3.11/site-packages/ragas/_analytics.py:129, in track_was_completed.<locals>.wrapper(*args, **kwargs)
    126 @wraps(func)
    127 def wrapper(*args: P.args, **kwargs: P.kwargs) -> t.Any:
    128     track(IsCompleteEvent(event_type=func.__name__, is_completed=False))
--> 129     result = func(*args, **kwargs)
    130     track(IsCompleteEvent(event_type=func.__name__, is_completed=True))
    132     return result

File ~/anaconda3/envs/rag_venv/lib/python3.11/site-packages/ragas/evaluation.py:199, in evaluate(dataset, metrics, llm, embeddings, callbacks, in_ci, run_config, token_usage_parser, raise_exceptions, column_map)
    196             reproducable_metrics.append(i)
    198     # init all the models
--> 199     metric.init(run_config)
    201 executor = Executor(
    202     desc="Evaluating",
    203     keep_progress_bar=True,
    204     raise_exceptions=raise_exceptions,
    205     run_config=run_config,
    206 )
    208 # Ragas Callbacks
    209 # init the callbacks we need for various tasks

File ~/anaconda3/envs/rag_venv/lib/python3.11/site-packages/ragas/metrics/base.py:150, in MetricWithLLM.init(self, run_config)
    146 if self.llm is None:
    147     raise ValueError(
    148         f"Metric '{self.name}' has no valid LLM provided (self.llm is None). Please initantiate a the metric with an LLM to run."  # noqa
    149     )
--> 150 self.llm.set_run_config(run_config)

AttributeError: 'str' object has no attribute 'set_run_config'
```

**Comment by jjmachan** [comment]
the code @CaduSantana is wrong 
```py
llm="gpt-4o-mini",
```

that should not be a string but an LLM. 

```py
result = evaluate(
     13     dataset_,
     14     metrics=[answer_relevancy, faithfulness, context_recall, context_precision],
     16     token_usage_parser=get_token_usage_for_openai,
     17 )
```

just do this instead

**Comment by CaduSantana** [comment]
Oh, so that was the issue.
Thanks for the headsup! 

Also

> dosu is right - but new release will be out in a couple of hours so that works too. @CaduSantana do share you feedback on the cost module though would really appreciate it 🙂

Bretty gud 👍. It reflected correctly our costs on the OpenAI dashboard. I like how simple and easy it is.

Great project and hope you guys keep growing this!

**Comment by CaduSantana** [comment]
Close comment.

**Comment by jjmachan** [comment]
@CaduSantana awesome! great to hear that 🙂. We will keep growing this too - we want to build an open-source standard for evaluations, lets see how it goes 😅 🤞🏽 

btw if you have any feedback or ideas for improvement do share it here on discord too 🙌🏽
