### ISSUE TITLE
[R-293] Noise sensitivity metrics from RAGChecker

### ISSUE THREAD

**Issue by shahules786** [explodinggradients/ragas#1185]
RAGChecker from AWS has [noise sensitivity](https://github.com/amazon-science/RAGChecker/tree/main/ragchecker
) metrics that could be useful to Ragas users 

TBD
1) Implement metrics
2) Prepare docs to intuitively explain how it's calculated and how can it be used. 

<sub>[R-293](https://linear.app/exploding-gradients/issue/R-293/noise-sensitivity-metrics-from-ragchecker)</sub>

**Comment by sky-2002** [comment]
Hey @shahules786 I will take up

**Comment by shahules786** [comment]
@sky-2002 Great, assigned to you.
