### ISSUE TITLE
OpenAI key not found

### ISSUE THREAD

**Issue by gabriead** [explodinggradients/ragas#122]
Hey guys,
I have a problem that occured all of a sudden. I am using the Azure OpenAI client and it worked until recently. Now I am getting the error ´ Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter.´
I am setting the paramters like so at the beginning of the code:

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_KEY"] = "..................................."
os.environ["OPENAI_API_VERSION"] = "....................................."
os.environ["OPENAI_API_BASE"] = "..........................."

llm = AzureOpenAI(deployment_name = ".................................", openai_api_key=os.environ["OPENAI_API_KEY"])
Passing it as a named parameter to the evaluate method did not solve it by the way.

I have absolutely zero idea where this is coming from. Can anyone hint me in a direction?

**Comment by gabriead** [comment]
I have included the openai parameters in the base.py since there is a method named _llm_factory which is calling the openai API and that seems to have fixed it. But why is that necessary all of a sudden?

**Comment by jjmachan** [comment]
that was because by default Langchain OpenAI LLMs through an error if openAI API keys are not found. But have you checked this out https://github.com/explodinggradients/ragas/blob/main/docs/guides/llms.ipynb

**Comment by jjmachan** [comment]
hey @gabriead closing this since [this guide](https://github.com/explodinggradients/ragas/blob/main/docs/guides/quickstart-azure-openai.ipynb) should help with these issues. Feel free to reopen if not

would love to chat with you sometime as well, are you in the discord group?

**Comment by amittos** [comment]
@jjmachan I have a similar issue (please, see [here](https://github.com/explodinggradients/ragas/issues/303)). The URLs that you have shared in this thread are broken, unfortunately, so I don't know how to address it.

**Comment by R-beep-AI** [comment]
@jjmachan Hi, Same Issue Here.

**Comment by vprzybylo** [comment]
The Azure guide seems to have moved to [here](https://github.com/explodinggradients/ragas/blob/main/docs/howtos/customisations/azure-openai.ipynb), which helped me get past this
