### ISSUE TITLE
No evaluation possible with context_relevancy/answer_relevancy/context_recall/harmfullness for Azure OpenAI

### ISSUE THREAD

**Issue by gabriead** [explodinggradients/ragas#126]
Hi guys,

I am using Azure OpenAI and the only evaluation method that is currently working is "faithfullness". All the others fail with the same error ```Exception: n=3 was passed to generate but the LLM AzureOpenAI
Params: {'deployment_name': '.........', 'model_name': 'text-davinci-003', 'temperature': 0.2, 'max_tokens': 256, 'top_p': 1, 'frequency_penalty': 0, 'presence_penalty': 0, 'n': 1, 'request_timeout': None, 'logit_bias': {}} does not support it. Raise an issue if you want support for {llm}.```

**Comment by gabriead** [comment]
Ah I guess the problem is coming from here:

 ```
if isinstance(llm, OpenAI) or isinstance(llm, ChatOpenAI)
 ```
i have included 
 ```
if isinstance(llm, OpenAI) or isinstance(llm, ChatOpenAI) or isinstance(llm, AzureOpenAI)
 ```
to the mix.

**Comment by jjmachan** [comment]
thank you for pointing the error out and fixing it. We haven't gotten access to Azure openAI yet so haven't been able to test it out. if you can make a PR after testing it, it would be really helpful and much appreciated :)

I think we can also add `AzureChatOpenAI` too as a check.

**Comment by jjmachan** [comment]
Hey @gabriead I've added a fix for this in that  PR but like I said since we don't have access to Azure instances yet I can't run the tests at my end. I would really appreciate it if you could test it on your end if it fixes your issue.

Would really help us a lot 😄

**Comment by gabriead** [comment]
Hey guys, just pulled and that fixes the issue :-)
