### ISSUE TITLE
local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by Sckarge** [explodinggradients/ragas#127]
Issue in src/ragas/metrics/llms.py
The result variable is not initiated outside the if elif else blocks.

**Comment by jjmachan** [comment]
thanks a lot for pointing that out, Is it causing a runtime exception for you? Which Python version are you using. 

will fix this shortly

**Comment by Sckarge** [comment]
Yes I was using Google colab (python 3.7) and I got this runtime error. I was trying to use FLAN-T5 as the llm in evaluate.
