### ISSUE TITLE
ragas v0.1.17 raise Original column names {'contexts'} not in the dataset. 

### ISSUE THREAD

**Issue by landhu** [explodinggradients/ragas#1271]
[ ] I have checked the [documentation](https://docs.ragas.io/en/stable/howtos/applications/data_preparation.html) and related resources and couldn't resolve my bug.

**Only evaluate answer_correctness, answer_similarity. and datasets not include contexts, only  ['question', 'answer', 'ground_truth'],  it can work before 0.1.16**

Ragas version: v0.1.17
Python version: python10

**Code to Reproduce**
data_samples = {'question': ['When did Einstein born?',]'answer': ['Einstein was born in Germany.'],'ground_truth': ['Einstein was born in 1879 in Germany.']}
dataset = Dataset.from_dict(data_samples)
score = evaluate(dataset, metrics=[answer_correctness, answer_similarity])

**Error trace**
  File "D:\Program Files\Python310\lib\site-packages\datasets\arrow_dataset.py", line 2329, in rename_columns
    raise ValueError(
ValueError: Original column names {'contexts'} not in the dataset. Current columns in the dataset: ['question', 'answer', 'ground_truth']

**Expected behavior**
answer_correctness, answer_similarity not use contexts. why needs contexts
and it's work before v0.1.16

**Comment by landhu** [comment]
@dosu it's not work. when I added
` column_map = {'contexts': 'ground_truth'}
score = evaluate(dataset, metrics=[answer_correctness, answer_similarity], column_map=column_map)
`
it's shows 
`  File "D:\Program Files\Python310\lib\site-packages\datasets\arrow_dataset.py", line 2329, in rename_columns
    raise ValueError(
ValueError: Original column names {'ground_truth'} not in the dataset. Current columns in the dataset: ['question', 'answer', 'contexts']`

**Comment by shahules786** [comment]
Hey @landhu We are moving to a new data representation format to add support to metrics beyond RAG as per #1009 . But this should be a bug, I'll check it out and raise a fix soon.
