### ISSUE TITLE
protobuf version incompatible with tf

### ISSUE THREAD

**Issue by albiross** [explodinggradients/ragas#128]
i am facing problems during the installation phase. It seems that the protobuf version required does not match dependencies required by tensorflow >= 2.13.0.
![image](https://github.com/explodinggradients/ragas/assets/50795192/3c09bdb1-2784-4f47-bfe6-bef5309fe957)

**Comment by jjmachan** [comment]
Hey @albiross thanks for bringing this up. I will be releasing the fix shortly. Please do test it out and see if it works.

Thanks again :)
