### ISSUE TITLE
Quality of metrics questionable with Azure OpenAI

### ISSUE THREAD

**Issue by gabriead** [explodinggradients/ragas#129]
Hi guys,
I am evaluating the quality of the metrics in your framework for my RAG use case. So far I a am afraid to say that most prompts and responses are not delivering the expected result and are therefore not reliable. I am using the Azure OpenAI endpoint with GPT 3.5 so it is very possible that it has everything to do with that. Can anyone else confirm this observation?

**Comment by gabriead** [comment]
I can offer a debugging session with the authors/contributors if that's helpful.

**Comment by shahules786** [comment]
Hi @gabriead , thanks for raising this issue. We are continuously working to improve the quality of metrics. We do have some updates coming soon but would certainly benefit from your input. If you wish you do this over a call I can personally write to you over an email.

**Comment by jjmachan** [comment]
Hey @gabriead as shahul said we are continuously working to improve the quality of the metrics in ragas and really appreciate your offer to help us debug with a combined debugging session - would be super helpful for us. I've sent a mail to the mail-id in your github but if that is not the correct one do let us know your mail id or write to us at team@explodinggradients.com 

looking forward to meeting you Adrian and having a nice debugging session :)

**Comment by jjmachan** [comment]
@gabriead we have made a lot of improvements to ragas now for reproducibility so this should have improved. Please feel free to reopen if this is still an issue.

@shahules786 shall we close this?
