### ISSUE TITLE
I cannot reproduce the results of the baseline because its context_relevancy is too high.

### ISSUE THREAD

**Issue by zc277584121** [explodinggradients/ragas#130]
I cannot reproduce the results of the fiqa baseline in this notebook:
https://github.com/explodinggradients/ragas/blob/main/experiments/baselines/fiqa/dataset-exploration-and-baseline.ipynb

At the end of this notebook, is shows the score:
{'NLI_score': 0.8655555555555556, 'answer_relevancy': 0.8737666666666667, 'context_ relevancy': 0.8181444444444443, 'ragas_score': 0.8517704492684051}

But when I test, the score I get is:
```json
{
      "context_ relevancy": 0.10368744449698047,
      "faithfulness": 1.0,
      "answer_relevancy": 0.9286177818722253,
      "context_recall": 0.6370370370370371,
      "harmfulness": 0.0,
      "ragas_score": 0.300955397960847,
}
```
I noticed that my context_relevancy is very low. I know that in the latest pr, the prompt used to test context_relevancy has been modified, but I am not running with this latest version. But I don’t think it’s caused by this, because this jupyter notebook seems to be running with an old version.
In addition to the context_relevancy value, there seem to be some gaps in the other values. So I'm wondering, what could be causing this?

**Comment by shahules786** [comment]
Hi @zc277584121 , the results for the quickstart notebook were generated using an older version of fiqa dataset which contained very few rows.  So if you run it now on the entire dataset the scores will be different.

**Comment by zc277584121** [comment]
Thank you for your answer.
So can you update it and consider it as a standard baseline? This way other RAG frameworks can easily compare with it.

**Comment by zc277584121** [comment]
I saw that it was using the first 30 rows. My results were also generated using the first 30 rows, not the entire data set.

@shahules786 , You mean, it uses an older version of the dataset and it has less than 30 rows?

**Comment by shahules786** [comment]
In the example, it selects the first 3 rows of the dataset `fiqa_eval["baseline"].select(range(3))`, not 30. I can run and update the notebook with the newer version. Would that help?

**Comment by zc277584121** [comment]
Thank you very much for your answer. I suggest you provide a stable and reproducible baseline so that other RAG frameworks can be compared with it. 😊

**Comment by shahules786** [comment]
Sure. Could you tell me what you're trying to achieve? Is this issue a blocker for your use case?
 I'm asking because since we are updating the code to improve metrics, there can be changes in the values of scores dedicated in the quickstart.

**Comment by zc277584121** [comment]
@shahules786 , This will not block our use. Even if the reproduced results are different from those in the notebook, I will currently use the results of my local run instead of those in the notebook. I was originally worried that there was something wrong with my reproduction process, but now it seems there is no problem.

**Comment by shahules786** [comment]
@zc277584121 Thank you.
