### ISSUE TITLE
Why is Context Relevancy removed from official documentation?

### ISSUE THREAD

**Issue by linzzzzzz** [explodinggradients/ragas#1330]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
Why is Context Relevancy removed from official documentation?

I can see it in the older version of doc.
https://docs.ragas.io/en/v0.1.0/concepts/metrics/context_relevancy.html

But not in the latest doc. 
https://docs.ragas.io/en/stable/concepts/metrics/context_relevancy.html

Why is that?

**Code Examples**
This community speaks code. Share your code snippets to help us understand your question better.

**Additional context**
Anything else you want to share with us?

**Comment by shahules786** [comment]
@linzzzzzz context relevancy was depreciated from v0.1 in favor of context utilisation. https://docs.ragas.io/en/stable/concepts/metrics/context_utilization.html
