### ISSUE TITLE
Request to replace fuzzywuzzy with rapidfuzz in the Jaccard(Similarity) class due to licensing restrictions

### ISSUE THREAD

**Issue by AishAmalgam** [explodinggradients/ragas#1360]
I would like to request that ragas uses rapidfuzz instead of fuzzywuzzy in the Jaccard(Similarity) class. fuzzywuzzy uses the GPL-2.0 license, which prevents its usage in projects with more restrictive licensing requirements. 

rapidfuzz offers similar functionality but is licensed under the more permissive MIT license, which would allow broader adoption and remove the licensing conflict.

In our project, we cannot use any libraries under GPL licenses, including fuzzywuzzy. As ragas currently depends on fuzzywuzzy, this creates a conflict. Replacing it with rapidfuzz would enable us to continue using ragas while staying within our project's licensing guidelines.

If there is any alternative approach to solve this issue, I would appreciate your suggestions. We want to ensure compatibility with more permissive licenses like MIT.

Thank you for your time and support!

**Comment by shahules786** [comment]
Hey @AishAmalgam thanks for pointing it out. It's use in metrics was already removed but the dependency remained due to one function in experimental testgen. Just raised a PR to replace it.

**Comment by jjmachan** [comment]
resolved already 🙂
