### ISSUE TITLE
give me the conclusion for this topic we are getting far from the real context.

### ISSUE THREAD

**Issue by amin-kh96** [explodinggradients/ragas#1367]
give me the conclusion for this topic we are getting far from the real context.
I know it is better to let the ragas do the embeddings but if i want to consider the cost or price for this
is it better to use my own  calculated embeddings and then in some ways or method make sure that my embeddings are suitable or compatible for using ragas,

_Originally posted by @amin-kh96 in https://github.com/explodinggradients/ragas/issues/1358#issuecomment-2376449771_

**Comment by jjmachan** [comment]
this is a duplicated
