### ISSUE TITLE
No module named 'ragas.metrics.critique'

### ISSUE THREAD

**Issue by robin-mader-bis** [explodinggradients/ragas#1374]
[X] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
Trying to import `ragas.metrics.critique` results in `ModuleNotFoundError: No module named 'ragas.metrics.critique'`.
Latest working version seems to be 0.1.18. Starting in 0.1.19 the error occurs. I assume this PR broke the behavior: #1286.

It seems that most of the functionality has been moved to `ragas.metric._aspect_critic`. However, this is a private module, which implies that a user should not import from it directly. But the pre-defined AspectCritics (harmfulness, maliciousness, etc.) which could previously be imported from `ragas.metric.critique` are only importable from this module now.

Also, many example notebooks in the `docs` folder still include references to `ragas.metric.critique`.

Ragas version: 0.1.20
Python version: 3.11.7

**Code to Reproduce**
```python
>>> import ragas.metric.critique
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ragas.metric'
```

**Error trace**
See above

**Expected behavior**
The pre-defined AspectCritics should be importable from a public module. Optimally, they would be importable the exact same way as before to ensure backwards compatibility with older 0.1.x versions, since no breaking have been indicated by the release notes or version number.
```python
from ragas.metrics.critique import harmfulness

# Suggested Alternatives
from ragas.metrics.aspect_critic import harmfulness
from ragas.metrics import harmfulness
```

**Additional context**
As a workaround, the metrics can be imported from the private module:
```python
from ragas.metrics._aspect_critic import harmfulness
```

**Comment by jjmachan** [comment]
@robin-mader-bis appologies for the hard time, will fix this shortly
in the mean time you can use the metric like so `from ragas.metrics._aspect_critic import harmfulness`

but will make a PR shortly to switch it to `from ragas.metrics.aspect_critic import harmfulness` as you suggested
