### ISSUE TITLE
Issue with Context type

### ISSUE THREAD

**Issue by netranga** [explodinggradients/ragas#143]
I am trying to run evaluate on outputs generated by GPT4. I have the columns structured in the desired format however am running into the following error

Dataset feature "contexts" should be of type Sequence[string[, got <class 'datasets.features.features.Value'>

Any tips on how to resolve? Thank you!

**Comment by shahules786** [comment]
Hi @netranga, the context should be given as a list of strings. Can you make sure that this is correct?

**Comment by netranga** [comment]
Yes this is the correct input - now hitting the following error:
"Must provide an 'engine; or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>.

I have set my API Key to my azure_token - I am accessing models through Azure but running my code with Sagemaker. Would this be causing an issue?

**Comment by jjmachan** [comment]
hey @netranga sorry about the late response but just published a new guide [here](https://github.com/explodinggradients/ragas/blob/main/docs/guides/quickstart-azure-openai.ipynb) that should help with this issue. Hope you find it useful

**Comment by mariamaslam** [comment]
Hi @jjmachan im trying to access this ../quickstart-azure-openai.ipynb/ it is no longer available
