### ISSUE TITLE
How to use the package without ChatGPT/OpenAI ?

### ISSUE THREAD

**Issue by nprime496** [explodinggradients/ragas#1448]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**

Hi, I am trying to generate test samples using ragas. I followed the documentation for custom models but I get an error regarding ChatGPT. 

I never instantiated OpenAI and don't want to. What is this model used for and how do I disable/replace it ?

**Code Examples**
This community speaks code. Share your code snippets to help us understand your question better.

Here is the code :

 ```python
from ragas.testset import TestsetGenerator
from langchain_ollama.llms import OllamaLLM
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
from langchain_community.document_loaders import PyMuPDFLoader
import os 


# generator with openai models
generator_llm = OllamaLLM(model="gemma2:2b")
critic_llm = OllamaLLM(model="gemma2:2b")

embeddings = FastEmbedEmbeddings()

pdf_path = os.path.join("documents", "sample.pdf")

loader = PyMuPDFLoader(pdf_path)

docs = loader.load()
generator = TestsetGenerator.from_langchain( generator_llm)#, generator_llm, embeddings )


dataset = generator.generate_with_langchain_docs(docs, test_size=10)
```
However, I get an error  : 

```
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Additional context**

None.

**Comment by Spawnfile** [comment]
Have you succesfully executed your test without openai ? @nprime496

**Comment by jjmachan** [comment]
@Spawnfile @nprime496 appologies for the confusion - dosu was incorrect here

all you have to do is 
```py
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

# generator with openai models
generator_llm = ChatOpenAI(model="gpt-3.5-turbo-16k")
critic_llm = ChatOpenAI(model="gpt-4")
embeddings = OpenAIEmbeddings()

generator = TestsetGenerator.from_langchain(
    generator_llm,
    critic_llm,
    embeddings
)

# generate testset
testset = generator.generate_with_langchain_docs(documents, test_size=10, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
```

now edit the llms with which ever you want - in your case you only changed one llm so Ragas will use the default llm for critic 

docs: https://docs.ragas.io/en/stable/getstarted/testset_generation.html
https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html

could you tell let me know if it works? feel free to ask any further questions here 🙂

**Comment by jjmachan** [comment]
@nprime496 take a look at this in that case https://docs.ragas.io/en/latest/getstarted/rag_testset_generation/

**Comment by jjmachan** [comment]
@nprime496 this is because of the embeddings in the transforms are defaulting to OpenAI - thanks a lot for reporting this - I will get this fixed shortly 🙂

**Comment by jjmachan** [comment]
@frr163 this has been fixed already
![image](https://github.com/user-attachments/assets/ab4433eb-dc88-443c-bb67-ccb6cb151de5)

do check out the docs here https://docs.ragas.io/en/latest/getstarted/rag_evaluation/#choosing-evaluator-llm
