### ISSUE TITLE
The documentation is not up to date with the code

### ISSUE THREAD

**Issue by nprime496** [explodinggradients/ragas#1454]
[ x ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**

The documentation is not on par with the code : https://docs.ragas.io/en/stable/howtos/customisations/ragas_custom_model.html

Ragas version: 0.1.21
Python version: 3.10

**Code to Reproduce**

```
from ragas.testset.evolutions import ComplexEvolution
```

**Error trace**

```
from ragas.testset.evolutions import ComplexEvolution
ModuleNotFoundError: No module named 'ragas.testset.evolutions'
```

**Expected behavior**

A successful import.

**Additional context**

**Comment by jjmachan** [comment]
hey @nprime496 I'm not sure there is a problem - justed added a test to confirm

https://github.com/explodinggradients/ragas/pull/1460
