### ISSUE TITLE
metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by vohoangkh4ng** [explodinggradients/ragas#1457]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
when i import library from ragas i get 
metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Code Examples**
from ragas.metrics import faithfullness
from ragas import evaluate

**Additional context**
What version of ragas i can use ?

**Comment by Mukhsin0508** [comment]
I am getting the same error but with Django viewsets

**Comment by jjmachan** [comment]
@VMinB12 @Mukhsin0508 are you guys using v0.2+
we do support the libs you mentioned now with that update

**Comment by Mukhsin0508** [comment]
@vohoangkh4ng 
There's a typo in your import: you wrote `faithfullness` instead of `faithfulness`

```
# Solution 1: Clean installation with specific versions
# First, uninstall existing packages
pip uninstall ragas langchain datasets -y

# Install specific versions known to work together
pip install ragas==0.0.22
pip install langchain==0.0.350
pip install datasets==2.14.7

# Your imports should now work
from ragas.metrics import faithfulness  # Note the correct spelling
from ragas import evaluate
```

> Check your Python version (Ragas works best with Python 3.8-3.10)
> b. Make sure you don't have conflicting packages in your environment
> c. Try running:
```
pythonCopypip freeze | grep -i "ragas\|langchain\|datasets"

```

**Comment by jjmachan** [comment]
thanks alot @Mukhsin0508 for the fix ❤️ 
closing this now
