### ISSUE TITLE
`ALL_METRICS` variable does not contain all metrics in v0.2

### ISSUE THREAD

**Issue by edjeffery** [explodinggradients/ragas#1508]
[x] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
The `ALL_METRICS` variable in the `ragas.metrics` module only has 8 of the metrics, but there are clearly far more than this.

Ragas version: 0.2.0
Python version: 3.12

**Code to Reproduce**
```python
>>> from ragas.metrics import ALL_METRICS
>>> len(ALL_METRICS)
8
```

**Error trace**
No error.

**Expected behavior**
There seem to be roughly 30 metrics, so a number closer to that. I appreciate some metrics are duplicates of others with a different name.

**Additional context**
None.

**Comment by jjmachan** [comment]
@edjeffery I think we'll remove that - it is not expected to work like that. Do check the docs and only pick the metrics you want :)
