### ISSUE TITLE
[R-309] add llamaindex support for evaluation and testset generatin in v0.2

### ISSUE THREAD

**Issue by vikrantdeshpande09876** [explodinggradients/ragas#1557]
Tried reading through the [docs](https://docs.ragas.io/) and source-code, but couldn't understand if Llama-Index support has been removed.

**Your Question**
Was working through the `ragas` with `llama-index` [tutorial](https://github.com/explodinggradients/ragas/blob/main/docs/howtos/integrations/llamaindex.ipynb), but `generator = TestsetGenerator.from_llama_index()` and `generator.generate_with_llamaindex_docs()` is no longer supported?
Is only `Langchain` supported hereon?

**Additional context**
Installed `ragas==0.2.2` using `!pip install git+https://github.com/explodinggradients/ragas`.

<sub>[R-309](https://linear.app/exploding-gradients/issue/R-309/llama-index-support-removed)</sub>

**Comment by jjmachan** [comment]
we didn't have port this integration yet but I can make this happen for you this week 🙂

**Comment by jjmachan** [comment]
@vikrantdeshpande09876 this is only for testset generation right?

**Comment by vikrantdeshpande09876** [comment]
Yes correct, testgeneration for now.
