### ISSUE TITLE
对于长文本评估指标较差的问题：

### ISSUE THREAD

**Issue by Superyeahh** [explodinggradients/ragas#1571]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
（1）对于answer、context和groud_truth较长的情况（每项约500字），如何修改代码使评估效果提升，目前存在一些指标如context_recall、faithfulness结果为空（不是0.0）的情况。
（2）大量的answer_relevancy值为0.0是正常的吗
（3）context_precision值只有0.9999999和0.0两种情况的现象也是正常的吗？
感谢您的回答！

**Comment by jjmachan** [comment]
hey @Superyeahh could you translate this to english - would help us 🙂

**Comment by Superyeahh** [comment]
> 嘿，你能把这个翻译成英文吗 - 会帮助我们 🙂

I have re-asked this question in English in issue#1572, thank you for your reply and I look forward to your answer!
