### ISSUE TITLE
Poor indicators for the assessment of long texts

### ISSUE THREAD

**Issue by Superyeahh** [explodinggradients/ragas#1572]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
(1) For cases where answer, context and groud_truth are long (about 500 words each), how can the code be modified to make the assessment more effective, currently there are some metrics such as context_recall, faithfulness results are empty (not 0.0).
(2) a large number of answer_relevancy value of 0.0 is normal
(3) Is it also normal to have only two context_precision values of 0.9999999 and 0.0?
Thanks for your answer!

**Comment by jjmachan** [comment]
hey @Superyeahh where you able to clear you doubts?

the recommended thing to do here is conect a logging and tracing tool like: https://docs.ragas.io/en/stable/howtos/customizations/metrics/tracing so that you results are more explainable
