### ISSUE TITLE
RAGAs compatibility with GISKARD

### ISSUE THREAD

**Issue by aranchod490** [explodinggradients/ragas#1582]
Currently trying to evaluate a RAG pipeline using generated tests using GISKARD and further integrating RAGAs metrics. However, after going through the documentation of GISKARD and implementation an error reading 

Package ragas.llms.prompt is missing, it is required for the computation of RAGAS metrics. You can install it with `pip install ragas.llms.prompt`.

however, ragas.llms.prompt does not exist

**Comment by jjmachan** [comment]
hey @aranchod490 with v0.2 that is no longer available, could you use v0.1 in that case or raise an issue in GISKARD to fix this?
