### ISSUE TITLE
TooManyRequests error. Even after setting Run Config

### ISSUE THREAD

**Issue by tarunn2799** [explodinggradients/ragas#1588]
[Y ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**

Trying to run Testset generation on a dataset with ~8000 llamaindex documents using Cohere's line of models. 

I constantly keep getting `cohere.errors.too_many_requests_error.TooManyRequestsError: status_code: 429, body: data=None message='You are past the per minute request limit, please wait and try again later.'`

How do I ensure rate-limiting is applied within the ragas framework? I tried setting a RunConfig like shown below, but it doesn't really help. 

```
my_run_config = RunConfig(max_workers=2, timeout=180, max_wait=120)
```

Its okay if it is slow but I just need my testset generation to run. 

Ragas version: 0.1.18
Python version: 3.11

**Code to Reproduce**

Share code to reproduce the issue
```
documents = SimpleDirectoryReader(input_files=[input_file]).load_data()
 generator_llm, critic_llm, embed_model = setup_models() #Cohere objects
 

    generator = TestsetGenerator.from_llama_index(
        generator_llm=generator_llm,
        embeddings=embed_model,
        critic_llm=critic_llm
    )

    generator.adapt(language="english", evolutions=[simple, multi_context, reasoning])
    testset = generator.generate_with_llamaindex_docs(
        documents,
        num_samples,
        distributions={simple: 0.6, reasoning: 0.2, multi_context: 0.2},
        is_async=False,
        with_debugging_logs=True,
        run_config=my_run_config
    )

```
**Error trace**

**Expected behavior**

**Additional context**

**Comment by jjmachan** [comment]
hey @tarunn2799 would it be possible to update to the latest version v0.2? we have batching in that version that should help

you can check the migration guide here: https://docs.ragas.io/en/stable/howtos/migrations/migrate_from_v01_to_v02/
