### ISSUE TITLE
[R-311] Adding exact match caching

### ISSUE THREAD

**Issue by jjmachan** [explodinggradients/ragas#1602]
add exact match catching so to save obvious LLM requests. While semantic caching might add noise exact match caching will avoid that. It also makes testset generation and evaluation options easily re-runnable - solving the issue of lost tokens in case of an error somewhere in the pipeline

refference issues

* [periodically save current progress and restart from last save · Issue #1522 · explodinggradients/ragas](https://github.com/explodinggradients/ragas/issues/1522)

<sub>From [SyncLinear.com](https://synclinear.com) | [R-311](https://linear.app/exploding-gradients/issue/R-311/adding-exact-match-caching)</sub>

**Comment by ayulockin** [comment]
Hey @jjmachan can you assign this issue to me. I would like to take a stab at this.
