### ISSUE TITLE
Issues with metrics in version 0.1.18

### ISSUE THREAD

**Issue by littlebai3618** [explodinggradients/ragas#1623]
I am migrating from version 0.1.18 to version 0.2.3. I want to find information on some metrics, but I can't find the documentation for `answer_correctness` and `answer_relevancy` metrics on the website [https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/](https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/). Are these metrics being deprecated? Previously, these metrics were stored at [https://docs.ragas.io/en/stable/concepts/metrics/answer_correctness.html](https://docs.ragas.io/en/stable/concepts/metrics/answer_correctness.html) and [https://docs.ragas.io/en/stable/concepts/metrics/answer_relevance.html](https://docs.ragas.io/en/stable/concepts/metrics/answer_relevance.html), but now these links are no longer accessible.

**Comment by jjmachan** [comment]
answer relavance is: https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/answer_relevance - it has been renamed to response relavency

answer_correctness: https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/answer_correctness

hope it helps 🙂
