### ISSUE TITLE
Creating ground truth from dynamic data

### ISSUE THREAD

**Issue by itsderek23** [explodinggradients/ragas#163]
Neat project!

Is there a way to generate the ground truth from dynamic functions, [similar to Langsmith](https://github.com/langchain-ai/langsmith-cookbook/blob/main/testing-examples/dynamic-data/testing_dynamic_data.ipynb)?

My need: I'm evaluating an agent that interacts with external APIs (specifically AWS) by generating code snippets that are then evaluated, returning JSON. The resulting JSON is fed back into the LLM and the LLM generates a natural language answer.

I'd like to have ground truth reference a function that is known to generate the data correctly for the question. This helps me test if the code generation is correct (as this is where things generally go wrong). I'd then compare the the LLM-generated JSON result to the result returned by the validated function.

...not sure if that makes sense?

**Comment by shahules786** [comment]
Hey @itsderek23 Thank you. We have a[ diverse test data generator](https://github.com/explodinggradients/ragas/blob/main/docs/Testsetgeneration.ipynb) for RAGs. But in your case, it is for the agent use case which we are also interested in exploring. Your idea certainly makes sense to me for testing agents but there can be some pitfalls we should avoid while doing so. How can we understand your use case in detail?  I can reach out to you in person.

**Comment by itsderek23** [comment]
Thanks @shahules786!

It's for [OpsTower.ai](https://github.com/opstower-ai/llm-opstower), a DevOps AI Assistant. You can see how we do the evaluation [here](https://github.com/opstower-ai/devops-ai-open-leaderboard) (shows the datasets, a reference function, and prompts).

Happy to chat! Email is on my @itsderek23 profile.
