### ISSUE TITLE
When transforms is a list type, there is no generate_execution_plan function

### ISSUE THREAD

**Issue by frr163** [explodinggradients/ragas#1644]
When I try to use my local llm to generate testset, there are some problems.

**Describe the bug**
In this file: ragas/src/ragas/testset/transforms/engine.py,
on line 104, the codes are:
![图片](https://github.com/user-attachments/assets/26e0b4ee-2182-46a0-94c2-21b07eb6ef2e)
but there is no generate_execution_plan function.(The existing generate_execution_plan function is for Parallel.)

Ragas version: 0.2.4
Python version: 3.8.19

**Comment by jjmachan** [comment]
@frr163 I'm not sure I understood the question but every transforms has an execution plan https://github.com/explodinggradients/ragas/blob/0415a2dd313f9991f9d41f8d78f55346a4a09235/src/ragas/testset/transforms/base.py#L76-L93

Prallel has a special one where it combines all the plans from the call and executes it together
