### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.core'

### ISSUE THREAD

**Issue by cirezd** [explodinggradients/ragas#1655]
[x ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
Using version 0.2.4 requires llama index as dependency

Ragas version: 0.2.4
Python version: 3.10.13

**Code to Reproduce**
Any sample code

**Error trace**
Traceback (most recent call last):
  File "/Users/markus/Code/xyz/evaluation/ragas_evaluation.py", line 4, in <module>
    from ragas.metrics import (
  File "/Users/markus/Code/xyz/.venv/lib/python3.10/site-packages/ragas/__init__.py", line 2, in <module>
    from ragas.evaluation import evaluate
  File "/Users/markus/Code/xyz/.venv/lib/python3.10/site-packages/ragas/evaluation.py", line 11, in <module>
    from llama_index.core.base.llms.base import BaseLLM as LlamaIndexLLM
ModuleNotFoundError: No module named 'llama_index.core'

**Expected behavior**
Llama index only as optional dependency

**Additional context**
Problem introduced in 0.2.4, 0.2.3 works without issues.

**Comment by sam-h-long** [comment]
Yes! Same problem - you can see in version 0.2.4 it forces you to install LLamaIndex before using evaluation.py

Version 0.2.4
https://github.com/explodinggradients/ragas/blob/v0.2.4/src/ragas/evaluation.py#L11

Version 0.2.3
https://github.com/explodinggradients/ragas/blob/v0.2.3/src/ragas/evaluation.py

**Comment by jjmachan** [comment]
hey @sam-h-long @cirezd  that was a bug on our end - this has been removed with v0.2.5

I'm closing this now but let me know if this is still a problem
