### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Dormiveglia-elf** [explodinggradients/ragas#1667]
ERROR:ragas.executor:Exception raised in Job[2]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[7]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[10]: TimeoutError()
ERROR:ragas.executor:Exception raised in Job[15]: TimeoutError()
....

I use GPT-4o and encountered many timeout error, any ideas?

**Comment by Dormiveglia-elf** [comment]
I have solved it by adjusting the max_workers and time_out parameter mentioned in [https://docs.ragas.io/en/stable/howtos/customizations/_run_config/?h=time](url)

**Comment by YuffieHuang** [comment]
> max_workers

Further reducing max_workers solved the same issue for me. I set it to be 8 for my locally hosted models.

**Comment by jjmachan** [comment]
hey anothe approach is `batch_size` argument for `evalaute()` https://docs.ragas.io/en/stable/references/evaluate/#ragas.evaluation.evaluate

something else you could try? easier to reason about IMO

**Comment by gtrigdon** [comment]
Hi, has anyone resolved the Ragas timeout errors? I've trying many configuration settings and still get them.
