### ISSUE TITLE
Bug in Testsetgeneration.ipynb

### ISSUE THREAD

**Issue by stepkurniawan** [explodinggradients/ragas#167]
Hi Devs, 

I found a bug in the notebook file. https://github.com/explodinggradients/ragas/blob/main/docs/Testsetgeneration.ipynb
When running this code: `from ragas.testset import TestsetGenerator`
there is an error because the `os.environ["OPENAI_API_KEY"] ="sk-xxx"` is set afterwards. 
It should be before we do import, and then it works. 

not sure where the fix should be done, in the TestsetGenerator, or in the notebook. 
Im a beginner in this. 
Thank you!

**Comment by shahules786** [comment]
Nice catch @stepkurniawan 
Resolved #165
