### ISSUE TITLE
How to set the ground_truth datatype correctly when creating a DatasetDict from scratch?

### ISSUE THREAD

**Issue by kpeters** [explodinggradients/ragas#172]
Hi,

After successfully trying the fiqa example, I'm now trying to get ragas to work on my own dataset. Below is a toy example I'm working on:

```
d = {
    'question': ['When was the first super bowl?', 'Who won the most super bowls?'],
    'answer': ['The first superbowl was held on January 15, 1967', 'The most super bowls have been won by The New England Patriots'],
    'ground_truths': ['The first superbowl was held on January 15, 1967', 'The New England Patriots have won the Super Bowl a record six times']
}
df = pd.DataFrame(data=d)

test = DatasetDict()
test['test'] = Dataset.from_list(
    mapping=df[["question", "answer", "ground_truths"]] \
                    .to_dict(orient='records'),
     # features={"ground_truths": Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)}
)
# test['test'] = test['test'].map(lambda example: {'ground_truths': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None)})

test_result = evaluate(
    test['test'],
    metrics=[answer_relevancy]
)
```

It works fine if I take out 'ground_truths' and just include the question and answer in Dataset.from_list(), but when I try to include the ground_truth I get an error about the datatype. I've tried setting the type with the 'features' argument in the Dataset call and afterwards with a map function but both didn't seem to work. Any tips or hints on how to set the datatype correctly?

Regards, Koen

**Comment by shahules786** [comment]
Hey @kpeters , thanks for raising the issue. `ground_truths` is a list of list. So if you change your dict to 
```python
d = {
    'question': ['When was the first super bowl?', 'Who won the most super bowls?'],
    'answer': ['The first superbowl was held on January 15, 1967', 'The most super bowls have been won by The New England Patriots'],
    'ground_truths': [['The first superbowl was held on January 15, 1967'], ['The New England Patriots have won the Super Bowl a record six times']]
}
df = pd.DataFrame(data=d)

````
it should work. 
The idea is that there can be multiple correct answers to a single question. Does that make sense?

**Comment by kpeters** [comment]
@shahules786, Thanks, that works indeed! I'm not used to the possibility of having multiple correct answers, but I'll take it for now.
