### ISSUE TITLE
Multi-lingual support for question generation and evaluation in Ragas v2

### ISSUE THREAD

**Issue by stilkin-pxl** [explodinggradients/ragas#1732]
**Describe the Feature**
A way to generate test sets (and run evaluations) in languages other than English.

**Why is the feature important for you?**
I do not live in an English-speaking country. 
The source material I am using is multi-lingual

**Additional context**
When using Ragas v1, there was an option to "_adapt_" the generator to different languages:

Example v1 code:
`generator.adapt('french', evolutions=[simple, reasoning, conditional, multi_context], cache_dir=cache_dir)`

I am not able to use this code in the new version of Ragas
(this generates the following error: `AttributeError: 'TestsetGenerator' object has no attribute 'adapt'`)

**Add any other context about the feature you want to share with us.**
When using non-English source material the resulting question-answer pairs are a mix between the source language and English. 

I also cannot seem to find how to do this in the v2 documentation. 
If there is no translation feature present, could it be possible to append something to the generation / evaluation prompt?

**Comment by shahules786** [comment]
Hey @stilkin-pxl We are working on this. Will try to ship it with this week's release it possible.  Meanwhile, we have shipped items that enables you to create custom single and multi hop queries, refer docs https://docs.ragas.io/en/latest/howtos/customizations/

**Comment by shahules786** [comment]
Hey @stilkin-pxl Just shipped it here https://github.com/explodinggradients/ragas/pull/1734

**Comment by shahules786** [comment]
Closing the issue with PR merged. Refer docs https://docs.ragas.io/en/stable/howtos/customizations/testgenerator/_language_adaptation/#intialize-required-models
