### ISSUE TITLE
Problem with Azure OpenAI endpoint.

### ISSUE THREAD

**Issue by zainif** [explodinggradients/ragas#174]
Very interesting framework! I am struggling right now to try it out though:
I followed your guidelines (https://github.com/explodinggradients/ragas/blob/main/docs/howtos/customisations/quickstart-azure-openai.ipynb) to be able to run evaluate() with my Azure OpenAI endpoint. However, I get the following error: 'InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.' .. even though my endpoint is up and running and works perfectly when I call it from my own code. There seems to be an issue with the langchain functionality AzureChatOpenAI of some kind. Any ideas, how I could resolve/debug this?

**Comment by buddhaha** [comment]
I managed to make it work with model `gpt-35-turbo`, as the deployment of `text-davinci-003` does not support `The chatCompletion operation`. Also, I have changed `deployment` to `deployment_name` in the `AzureChatOpenAI` definition:

```
azure_model = AzureChatOpenAI(
    deployment_name=os.getenv("OPENAI_LLM_DEPLOYMENT"),
    openai_api_base=os.getenv("OPENAI_API_BASE"),
    openai_api_type=os.getenv("OPENAI_API_TYPE"),
)
```

**Comment by jjmachan** [comment]
closing this since we also have an updated documentation site that documents this https://docs.ragas.io/en/latest/howtos/customisations/azure-openai.html

**Comment by zainif** [comment]
the change to deployment_name solved my issue. thanks!
