### ISSUE TITLE
 howtos:  comparing LLMs using ragas

### ISSUE THREAD

**Issue by shahules786** [explodinggradients/ragas#181]
The idea is to build a how-to notebook comparing two LLMs using ragas
- The work can be organized similar to https://docs.ragas.io/en/latest/howtos/applications/compare_embeddings.html
- The metrics to use here are `faithfulness` and `answer_relevancy`
- Some suggestions for models to compare [falcon](https://huggingface.co/tiiuae/falcon-7b-instruct) vs [zyphyr](https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha). You can use the free HF inference API for these models.

**Comment by rachittshah** [comment]
Hi @shahules786, I'd like to take this up

**Comment by jjmachan** [comment]
finished by @tinomaxthayil here https://docs.ragas.io/en/latest/howtos/applications/compare_llms.html

**Comment by swethag04** [comment]
When running this code for comparing LLMs, I am running into the TypeError. Any pointers ?

`# Use zephyr model using HFInference API
zephyr_llm = HuggingFaceInferenceAPI(
    model_name="HuggingFaceH4/zephyr-7b-alpha",
    token="*****" 
)
qe1 = build_qe(zephyr_llm)
result_ds = generate_responses(qe1, test_questions, test_answers)
result_zephyr = evaluate(result_ds, metrics=metrics )
`

Error:
TypeError: evaluate() missing 1 required positional argument: 'questions'

**Comment by tinomaxthayil** [comment]
Hi, can you verify if your result_ds is of the format:
Dataset({
    features: ['question', 'answer', 'contexts', 'ground_truths']
})

**Comment by swethag04** [comment]
Hi @tinomaxthayil , thanks for your reply. I figured I was using the wrong evaluate function. (`ragas.llama_index.evaluate` instead of `ragas.evaluate`. The code works fine now. 

Thanks for creating this super useful notebook.
