### ISSUE TITLE
Retrieval metrics : improvements 

### ISSUE THREAD

**Issue by shahules786** [explodinggradients/ragas#190]
- [ ] Add guardrails to metrics to check for the correct format.  Score NaN if returned otherwise
- [ ] Differentiate between context relevance and precision 
Relevance -> reference free ( can be used to optimize chunking/ ranking ) 
Precision -> works with ground truth

**Comment by marrvolo** [comment]
Hi @shahules786, thank you for these improvements, we were also a little bit confused by the different definition of context recall and precision, glad to know that it's going to be changed.
BTW, we have a question concerning the Relevance->reference free improments, what do you mean by reference free in this case?
Thanks for your response in advance.
