### ISSUE TITLE
Fix Documentation 

### ISSUE THREAD

**Issue by mmaysami** [explodinggradients/ragas#192]
I was going through docs and noticed a few typos. Sharing them here.

[Evaluation Document](https://github.com/explodinggradients/ragas/blob/main/docs/getstarted/evaluation.md?plain=1#L31-L34):
> question: list[str] - These are the questions you**r** RAG pipeline will be evaluated on.
> answer: list[str] - The answer generated from the RAG pipeline and give**n** to the user.
> contexts: list[list[str]] - The contexts which **were** passed into the LLM to answer the question.
> ground_truths: list[list[str]] - The ground truth answer to the questions. (only required if you are using context_recall)

**Comment by shahules786** [comment]
hey @mmaysami Nice catch. Would you like to raise a PR on this?
