### ISSUE TITLE
Clarification of answer relevancy

### ISSUE THREAD

**Issue by ogencoglu** [explodinggradients/ragas#196]
Is answer relevancy supposed to be used to compare "only prompt (only the question) and answers" or "prompt + retrieved context (full input to an LLM) and answers?

**Comment by shahules786** [comment]
@ogencoglu that's interesting. Although the initial idea was to enable compare <question, answer>  I am now thinking it should also consider <context> as in many instances that can be helpful in recreating the question back. I'm working on some improvements in answer_relevancy which I can include too. 

If you like to contribute to this, please let me know.
