### ISSUE TITLE
New metric: to quantify the RAG Improvement

### ISSUE THREAD

**Issue by wywdiablo** [explodinggradients/ragas#199]
It would be beneficial to have an evaluation metric that measures the improvement brought by the RAG. This metric should perform the following:

1. Calculate the distance between the RAG-generated answers and the ground truths.
2. Calculate the distance between the LLM stand-alone generated answers and the ground truths.
3. Determine the improvement based on the two distances mentioned above. The resulting score could range from [-1, 1], since the improvement could potentially be negative.

Inputs required:

1. Ground truths
2. LLM stand-alone generated answers
3. RAG generated answers

**Comment by shahules786** [comment]
Hey @wywdiablo , this is interesting. We worked on a similar idea during the paper but couldn't quantify the difference effectively.  How do you think this feature will help?

**Comment by wywdiablo** [comment]
I believe this metric will be important for certain use cases. For example, in one case we aim to enhance the answer by integrating the LLM's knowledge with a new external data source. A challenge arises when the RAG forms an answer based solely on the data we provided. If we offer a different prompt template in the RAG, such as, "You are a professor in the XXX domain," it seems only activate the LLM's inherent knowledge rather than drawing from the external data source. There should be a metric to inform the developer of this, allowing for better control.
