### ISSUE TITLE
Can you confirm if Vertex AI (Text Bison) is supported with Ragas?

### ISSUE THREAD

**Issue by AIAnytime** [explodinggradients/ragas#200]
Hi, thanks for this tool. Can you tell us when Ragas will support LLMs like Vertex AI models like Text-bison?

**Comment by jjmachan** [comment]
yep you can use Vertext AI models via langchains [Vertext AI modle](https://python.langchain.com/docs/integrations/llms/google_vertex_ai_palm).

```py
from langchain.llms import VertexAI
from ragas.llms import LangchainLLM

llm = LangchainLLM(VertextAI())
# now you can swap it out for other LLMs
```

to figure out how to customise Ragas llm check [this doc](https://docs.ragas.io/en/latest/howtos/customisations/llms.html)

**Comment by jjmachan** [comment]
feel free to reopen if you face any more problems

**Comment by simonprudhomme** [comment]
Hi, I am facing the same issue. 

This solution isn't working:
`from langchain.llms import VertexAI
from ragas.llms import LangchainLLM

llm = LangchainLLM(VertextAI())`
