### ISSUE TITLE
[Feature Request] Add support for LangChain Bedrock LLMs and embedding models

### ISSUE THREAD

**Issue by austinmw** [explodinggradients/ragas#211]
Could you please add support to pass in a different LLM and embedding model?

```python
import boto3
from botocore.config import Config
from langchain.chat_models import BedrockChat
from langchain.embeddings import BedrockEmbeddings

my_config = Config(retries={'max_attempts': 10, 'mode': 'standard'})
bedrock_inference = boto3.client(service_name='bedrock-runtime', config=my_config)

llm = BedrockChat(
    client=bedrock_inference,
    model_id="anthropic.claude-v2",
    model_kwargs={"temperature": 0.0},
)

embeddings = BedrockEmbeddings(
    client=bedrock_inference,
    model_id='amazon.titan-embed-text-v1',
)
```

**Comment by jjmachan** [comment]
hey @austinmw thanks for raising this issue - I will take a look at this and make a PR for adding the same. 
currently there is a bug in the way we are handling temperature so you can't use it out of the box

also thank you so much for taking the time to write out the code as well, that really helped a lot 🙂 
will get this out shortly

**Comment by andreibondarev** [comment]
@jjmachan Related question: I see that the temperature is hardcoded to `0`, for example [here](https://github.com/explodinggradients/ragas/blob/1dd363e3e54744e67b0be85962a0258d8121500a/src/ragas/llms/base.py#L54) and [here](https://github.com/explodinggradients/ragas/blob/1dd363e3e54744e67b0be85962a0258d8121500a/src/ragas/llms/llamaindex.py#L28), also in the [example](https://github.com/explodinggradients/ragas/blob/1dd363e3e54744e67b0be85962a0258d8121500a/docs/howtos/integrations/langchain.ipynb#L52). Is the temperature set to zero to bring some randomness in, for example, when generating Answer Relevance questions off of the same prompt?

**Comment by austinmw** [comment]
Hey @jjmachan , just curious what the status is on this? I noticed a v0.0.18 release with #189 that seems to provide some fixes, but I still get `OpenAIKeyNotFound` when I try:

```python
answer_rel_chain = RagasEvaluatorChain(metric=answer_relevancy)
```

Also if you need help testing Bedrock models I'm happy to help!
