### ISSUE TITLE
Getting sharply different values for results, using llama_index example under integrations

### ISSUE THREAD

**Issue by vishhvak** [explodinggradients/ragas#213]
Tried to run the llama_index example from integrations folder under docs - 

Got the following result:
`{'ragas_score': 0.0779, 'faithfulness': 0.9600, 'answer_relevancy': 0.8940, 'context_recall': 0.6800, 'context_precision': 0.0210, 'harmfulness': 0.0000}`

Which seems to be way off compared to the results in the notebook.
`{'ragas_score': 0.5142, 'faithfulness': 0.7000, 'answer_relevancy': 0.9550, 'context_precision': 0.2335, 'context_recall': 0.9800, 'harmfulness': 0.0000}`

For reference, I am using an Azure Open AI Instance, with GPT4 as my model. 

Is this normal/expected?

**Comment by shahules786** [comment]
Hey @vishhvak , thanks for asking. This is normal as we had updated metrics/datasets multiple times after the notebook had the last run. 
I think it would be nice to add a caution at the end of tutorial notebooks mentioning this as well. Let me know if you like to work on this :)
