### ISSUE TITLE
divide by zero encountered in divide

### ISSUE THREAD

**Issue by gdelpuente** [explodinggradients/ragas#217]
When it tries to calculate the "ragas_score" it does the harmonic mean on the metrics, if one of the metrics is equal to 0 by carrying out the calculation on evaluate:
"reciprocal_sum = np.sum(1.0 / np.array(values))" occurs: "RuntimeWarning: divide by zero encountered in divide"
therefore the ragas_score is set to 0.

**Comment by shahules786** [comment]
@gdelpuente , Nice catch! This can be solved by #218
