### ISSUE TITLE
"BedrockChat" object has no field "temperature" error when trying to use Bedrock

### ISSUE THREAD

**Issue by nmklong** [explodinggradients/ragas#220]
Hi, I have a test evaluation code below, but when I run it, it keeps throwing an error with trying to get `temperature` from the `BedrockChat` object (this class doesn't have `temperature` field). Am I doing anything wrong? Or can someone give me some directions?

```python
from langchain.chat_models import BedrockChat
from ragas.metrics import (
    context_precision,
    answer_relevancy,
    faithfulness,
    context_recall,
)
from ragas.metrics.critique import harmfulness
from datasets import load_dataset
from ragas import evaluate

chat = BedrockChat(
    model_id="anthropic.claude-instant-v1",
    model_kwargs={"temperature":0.0}
)

fiqa_eval = load_dataset("explodinggradients/fiqa", "ragas_eval")
faithfulness.llm.langchain_llm = chat
result = evaluate(
    fiqa_eval["baseline"].select(range(5)),  # showing only 5 for demonstration
    metrics=[faithfulness],
)
```

**Comment by jjmachan** [comment]
Hey @nmklong thanks for pointing this out, Bedrock is not supported at the moment but we will get that out by this weekend

**Comment by nmklong** [comment]
@jjmachan awesome to hear that, thank you!

**Comment by jjmachan** [comment]
thankfully #227 will fix this - will release this soon
