### ISSUE TITLE
TypeError: BaseChatModel.generate() missing 1 required positional argument: 'messages'

### ISSUE THREAD

**Issue by zjucsgk** [explodinggradients/ragas#222]
When I generate a test dataset using the code provided in the document, this error occurs.
The code:
### Add custom llms and embeddings
generator_llm = ChatOpenAI(model="gpt-3.5-turbo-16k")
critic_llm = ChatOpenAI(model="gpt-3.5-turbo-16k")
embeddings_model = OpenAIEmbeddings()

### Change resulting question type distribution
testset_distribution = {
    "simple": 0.25,
    "reasoning": 0.5,
    "multi_context": 0.0,
    "conditional": 0.25,
}

### percentage of conversational question
chat_qa = 0.5

test_generator = TestsetGenerator(
    generator_llm=generator_llm,
    critic_llm=critic_llm,
    embeddings_model=embeddings_model,
    testset_distribution=testset_distribution,
    chat_qa=chat_qa,
)

testset = test_generator.generate(documents, test_size=5)

The error detail：
File d:\ProgramData\Anaconda3\envs\xx\lib\site-packages\ragas\testset\testset_generator.py:179, in TestsetGenerator._filter_context(self, context)
    [177](file:///d%3A/ProgramData/Anaconda3/envs/seckb/lib/site-packages/ragas/testset/testset_generator.py?line=176) human_prompt = SCORE_CONTEXT.format(context=context)
    [178](file:///d%3A/ProgramData/Anaconda3/envs/seckb/lib/site-packages/ragas/testset/testset_generator.py?line=177) prompt = ChatPromptTemplate.from_messages([human_prompt])
--> [179](file:///d%3A/ProgramData/Anaconda3/envs/seckb/lib/site-packages/ragas/testset/testset_generator.py?line=178) results = self.critic_llm.generate(prompts=[prompt])
    [180](file:///d%3A/ProgramData/Anaconda3/envs/seckb/lib/site-packages/ragas/testset/testset_generator.py?line=179) output = results.generations[0][0].text.strip()
    [181](file:///d%3A/ProgramData/Anaconda3/envs/seckb/lib/site-packages/ragas/testset/testset_generator.py?line=180) score = load_as_score(output)

TypeError: BaseChatModel.generate() missing 1 required positional argument: 'messages'

**Comment by zjucsgk** [comment]
Who can help me solve this problem?

**Comment by shahules786** [comment]
Hi @zjucsgk ,apologies for late reply. Can you help us with the ragas & python version you're using?

**Comment by jjmachan** [comment]
applogies from my side for the delay, this is probably because your passing a Langchain LLM where a `RagasLLM` is expected.

how you should call is like 
```python
from langchain.chat_models import ChatOpenAI
from ragas.llms import LangchainLLM

generator_llm = LangchainLLM(llm=ChatOpenAI(model=openai_generator_llm))
critic_llm = LangchainLLM(llm=ChatOpenAI(model=openai_filter_llm))
embeddings_model = OpenAIEmbeddings()  # type: ignore
```

**Comment by zjucsgk** [comment]
> Hi @zjucsgk ,apologies for late reply. Can you help us with the ragas & python version you're using?
@shahules786 Thanks
Python 3.10.13
ragas-0.0.18

**Comment by zjucsgk** [comment]
@jjmachan OK，its fixed. Thank you
