### ISSUE TITLE
Have noticed ragas needs cohere and llama_index libraries to be installed before importing ragas

### ISSUE THREAD

**Issue by GautamR-Samagra** [explodinggradients/ragas#223]
Not a bug as such :)
I was trying to run this on Google collab and noticed it requires me to install cohere and llama_index before installing ragas for being able to import ragas successfully.  

```
!pip install cohere 
!pip install llama_index
!pip install ragas 

from ragas import evaluate
``` 

Also have noticed its necessary  to set up the openai key before I import ragas, cannot set it after I import ragas

**Comment by jjmachan** [comment]
thanks for bringing this up @GautamR-Samagra  I've created #231 to track another problem with dependencies and will close this one with that too

Cheers and welcome to the community :)
