### ISSUE TITLE
[Feature Request] extract single question scores

### ISSUE THREAD

**Issue by gdelpuente** [explodinggradients/ragas#224]
Give the possibility to extract from the result also the single question evaluation.

**Comment by shahules786** [comment]
Hi @gdelpuente , thanks for raising the FR. can you explain this a bit more?

**Comment by gdelpuente** [comment]
when I use the evaluation on a pool of questions the result is one for all for each metric (the average).
I would also like to read the result of the single query

ex:

{
question1 : {context_precision:0,653 ; faithfulness:0,376 ; answer_relevancy....} 
question2:  {context_precision:0,253 ; faithfulness:0,721 ; answer_relevancy...} 
...
final_result: {context_precision:0,876 ; faithfulness:0,345 ; answer_relevancy...} 
}

**Comment by shahules786** [comment]
Hey, have you tried to do `results.to_pandas()` to get sample-level scores?

**Comment by jjmachan** [comment]
hey ask @shahules786 suggested converting it into the dataframe will help you with this. Each row will correspond in the dataframe will currespond to one query and you can do further analysis with just pandas. Do try it out @gdelpuente and tell us if that is what your looking for :)

**Comment by gdelpuente** [comment]
currently I call evaluate on the individual question and then perform the mean and harmonic mean outside the framework to obtain the summary results.

But the _evaluate_ function internally already does this only that at the end of the cycle it does not display the results calculated for the individual questions.

It could have been an additional feature, also to remain aligned in the formalization of the summary results, to be able to recover the calculated results of the individual questions directly from the framework function

**Comment by shahules786** [comment]
@gdelpuente , understood.  Although you don't have to evaluate the individual questions separately. You can run the entire batch and export results to pandas as mentioned above. Then you can do any operation on the dataframe level.

**Comment by jjmachan** [comment]
but if you want there is a `score_single()` class for each metric that you can use. Its not documented because we might be changing it but you can check the `metrics/base.py` file for more info

**Comment by omri374** [comment]
I have the same issue, of integrating the ragas metrics into an existing evaluation pipeline which already does other types of evaluation, and I'd like to run it the same way. Thanks for suggesting `score_single()`.
