### ISSUE TITLE
[Feature Request] use evaluate without ground_truths

### ISSUE THREAD

**Issue by gdelpuente** [explodinggradients/ragas#225]
allow the evaluate function to work without "ground_truths" by providing the other available measures

**Comment by shahules786** [comment]
Hi @gdelpuente , thanks for asking. This is possible with ragas (metrics such as faithfulness), please update to the latest version.

**Comment by jjmachan** [comment]
also @gdelpuente just curious what aspects are you trying to evaluate?

**Comment by gdelpuente** [comment]
when you do something like
```python
from ragas import evaluate
from datasets import Dataset
import os

os.environ["OPENAI_API_KEY"] = "your-openai-key"
``` 
 prepare your dataset in the format **without ground_truths**
```python
# Dataset({
#     features: ['question', 'contexts', 'answer'],
#     num_rows: 25
# })

dataset: Dataset

results = evaluate(dataset)
# ERROR
``` 

the function return an error because it try to evaluate also the _context_recall_
it might be friendly to use if it evaluated what measures it can calculate from the input it receives

I know you can select metrics as parameter
mine was just a suggestion for improvement
also given that the project's starting paper focuses on measurements without ground_truths

**Comment by jjmachan** [comment]
understood, thank you for the valuable suggestion. Will fix this shortly 🙂
