### ISSUE TITLE
make heavy  dependencies optional

### ISSUE THREAD

**Issue by jjmachan** [explodinggradients/ragas#231]
currently we have a few heavy dependencies like sentence-transformer and torch, we can reduce this for smaller installables

**Comment by shahules786** [comment]
This will require

- [ ] Removing strictness &[ sentence agreements](https://github.com/explodinggradients/ragas/blob/1b2c79b58c632bbb407a72b3f0a376503b8a17ae/src/ragas/metrics/context_precision.py#L49) from context relevancy
- [ ] Adding bi-encoder methods in [answer similarity  ](https://github.com/explodinggradients/ragas/blob/1b2c79b58c632bbb407a72b3f0a376503b8a17ae/src/ragas/metrics/answer_similarity.py#L45)

**Comment by sid8491** [comment]
currently size of library is very big, removing these dependencies will make it more usable.

**Comment by jjmachan** [comment]
fixed now
