### ISSUE TITLE
dynamically check which LLM class is it and if its langchain and not wrapped, just wrap it ourselves

### ISSUE THREAD

**Issue by austinmw** [explodinggradients/ragas#239]
Hey, I noticed that `langchain.llms.OpenAI.generate()` and `langchain.llms.Bedrock.generate()` are supposed to take `prompt: List[str]` instead of `List[ChatPromptTemplate]` that is currently being passed. 

Although the OpenAI class doesn't seem to error with the wrong input type, the Bedrock class does. It errors at `langchain.llms.bedrock._human_assistant_format()`.

Similarly, `langchain.chat_models.BedrockChat.generate()` `messages` argument should take type `List[List[BaseMessage]]` instead of `ChatPromptTemplate`.  This causes an error in `langchain.chat_models.anthropic. _convert_one_message_to_text`.

Thanks again!

**Comment by austinmw** [comment]
Actually, this might be me just forgetting to wrap the LLM in `LangchainLLM` 😅

**Comment by jjmachan** [comment]
yeah that is mostly the reason although we are trying to to figure out how to avoid that gotcha 😅 
if you have any suggestion please do let us know - about how we can make it much more easier for users to use this the correct way.

On option I had in mind was to dynamically check which LLM class is it and if its langchain and not wrapped, just wrap it ourselves. should avoid the gotchas here
