### ISSUE TITLE
Non-deterministic scores

### ISSUE THREAD

**Issue by austinmw** [explodinggradients/ragas#240]
Hey, apologies for creating multiple issue threads so rapidly, but I like this library and hope it gains more traction!

Some metrics are giving different results each time they are ran even with temperature set to 0. For example, Faithfulness and AnswerCorrectness.

I believe this might be due to using LangChain `ChatOpenAI` instead of `OpenAI`, where the latter appears more deterministic with temperature set to 0, but I'm not positive about this.

**Comment by ihgumilar** [comment]
I got the same issue as well, every time I run the evaluation, it will give slight or significant different scores for each question sometime. Any advice @shahules786  ?

**Comment by austinmw** [comment]
I guess the new seed feature would be helpful here

**Comment by shahules786** [comment]
Hi @austinmw @ihgumilar , thanks for sharing your thoughts & concerns. The scores can vary due to the non-deterministic nature of LLMs, I have seen this happening more with closed-sourced services. The new `seed` feature from OpenAI might be useful, but I have yet to experiment with it. But I would want something more generalization beyond OpenAI.  

Self-consistency checks can be a good way to improve reproducibility.

**Comment by jgege** [comment]
I'm experiencing the same issue. I looked into this and in my case it seems that the passed temperature value is not respected, it's either set to 0.2 or 1e-8.
https://github.com/explodinggradients/ragas/blob/v0.0.22/src/ragas/llms/langchain.py#L200

1e-8 is very close to 0 but not zero. Is this a bug or an intended feature?

Also there seems to be a lack of consistency between the async and non-async implementation as for async it's always set to 0:
https://github.com/explodinggradients/ragas/blob/v0.0.22/src/ragas/llms/langchain.py#L146

**Comment by tranhoangnguyen03** [comment]
I'm also experiencing score fluctuations between runs. Is the seed feature implemented yet?

**Comment by simon19891101** [comment]
@shahules786 FYI I fixed the seed but it didn't work...
