### ISSUE TITLE
docs: examples with Amazon Bedrock

### ISSUE THREAD

**Issue by arm-diaz** [explodinggradients/ragas#241]
Add documentation and examples of ragas with Amazon Bedrock. Please assign this issue to me.

**Comment by shahules786** [comment]
Hey @arm-diaz , thank you. This will go under [customisation](https://docs.ragas.io/en/latest/howtos/customisations/index.html).

**Comment by austinmw** [comment]
Hi, is this currently using `BedrockChat.generate()`? If so I think it should be faster with `BedrockChat.batch()`

**Comment by jjmachan** [comment]
hey I'm closing this because we have the docs now at https://docs.ragas.io/en/latest/howtos/customisations/aws-bedrock.html.

feel free to reopen or comment below if there is more to be done :)
