### ISSUE TITLE
Get metrics evaluation logs

### ISSUE THREAD

**Issue by grauvictor** [explodinggradients/ragas#250]
For evaluation monitoring and understanding, it would be great to have the logs of the evaluation process, in particular the llm's responses to produce the final score

For example, for the faithfulness, retrieve the response to LONG_FORM_ANSWER_PROMPT and NLI_STATEMENTS_MESSAGE. 

Possible solutions:
- return another value (a dict, or an object) in addition to the scores with answer logs
- create a class property for each metric, for example `score_logs` updated during evaluation process, and from which we can retrieve logs

**Comment by jjmachan** [comment]
I think the following should help with this
1. ironing out the callback bugs
2. documentation on how to log ragas itself effectively

I will be working on both of these shortly but I see you also have a PR ready.
