### ISSUE TITLE
reformat:  Add pydantic for better error handling and debugging

### ISSUE THREAD

**Issue by arm-diaz** [explodinggradients/ragas#253]
Pydantic is a library that provides data validation and settings management using type annotations.

[Official documentation:](https://docs.pydantic.dev/latest/)

#Why use Pydantic?

- Powered by type hints — with Pydantic, schema validation and serialization are controlled by type annotations; less to learn, less code to write, and integration with your IDE and static analysis tools. 
- Speed — Pydantic's core validation logic is written in Rust. As a result, Pydantic is among the fastest data validation libraries for Python. 
- JSON Schema — Pydantic models can emit JSON Schema, allowing for easy integration with other tools. Learn more…
- Strict and Lax mode — Pydantic can run in either strict=True mode (where data is not converted) or strict=False mode where Pydantic tries to coerce data to the correct type where appropriate.
- Dataclasses, TypedDicts and more — Pydantic supports validation of many standard library types including dataclass and TypedDict
- Customisation — Pydantic allows custom validators and serializers to alter how data is processed in many powerful ways.
- Ecosystem — around 8,000 packages on PyPI use Pydantic, including massively popular libraries like FastAPI, huggingface, Django Ninja, SQLModel, & LangChain. 
- Battle tested — Pydantic is downloaded over 70M times/month and is used by all FAANG companies and 20 of the 25 largest companies on NASDAQ. If you're trying to do something with Pydantic, someone else has probably already done it.

Pydantic can provide better error handling and more visibility of classes, methods, and dependencies across the project.

**Comment by jjmachan** [comment]
would you give a few examples of how pydantic would help with error handling and debugging with respect to ragas.

if it is for LLM output parsing I agree. We are working out json for this since models are more likely to understand json errors than pydantic
