### ISSUE TITLE
Importing LangchainLLM from ragas.llms throws validation error

### ISSUE THREAD

**Issue by Sckarge** [explodinggradients/ragas#266]
This is what I was running

```
from langchain.chat_models import AzureChatOpenAI
from langchain.embeddings import OpenAIEmbeddings
from ragas.llms import LangchainLLM
```

Python==3.10.12
ragas==0.0.12

<img width="1316" alt="Screenshot 2023-11-08 at 4 38 47 PM" src="https://github.com/explodinggradients/ragas/assets/97539993/850fbe57-dcc0-4ba1-aa0a-1ec8f428ee7b">

**Comment by jjmachan** [comment]
this should be fixed with the latest release. feel free to reopen if this is still an issue :)
