### ISSUE TITLE
Set versions of each dependency - new versions of llama-index breaks ragas

### ISSUE THREAD

**Issue by patelisii** [explodinggradients/ragas#270]
**Describe the bug**
Installing ragas and installing the newest version of llama index breaks ragas - please add the correct versions of each dependency in the requirements

Ragas version: 0.0.18
Python version: 3.8

**Comment by ceferisbarov** [comment]
This is a problem with older versions of langchain, too.

**Comment by jjmachan** [comment]
this was fixed but I'll confirm this again before closing this
