### ISSUE TITLE
Synthetic test data generation, but result was enpty

### ISSUE THREAD

**Issue by Gaia-Wu** [explodinggradients/ragas#272]
I' m tring to do "Synthetic test data generation", but But the result was empty. Can you help me solve this problem?

**Code:**
from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader("/home/data/_pdf/test_1.pdf")
documents_0 = loader.load()

from ragas.testset import TestsetGenerator

testsetgenerator = TestsetGenerator.from_default()
test_size = 12
testset = testsetgenerator.generate(documents_0, test_size=test_size)

**result:**
[/Users/opt/anaconda3/envs/py311_langchain/lib/python3.11/site-packages/ragas/testset/testset_generator.py:316](https://file+.vscode-resource.vscode-cdn.net/Users/wukaiyan/opt/anaconda3/envs/py311_langchain/lib/python3.11/site-packages/ragas/testset/testset_generator.py:316): UserWarning: Most documents are too short
  warnings.warn("Most documents are too short")
  0%|          | 0/2 [00:02<?, ?it/s]

TestDataset(test_data=[])

**Comment by shahules786** [comment]
Hi @Gaia-Wu , can you share the ragas version?

**Comment by Gaia-Wu** [comment]
@shahules786 

Name: ragas
Version: 0.0.19

**Comment by shahules786** [comment]
From the warning here 
`serWarning: Most documents are too short
warnings.warn("Most documents are too short")`
most documents seem to be too short for going through QA evolution process. This might have caused. I would suggest to pass larger chunks and/or modify test distribution to `{'simple':1.0}`

**Comment by Gaia-Wu** [comment]
> From the warning here `serWarning: Most documents are too short warnings.warn("Most documents are too short")` most documents seem to be too short for going through QA evolution process. This might have caused. I would suggest to pass larger chunks and/or modify test distribution to `{'simple':1.0}`

@shahules786  Thanks for your guidance. I have solved this problem.
