### ISSUE TITLE
Context (Average) Precision and LongContextReorder

### ISSUE THREAD

**Issue by austinmw** [explodinggradients/ragas#274]
Hi, I noticed something interesting that I thought might be worth mentioning. 

There's been some attention around the paper "[Lost in the Middle: How Language Models Use Long Contexts](https://arxiv.org/abs/2307.03172)"

LangChain has introduced a [LongContextReorder](https://python.langchain.com/docs/modules/data_connection/document_transformers/post_retrieval/long_context_reorder) class, which basically reorders the retrieved documents so that the least relevant documents are in the middle instead of at the end of the document list. The claim is that having the most relevant documents at the beginning and end is actually better for the LLM than to rank them in true ascending order.

The side effect of course is that `LongContextReorder` should have the unfortunate effect of lowering the Average Precision calculation.

I just thought I'd make a note of that in case anyone else came across this.

**Comment by shahules786** [comment]
Hey @austinmw , thank you for sharing this. I had similar thoughts after going through the paper. This is one of the reasons why I added the new [context_precicion](https://docs.ragas.io/en/latest/concepts/metrics/context_precision.html) metric which is rank-sensitive precision, Would love to know your thoughts on it. Here's a [reference](https://amitness.com/2020/08/information-retrieval-evaluation/)

Regarding finding in "lost in the middle" paper, I believe this behavior of the particular LLM is due the nature of finetuning data ( which makes LLM attention scores ignore tokens in the middle).  In my research & understanding it is always best to have relevant chunks at the top. 

I appreciate your genuine interest in our project, I would love to have a chat with you on this and possible contribution opportunities. Here's my [calendly](https://calendly.com/shahules/30min).

**Comment by austinmw** [comment]
Scheduled, looking forward to talking!
