### ISSUE TITLE
Evaluation fails with openai version 1.2.3

### ISSUE THREAD

**Issue by DanLeininger** [explodinggradients/ragas#280]
Evaluating metrics throws the following error with openai==1.2.3

```
File ".../python3.10/site-packages/langchain/chat_models/openai.py", line 73, in _create_retry_decorator
    openai.error.Timeout,
AttributeError: module 'openai' has no attribute 'error'
```

Fixed by rolling back to openai==0.28.1

Relevant langchain issue:
https://github.com/langchain-ai/langchain/issues/12967

Ragas version: 0.0.19
Python version: 3

**Comment by vishwasg217** [comment]
I'm also facing the same issue. Any fix to this?

**Comment by zhzfight** [comment]
hi, dude, the same problem. my ragas version is 0.21, the error message suggest me rolling back to open==0.28, however the question still remain. it tell me that ragas 0.021 require openai>1. anyone can help?

**Comment by jjmachan** [comment]
should be fixed with the latest release. will make a final check before closing this
