### ISSUE TITLE
Latest dependency versions for getting open source LLMs to work

### ISSUE THREAD

**Issue by jenghub** [explodinggradients/ragas#287]
Can someone please list which versions of openai, llama index, etc are currently required to get the documentation examples to work properly with open source LLMs? I've tried ragas evaluation and testsetgenerator with TGI and vLLM endpoints and run into missing dependencies. Having a tough time nailing down which ones currently work. The latest `llama-index` dependency throws `ModuleNotFoundError: No module named llama_index.node_parser.simple` when trying to run TestSetGenerator. I've rolled openai back to `openai==0.28.1` but this throws `ImportError: cannot import name 'AsyncAzureOpenAI' from 'openai`. Thanks!

**Comment by tinomaxthayil** [comment]
Hi jenghub,

This is an issue with the latest version of llama_index. You can use llama-index==0.8.69.post1 to resolve this issue. Note: if you installing ragas first it will install the llama_index with latest version. 
pip install llama-index==0.8.69.post1
pip install ragas
This order helped me resolve the issue.

**Comment by jenghub** [comment]
@tinomaxthayil thank you, this seems to work for now! Although hitting other errors with evaluation and testsetgenerator which has been raised in other issues. Cheers!
