### ISSUE TITLE
Answer relevancy always returns 1

### ISSUE THREAD

**Issue by ferdinandl007** [explodinggradients/ragas#292]
**Describe the bug**
The Answer Relevancy Score calculation is malfunctioning when used with embedding models such as OpenAI or Vertex Gecko. Regardless of the actual similarity between answers, the score is consistently outputting a value of '1'. This issue has been observed since the latest software release and was not present in the earlier version (ragas==0.0.19).
Python version:
pyhton3.9

**Comment by younes-io** [comment]
I have this:

```python
eval_questions = [
    "Can I work remotely?",
]

eval_answers = [
    "You must eat home-made pasta!",
]

examples = [
    {"query": q, "ground_truths": [eval_answers[i]]}
    for i, q in enumerate(eval_questions)
]

eval_result = faithfulness_chain(result)
eval_result["faithfulness_score"]
```


This logs `1.0`.. I don't understand.. am I missing something ?

**Comment by shahules786** [comment]
Hey @younes-io , Please pass a context along with your question if you are trying to measure faithfulness. Checkout our quickstart.

**Comment by shahules786** [comment]
Hey @ferdinandl007 , Answer_relevancy needs some rework, I'll be on it this weekend :)

**Comment by younes-io** [comment]
@shahules786 : 
I went through the quickstart, but in my real use case, I'm using LangChain with AzureOpenAI.
When I looked at the faithfuless calculation / algo, it loops over the source_documents, which I have in my `result`:

```python
print("result[source_documents] : ",len(result["source_documents"]))
eval_result = faithfulness_chain(result)
print("faithfulness_score: ",eval_result["faithfulness_score"])
```

The result is:

```
result[source_documents] :  4
faithfulness_score:  1.0
```

I also added a print log in the Ragas code in `evalchain.py` and the `contexts` object exists very well `length contexts : 1`


Then, I did this:

```python
from langchain.docstore.document import Document
text = """Records of people adding other ingredients to bread to make it more flavorful can be found throughout ancient history. In the 6th century BC, the Persian soldiers of the Achaemenid Empire during the rule of Darius the Great baked flatbreads with cheese and dates on top of their battle shields[23][24] and the ancient Greeks supplemented their bread with oils, herbs, and cheese.[25][26] An early reference to a pizza-like food occurs in the Aeneid, when Celaeno, queen of the Harpies, foretells that the Trojans would not find peace until they are forced by hunger to eat their tables (Book III). In Book VII, Aeneas and his men are served a meal that includes round cakes (like pita bread) topped with cooked vegetables. When they eat the bread, they realize that these are the "tables" prophesied by Celaeno.[27] In 2023, archeologists discovered a fresco in Pompeii appearing to depict a pizza-like dish among other foodstuffs and staples on a silver platter. Italy's culture minister said it "may be a distant ancestor of the modern dish".[28][29] The first mention of the word "pizza" comes from a notarial document written in Latin and dating to May 997 AD from Gaeta, demanding a payment of "twelve pizzas, a pork shoulder, and a pork kidney on Christmas Day, and 12 pizzas and a couple of chickens on Easter Day."[30]"""

doc = Document(page_content=text)


fake_result = result.copy()
fake_result["source_documents"] = [doc]

eval_result = faithfulness_chain(fake_result)
eval_result["faithfulness_score"]
```


And I got this:

```
[debug-to-be-removed] length contexts:  1
0.0
```

**My conclusion**: the example in the documentation for "faithfuless" calculation is wrong / misleading. In other words, the example [here](https://docs.ragas.io/en/latest/howtos/integrations/langchain.html#introducing-ragasevaluatorchain):

```python
fake_result = result.copy()
fake_result["result"] = "we are the champions"
eval_result = faithfulness_chain(fake_result)
eval_result["faithfulness_score"]
```


I think it should be:

```python
from langchain.docstore.document import Document
fake_result = result.copy()
fake_result["result"] = Document(page_content="we are the champions") 
eval_result = faithfulness_chain(fake_result)
eval_result["faithfulness_score"]
```

**Comment by younes-io** [comment]
> Hey @younes-io , Please pass a context along with your question if you are trying to measure faithfulness. Checkout our quickstart.

Please take a look at my comment and let me know if I got something wrong.. I'm a bit confused

**Comment by younes-io** [comment]
I also realize that sometimes Ragas expects the answer to be in the key "answer" and sometimes "result".. could you please clarify ?

**Comment by younes-io** [comment]
@shahules786 I already, I will open a separate issue if required.. I realized I was "polluting" this issue x) sorry @ferdinandl007

**Comment by shahules786** [comment]
Hey @younes-io , I would be happy to look at if you can open a PR :) Thank you.
