### ISSUE TITLE
Broken link in the documentation

### ISSUE THREAD

**Issue by younes-io** [explodinggradients/ragas#293]
**Describe the bug**
The link referred to in [this section](https://docs.ragas.io/en/latest/howtos/integrations/langchain.html#introducing-ragasevaluatorchain) is broken:

RagasEvaluatorChain creates a wrapper around the metrics ragas provides (documented **[here]**(https://github.com/explodinggradients/ragas/blob/main/docs/metrics.md)), making it easier to run these evaluation with langchain and langsmith.

**Expected behavior**
Just update the link with the correct URL

**Comment by shahules786** [comment]
Hey @younes-io , Nice catch. Would you like to contribute?

**Comment by younes-io** [comment]
@shahules786 Sure
