### ISSUE TITLE
OpenAI API key not found

### ISSUE THREAD

**Issue by amittos** [explodinggradients/ragas#303]
**Describe the bug**

I have set up my OpenAI API key as follows: 

`os.environ["OPENAI_API_KEY"] = 'my key'`

This is how it is described in the main page of the project and this is how I do with langchain and works as expected. 

However, I get the follower error: 

```
raise OpenAIKeyNotFound
ragas.exceptions.OpenAIKeyNotFound: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable
```

Ragas version: 0.0.20
Python version: 3.10

Why is this happening? How can I fix it? 

Many thanks for creating this library and sharing it with us!

**Comment by R-beep-AI** [comment]
Hi Always Same Issue

**Comment by R-beep-AI** [comment]
@ceferisbarov Thx that works for me.

**Comment by jjmachan** [comment]
yep @ceferisbarov is right and that was a bug but has been fixed with the latest release.

please do reopen if this is still a problem

**Comment by yasergsi** [comment]
I'm facing the same issue here with the latest RAGAS version i.e. `0.0.21`
Moving the RAGAS imports after setting the OpenAI API keys solved the issue for me.

**Comment by jiangxinke** [comment]
thanks, I change my code to: 

```
import os
os.environ["OPENAI_API_KEY"] = "xxxx"

from datasets import Dataset
from ragas import evaluate

```

than's work. 

Remember to set openai key before you import rages
