### ISSUE TITLE
import error:  from ragas.llms import LangchainLLM

### ISSUE THREAD

**Issue by Manikanta5112** [explodinggradients/ragas#310]
**Describe the bug**
Tried to import from ragas.llms import LangchainLLM.
Getting error: ImportError: cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings'

Ragas version: 0.0.20
Python version: 3.11.4

**Code to Reproduce**
from ragas.llms import LangchainLLM

**Error trace**
ImportError: cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings'

**Expected behavior**
AzureOpenAIEmbeddings import without any errors

**Comment by Manikanta5112** [comment]
Yes, I tried still. Getting the error ModuleNotFoundError: No module named 'langchain.embeddings.azure_openai'

**Comment by younes-io** [comment]
you should check your langchain version and compare with the langchain docs / reference

**Comment by Manikanta5112** [comment]
Thanks, after updating langchain version, issue got resolved

**Comment by lqcStar** [comment]
How do you update it, I update it by"pip install --upgrade langchain",but still " cannot import name 'LangchainLLMWrapper' from 'ragas.llms.base' "
