### ISSUE TITLE
AttributeError: 'Bedrock' object has no attribute 'validate_api_key' (ragas-0.0.21)

### ISSUE THREAD

**Issue by mabdul2** [explodinggradients/ragas#323]
https://github.com/explodinggradients/ragas/blob/3d29c44825eff39775f458af7c2e5d51411ac277/src/ragas/metrics/base.py#L121

```
import boto3
from langchain.llms import Bedrock
# from langchain.chat_models import BedrockChat # Same error using chat model


def get_claude_v2_llm(credentials_profile_name="default"):
    return Bedrock(
    credentials_profile_name=credentials_profile_name,
    # client=bedrock_runtime_client,
    model_id="anthropic.claude-v2",
    model_kwargs={
        "max_tokens_to_sample": 5000,
        "temperature": 0.0,
        "top_k": 250,
    }
)

claude_v2_llm = get_claude_v2_llm(credentials_profile_name="default")



for m in metrics:
    m.__setattr__("llm", claude_v2_llm)


from ragas import evaluate
import nest_asyncio  # CHECK NOTES

result = evaluate(
    fiqa_eval["baseline"],
    metrics=metrics,
)

result
```

**Comment by mabdul2** [comment]
ERROR:
    115 def init_model(self):
    116     """
    117     Init any models in the metric, this is invoked before evaluate()
    118     to load all the models
    119     Also check if the api key is valid for OpenAI and AzureOpenAI
    120     """
--> 121     self.llm.validate_api_key()
    122     if hasattr(self, "embeddings"):
    123         # since we are using Langchain Embeddings directly, we need to check this
    124         if hasattr(self.embeddings, "validate_api_key"):

AttributeError: 'Bedrock' object has no attribute 'validate_api_key'

**Comment by donatoaz** [comment]
I am also interested in using ragas with Bedrock.

**Comment by mabdul2** [comment]
This fixed it:
```
from ragas.llms import LangchainLLM
ragas_bedrock_model = LangchainLLM(claude_v2_llm)
```
