### ISSUE TITLE
TestsetGenerator silently ignoring test cases

### ISSUE THREAD

**Issue by ceferisbarov** [explodinggradients/ragas#324]
**Describe the bug**
`TestsetGenerator.generate` method takes `test_size` as an argument, but it usually returns less test cases than this number. I understand test cases that do not meet certain requirements are removed, but I had to search through the source code for some time before discovering that. In a similar fashion, `to_pandas` method removes test cases where question is an empty string, but again, no warnings.

Ragas version: 0.0.21.dev8+g13465f0
Python version: 3.10.12

**Code to Reproduce**
```
import argparse

from ragas.testset import TestsetGenerator
from langchain.document_loaders import TextLoader, DirectoryLoader

from config import OPENAI_API_KEY, LLAMA_URL, BGE_URL
from src.llms import LLaMA, BGE, OpenAILLM

parser = argparse.ArgumentParser()
parser.add_argument("--file", help="File path to be loaded. Mutually exclusive with folder argument.")
parser.add_argument("--folder", help="Folder path to be loaded. Mutually exclusive with folder argument.")
parser.add_argument("--outdir", help="Output directory to save to.")
parser.add_argument("--count", help="Number of test cases to be generate.")
args = parser.parse_args()

if args.file:
    loader = TextLoader(args.file)
elif args.folder:
    loader = DirectoryLoader(args.folder)
else:
    raise ValueError("Specify file or folder input by using one of the --file or --folder flags.")
    
documents = loader.load()

llama = LLaMA(url=LLAMA_URL)
openai = OpenAILLM(api_key=OPENAI_API_KEY)
bge = BGE(base_url=BGE_URL)

testsetgenerator = TestsetGenerator(generator_llm=openai, critic_llm=openai, embeddings_model=bge)

print(int(args.count))
testset = testsetgenerator.generate(documents, test_size=int(args.count))

df = testset.to_pandas()
print(df.shape)
df.to_csv(args.outdir)
```

**Expected behavior**
I think it is necessary to either add a warning or make these filters optional.

**Comment by ceferisbarov** [comment]
I can create a PR if you have an idea about how to approach this @jjmachan @shahules786

**Comment by shahules786** [comment]
Hi @ceferisbarov , thanks for raising this issue. We are aware of this issue, this will be solved in the next release of test generation.

**Comment by c-yeh** [comment]
@shahules786 it this meant to have been solved? Because I'm still experience the same.
Requested for `test_size=500`, got 498.
Requested for `test_size=1000`, got 998.

Ragas version: `0.1.2.dev8+gc18c7f4`
Python version: 3.9.13

**Comment by shahules786** [comment]
@c-yeh Oh, I think your issue is due to the distribution of question types. Will raise a fix for it.
