### ISSUE TITLE
Outdated Documentations for Azure-Openai Customization ?

### ISSUE THREAD

**Issue by rommik-nuvalence** [explodinggradients/ragas#326]
**Describe the bug**
In https://docs.ragas.io/en/latest/howtos/customisations/azure-openai.html the section says

```
# init and change the embeddings
# only for answer_relevancy
azure_embeddings = OpenAIEmbeddings(
    deployment="your-embeddings-deployment-name",
    model="your-embeddings-model-name",
    openai_api_base="https://your-endpoint.openai.azure.com/",
    openai_api_type="azure",
)
```
 However, the code would raise this exception on the `answer_relevancy` step

```
NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
```

changing `OpenAIEmbeddings` to `AzureOpenAIEmbeddings` resolved the problem

**Comment by ajinkyavbhandare** [comment]
Can I work on this?

**Comment by shahules786** [comment]
Thanks a lot @ajinkyavbhandare

**Comment by rommik-nuvalence** [comment]
The fix is wrong because the parameters for `AzureOpenAIEmbeddings` are not the same as for `OpenAIEmbeddings`
