### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower' while using evaluation (from ragas import evaluate).

### ISSUE THREAD

**Issue by debanshu005** [explodinggradients/ragas#352]
I'm getting the below error while using evaluate from ragas (from ragas import evaluate).
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by jjmachan** [comment]
thanks to @yuukidach this has been significantly improved. Please feel free to reraise this if you encounter this again @debanshu005
