### ISSUE TITLE
the trace_as_chain_group context do not contain the code

### ISSUE THREAD

**Issue by lucasiscovici** [explodinggradients/ragas#363]
https://github.com/explodinggradients/ragas/blame/68c7ed67da25c93172f093912646ba6a845a595c/src/ragas/metrics/_answer_correctness.py#L98-L137

- the trace_as_chain_group context do not contain the code
- add the callback to answer_similarity._score_batch method

**Comment by jjmachan** [comment]
this has been fixed with #390
