### ISSUE TITLE
testgenerator

### ISSUE THREAD

**Issue by zhzfight** [explodinggradients/ragas#372]
anaconda3/envs/rag/lib/python3.11/site-packages/ragas/testset/testset_generator.py", line 200, in _filter_question
    return json_results.get("verdict") != "No"
           ^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'

This error occurred during the execution of testgenerator. After inspecting the code, I found that if the open-source model I am using outputs in an incorrect format, such as a string containing only numbers, then the load_as_json method would directly return an integer, leading to this error. This doesn’t seem to be the correct behavior. Or is it because the model I am using is not powerful enough? What type of model should I choose for dataset generation (I am on a budget haha)? thanks dude

**Comment by zhzfight** [comment]
could you help?
`model = LlamaCpp(
        model_path="model/mistral-7b-instruct-v0.1.gguf",
        temperature=0.75,
        max_tokens=2000,
        n_ctx=4096,
        top_p=1,
        verbose=True  # Verbose is required to pass to the callback manager
    )

    # loading files in a directory
    # loader = DirectoryLoader('../doc/', glob="**/*.pdf", show_progress=True)
    loader = DirectoryLoader('doc/', show_progress=True)
    data = loader.load()
    print("Loading Documents nubmers: ", len(data))
    print("data:", data)

    llm = LangchainLLM(model)
    testset_distribution = {
        "simple": 0.25,
        "reasoning": 0.5,
        "multi_context": 0.0,
        "conditional": 0.25,
    }

    testsetgenerator = TestsetGenerator(generator_llm=llm, critic_llm=llm, embeddings_model=embeddings,testset_distribution=testset_distribution,  chunk_size=512)
    testset = testsetgenerator.generate(data, 100)
`
the above code is copied from your docs, and it always encounter the error like this:
`anaconda3/envs/rag/lib/python3.11/site-packages/llama_cpp/llama.py", line 422, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaModel.__del__ at 0x7f41c450aa20>
Traceback (most recent call last):`
This prevents me from continuing my work.

**Comment by jjmachan** [comment]
this is a current limitation of ragas and will be fixed in the next version but unfortunately we don't have a work around for this yet :(
