### ISSUE TITLE
AuthenticationError with "Answer Correctness"

### ISSUE THREAD

**Issue by codinseok** [explodinggradients/ragas#373]
```
from ragas.metrics import AnswerCorrectness
answer_correctness = AnswerCorrectness(
    weights=[0.4,0.6]
)

results = answer_correctness.score(dataset["train"].select(range(3)))
```
`RuntimeError: ('Fatal error occurred while running async tasks.', AuthenticationError("Error code: 401 - {'error': {'message': 'Incorrect API key provided: `

code raise runtime error. i can use other metrics but Answercorectness.
i use azure openAI  api, gpt4, ada-002

**Comment by ZhexuanZhou** [comment]
meet the same runtime error.

**Comment by ZhexuanZhou** [comment]
similar to #325

**Comment by shahules786** [comment]
Hi @codinseok , please initialize Azure open ai embeddings as shown here https://docs.ragas.io/en/latest/howtos/customisations/azure-openai.html

**Comment by codinseok** [comment]
Hi @shahules786 , I am using the rest of the metrics(context_precision,faithfulness,answer_relevancy,context_recall) normally. The same problem occurs only in two specific cases. (answer_similarity,answer_correctness)

**Comment by shahules786** [comment]
Thank you @codinseok

**Comment by owerbai** [comment]
> 此外，我尝试先运行其他指标，然后在最后尝试（answer_similarity、answer_correctness）。



> 嗨，我正常使用其余的指标（context_precision，忠诚度，answer_relevancy，context_recall）。仅在两种特定情况下会出现相同的问题。（answer_similarity，answer_correctness）

另外几种指标报这个错该如何处理
