### ISSUE TITLE
Get score for each context chunk

### ISSUE THREAD

**Issue by leonseet** [explodinggradients/ragas#389]
Is it possible to retrieve individual scores for each context when using Context Precision and Context Relevancy, rather than a cumulative score? For instance, if I retrieve three distinct chunks of data, I would like to obtain score for each chunk.

**Comment by shahules786** [comment]
It's not supported as of now, could you tell me your use case for this? @leonseet

**Comment by leonseet** [comment]
To do more granular analysis on each context retrieved.

**Comment by jjmachan** [comment]
hey @leonseet - did you find a work around for this?
