### ISSUE TITLE
[Bug Report] Duplicated questions are generated while calculating answer relevance

### ISSUE THREAD

**Issue by un-certainty** [explodinggradients/ragas#396]
**Describe the bug**
While cacluating the answer relevance, the temperature is set to 0 by default. So with `n=self.strictness`, it will return `n` same questions, which is unexpected.

https://github.com/explodinggradients/ragas/blob/9850f096fd289c68a7a0cc84063f43797ac0c79f/src/ragas/metrics/_answer_relevance.py#L123-L127

**Comment by un-certainty** [comment]
Also, the answer relavence is now calculated in an indirect way (by embedding similarity). Is it possible that we decompose the question into a list of sub-queries and check the ratio of whether the answer contains related information?

**Comment by NilAndNone** [comment]
I change the prompt to let llm only gen one question, it works for me with my local llm, I believe that GPT will be able to perform even better

**Comment by shahules786** [comment]
@un-certainty thanks for sharing this with us. We have been refactoring code for async operations and hence wasn't able to fix this issue earlier. I have raised a PR for this.
