### ISSUE TITLE
The FILTER_QUESTION prompt used for testset_generator.py need to be corrected / improved

### ISSUE THREAD

**Issue by mosama1994** [explodinggradients/ragas#400]
**Issue Description**
The FILTER_QUESTION prompt used for test set generation to evaluate the RAG pipeline needs to be corrected / improved. The link to the prompts.py file is as follows:
https://github.com/explodinggradients/ragas/blob/main/src/ragas/testset/prompts.py

**Original FILTER_QUESTION prompt**
"""
Determine if the given question can be clearly understood even when presented without any additional context. Specify reason and verdict is a valid json format.
question: What is the keyword that best describes the paper's focus in natural language understanding tasks?
{{"reason":"The specific paper being referred to is not mentioned in the question.", "verdict": "No"}}
question:{question}
"""

**Suggested Improved FILTER_QUESTION prompt**
"""
The task is to assess whether the given question can be clearly understood without any additional context. Analyze the question provided at the end and provide feedback in a valid JSON format as follows:
{{
  "reason": "Specify the reason if the question can be understood without any additional context.",
  "verdict": "A single word 'Yes' or 'No' indicating whether the question can be understood or not."
}}
question: {question}
"""

**Comment by shahules786** [comment]
Hi @mosama1994 , thanks for your feedback. Test set generation is in active refactoring, I have changed and improved almost all of the prompts in the module. In fact, my latest prompts are very similar to your suggestion.

**Comment by mosama1994** [comment]
Thank you. I was also looking for easier implementation of incorporating open source llm's and embedding models in the framework. That would be great. Currently instead of inheriting the ragas base classes and implementing my own theory, I used hugging face models through langchain and made changes to the Langchain model code. As hugging face is the most widely used open source platform for downloading different models (llms, encoders, rerankers, etc.), it would be great if we had easier implemetation for that.

**Comment by jjmachan** [comment]
Hey @mosama1994 - great to meet you 🙂 
could you tell me a bit more about what changes you had to make and why you had to make those changes?

i do understand good HF support is crucial which is why I was curious
