### ISSUE TITLE
VLLM RAGAS API key error for HuggingFace Models

### ISSUE THREAD

**Issue by Jaykumaran** [explodinggradients/ragas#405]
Does anyone have idea about using RAGAS EVALUATION using VLLM server for HuggingFace models.I was successfully serving my model,but ragas metrics evaluation does recognise vlllm serving and it always asks for open ai api key

cell1:
!python -u -m vllm.entrypoints.openai.api_server \
       --host 0.0.0.0 \
       --model TheBloke/Mistral-7B-Instruct-v0.2-AWQ \
       --dtype half \
       --max-num-batched-tokens 4096 \
       --max-model-len 256 \
       --quantization awq \
       --tensor-parallel-size 1 \
       --port 8010 | grep -q "Uvicorn running" &npx localtunnel --port 8010

cell2:
from langchain.chat_models import ChatOpenAI
from ragas.llms import LangchainLLM

inference_server_url = "http://localhost:8010/v1"

# create vLLM Langchain instance
chat = ChatOpenAI(
    model="mistralai/Mistral-7B-Instruct-v0.2",
    openai_api_key="no-key",
    openai_api_base=inference_server_url,
    max_tokens=256,
    temperature=0.2,
)

# use the Ragas LangchainLLM wrapper to create a RagasLLM instance
vllm = LangchainLLM(llm=chat)

cell3:
evaluate
from ragas import evaluate

result = evaluate(
fiqa_eval["baseline"].select(range(5)), # showing only 5 for demonstration
metrics=[faithfulness],
)

result

OpenAIKeyNotFound: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable

Running this on T4 cuda 12.2 colab free tier

**Comment by shahules786** [comment]
Hi @Jaykumaran , apologies for the late response. Were you able to solve this issue?

**Comment by Jaykumaran** [comment]
Hi,thanks I have used RAGAS with VLLM successfully,
but  calculating metric evaluation its very slow.Like when doing faithfulness score calculation.It takes more time,.
I'm hosting my VLLM endpoint in one T4 colab notebook and imferencing ragas in another notebook T4 .Inferencing is fast but calculating scores takes more time
