### ISSUE TITLE
Issue with faithfulness

### ISSUE THREAD

**Issue by Robs1999** [explodinggradients/ragas#411]
I am occasionally encountering an error when evaluating with faithfulness. The error is at line 178, when computing the faithful statements:

    176                 output = output if isinstance(output, list) else []
    177                 faithful_statements = sum(
--> 178                     verdict_score_map.get(dict.get("verdict", "").lower(), np.nan)
    179                     for dict in output
    180                 )

AttributeError: 'int' object has no attribute 'lower'

**Comment by shahules786** [comment]
Hi @Robs1999 , this is interesting. Would be able to provide the sample for which this issue is being encountered?
