### ISSUE TITLE
Issue with import *LangchainLLM* in Databricks 

### ISSUE THREAD

**Issue by zohaibdr** [explodinggradients/ragas#412]
While running on Databricks, the following error is encountered when running _from ragas.llms import LangchainLLM_

**ImportError: cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings' (/databricks/python/lib/python3.10/site-packages/langchain/embeddings/__init__.py)**

It works perfectly well on my PC. 

Ragas version: 0.0.22
Python version: 3.10.12
Langchain ver:  0.0.217

**Code to Reproduce**
from ragas.llms import LangchainLLM

**Error trace**
----> 4 from ragas.llms import LangchainLLM
      5 from ragas.testset import TestsetGenerator
      6 from langchain.chat_models.azure_openai import AzureChatOpenAI

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/__init__.py:1
----> 1 from ragas.evaluation import evaluate
      3 try:
      4     from ._version import version as __version__

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/evaluation.py:10
      7 from datasets import Dataset, concatenate_datasets
      9 from ragas._analytics import EvaluationEvent, track
---> 10 from ragas.metrics.base import Metric
     11 from ragas.metrics.critique import AspectCritique
     12 from ragas.validation import (
     13     remap_column_names,
     14     validate_column_dtypes,
     15     validate_evaluation_modes,
     16 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/metrics/__init__.py:1
----> 1 from ragas.metrics._answer_correctness import AnswerCorrectness, answer_correctness
      2 from ragas.metrics._answer_relevance import AnswerRelevancy, answer_relevancy
      3 from ragas.metrics._answer_similarity import AnswerSimilarity, answer_similarity

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/metrics/_answer_correctness.py:11
      8 from langchain.callbacks.manager import CallbackManager, trace_as_chain_group
      9 from langchain.prompts import ChatPromptTemplate, HumanMessagePromptTemplate
---> 11 from ragas.metrics._answer_similarity import AnswerSimilarity
     12 from ragas.metrics.base import EvaluationMode, MetricWithLLM
     13 from ragas.utils import json_loader

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/metrics/_answer_similarity.py:9
      6 import numpy as np
      7 from datasets import Dataset
----> 9 from ragas.embeddings.base import (
     10     HuggingfaceEmbeddings,
     11     OpenAIEmbeddings,
     12     embedding_factory,
     13 )
     14 from ragas.exceptions import OpenAIKeyNotFound
     15 from ragas.metrics.base import EvaluationMode, MetricWithLLM

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/embeddings/__init__.py:1
----> 1 from ragas.embeddings.base import (
      2     AzureOpenAIEmbeddings,
      3     FastEmbedEmbeddings,
      4     HuggingfaceEmbeddings,
      5     OpenAIEmbeddings,
      6     RagasEmbeddings,
      7 )
      9 __all__ = [
     10     "HuggingfaceEmbeddings",
     11     "OpenAIEmbeddings",
   (...)
     14     "FastEmbedEmbeddings",
     15 ]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e45e8563-0586-47e9-a096-aedc15631cbc/lib/python3.10/site-packages/ragas/embeddings/base.py:9
      6 from typing import List
      8 import numpy as np
----> 9 from langchain.embeddings import AzureOpenAIEmbeddings as BaseAzureOpenAIEmbeddings
     10 from langchain.embeddings import OpenAIEmbeddings as BaseOpenAIEmbeddings
     11 from langchain.embeddings import FastEmbedEmbeddings as BaseFastEmbedEmbeddings

**Additional context**
only encountered on **databricks**

**Comment by shahules786** [comment]
Hi @zohaibdr , can you update langchain and try again?

**Comment by zohaibdr** [comment]
> Hi @zohaibdr , can you update langchain and try again?

Thanks a lot. Its working now with langchain 0.0.352
