### ISSUE TITLE
Cannot access ragas.evaluation.evaluate() is_async argument

### ISSUE THREAD

**Issue by anthonyivn2** [explodinggradients/ragas#441]
Hi I am not sure if this is intentional or not (hence why I am not marking it as a bug), but it seems like I am not able to set the _is_async_ argument in ragas.evaluation.evaluate function as True even though it seems like based on this [documentation page](https://docs.ragas.io/en/latest/references/evaluation.html) it is an argument for the function. I am using ragas version 0.0.22.

**Comment by jjmachan** [comment]
ohh @anthonyivn2 that is because it is only available in the `main` branch right now. You will have to install it from the source.

do give it a go if you want - does have some breaking changes though. 

Thanks also for raising the issue and helping us with keeping ragas top-notch 🙂

**Comment by jjmachan** [comment]
I'm closing this for now - feel free to reopen in case you need it

**Comment by jjmachan** [comment]
ps this will also be generally available with our `v0.1` release

**Comment by anthonyivn2** [comment]
Ok got it, would the v0.1 release comes with the changes where _context precision_ would require _ground truths_?

**Comment by shahules786** [comment]
@anthonyivn2 Yes but it will be still optional. You can try this out now by installing ragas from source.
