### ISSUE TITLE
[Bug Report] Wrong few shot example used in Context Recall

### ISSUE THREAD

**Issue by un-certainty** [explodinggradients/ragas#446]
The reason is wrong:

https://github.com/explodinggradients/ragas/blob/041b20cb00eb200bb6e62df8104baf0ac801b976/src/ragas/metrics/_context_recall.py#L52-L60

**Comment by shahules786** [comment]
@un-certainty thanks a lot for bringing this up, would you like to raise a PR to have this fixed? 

Apologies for the late reply as I was traveling.
