### ISSUE TITLE
Azure has not provided the response due to a content filter being triggered

### ISSUE THREAD

**Issue by atursunov** [explodinggradients/ragas#449]
**Describe the bug**
Trying to run ragas evaluations as mentioned here: https://docs.ragas.io/en/latest/howtos/customisations/azure-openai.html. In some cases it runs OK, but on other cases the same code throws following error:

![image](https://github.com/explodinggradients/ragas/assets/7220691/64064f0d-dcc2-418a-b67f-b16b6d7582e8)

![image](https://github.com/explodinggradients/ragas/assets/7220691/94ff05c4-4c1f-45b0-b633-d2da8f70634e)

It looks like the issue is not in ragas but wondering is there a retry option in ragas, so we can re-run code if it fails?

Ragas version: 0.0.22
OpenAI version: 1.6.1
LangChain version: 0.1.0
Python version: 3.10

**Comment by danieljohnxon** [comment]
Hi @atursunov, did you managed to resolve it?

**Comment by atursunov** [comment]
Yes, it is more on Langchain and OpenAI side. Later will post a workaround.

**Comment by vinay235** [comment]
@atursunov could you please share the solution? I am working to implement this with Azure OpenAI and getting the same error as you but with latest Ragas package.
