### ISSUE TITLE
Python library must be updated to the latest version

### ISSUE THREAD

**Issue by GabrieleFerrario** [explodinggradients/ragas#463]
**Describe the bug**
The available version of the python library is old and it must be updated to the latest version of the main branch.
I need the last version to use the evaluation with GPT-4.
Ragas version: v0.0.22 
Python version: 3.9.4

**Code to Reproduce**
from langchain.chat_models import ChatOpenAI

gpt4 = ChatOpenAI(model_name="gpt-4")

from ragas.llms.base import LangchainLLMWrapper

gpt4_wrapper = LangchainLLMWrapper(langchain_llm=gpt4)

**Error trace**

**Expected behavior**
I expect that in ragas.llms.base there is LangchainLLMWrapper as in the branch main of the git repo

**Additional context**

**Comment by lqcStar** [comment]
My error is "cannot import name 'LangchainLLMWrapper' from 'ragas.llms.base' (/usr/local/lib/python3.10/dist-packages/ragas/llms/base.py)",  did you solve it

**Comment by shahules786** [comment]
@lqcStar @GabrieleFerrario please install the version from source for now, we are working hard to resolve bugs to make a stable release ASAP.
```
pip install git+https://github.com/explodinggradients/ragas.git
```

**Comment by GabrieleFerrario** [comment]
@lqcStar yes I solved using the main branch of the repo or if you want in the stable version you can follow this: https://docs.ragas.io/en/stable/howtos/customisations/llms.html
