### ISSUE TITLE
How can we use Azure OpenAI key with Ragas?

### ISSUE THREAD

**Issue by abhijithneilabraham** [explodinggradients/ragas#468]
Trying to run an example script the following way and got an error:

```
from ragas import evaluate
from datasets import Dataset, Features, Sequence, Value
import os

# Set the OpenAI API key
os.environ["OPENAI_API_KEY"] = "$YOUR AZURE OPENAI KEY"

# Define the structure of your dataset with the correct types
features = Features({
    'question': Value('string'),
    'contexts': Sequence(Value('string')),  # Contexts as a sequence of strings
    'answer': Value('string'),
    'ground_truths': Sequence(Value('string'))  
})

# Example data (update this with your actual data)
data = {
    'question': ["What is the capital of France?", "What is the boiling point of water?"],
    'contexts': [["Paris is known for its beautiful streets."], ["Water boils at 100 degrees Celsius."]],
    'answer': ["Paris", "100 degrees Celsius"],
    'ground_truths': [["Paris"], ["100 degrees Celsius"]]  # Note the nested lists
}

# Create the dataset
dataset = Dataset.from_dict(data, features=features)

# Evaluate the dataset
results = evaluate(dataset)

# Output the results
print(results)
```

Error:

`openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided:"**********************" . You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

Version : Latest installation from source ` git+https://github.com/explodinggradients/ragas.git@5f105c08b7579188aea1113334dae6b6a8a15660#egg=ragas`

**Comment by shahules786** [comment]
Hi @abhijithneilabraham , please refer to https://docs.ragas.io/en/latest/howtos/customisations/azure-openai.html

**Comment by htzayada** [comment]
Hi,
i got the same error even i defined flow according to the guide you pointed.
can you help with more concrete example?
To keep it simple, i defined the data hard coded and sent the data for evaluate as below:
result = evaluate(
        dataset = dataset,
        metrics=[
            context_precision,
            context_recall,
            faithfulness,
            answer_relevancy,
        ],
        llm=azure_model
    )

It seems Evaluation has been started(8%) and then got the error:
Evaluating:   8%|██████████████████▋        
....

openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: ******************************. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by htzayada** [comment]
Found solution- it was required to pass embedding instance as the default embedding is OpenAIEmbedding which require API_KEY which didn't define for embedding. so when i passed my embedding(not of OpenAI) it worked. Thanks anyway!
