### ISSUE TITLE
ImportError: cannot import name 'LangchainLLM' from 'ragas.llms'

### ISSUE THREAD

**Issue by abhijithneilabraham** [explodinggradients/ragas#469]
In docs and the examples mentioned, Ragas uses `LangchainLLM` but that throws the following error:

```
ImportError: cannot import name 'LangchainLLM' from 'ragas.llms' 
```

Ragas version: git+https://github.com/explodinggradients/ragas.git@5f105c08b7579188aea1113334dae6b6a8a15660#egg=ragas
Python version: 3.9

Upon quick inspection into the [imports](https://github.com/explodinggradients/ragas/blob/main/src/ragas/llms/__init__.py) I believe `LangchainLLMWrapper` should be in place for the docs.

**Comment by shahules786** [comment]
Hi @abhijithneilabraham , you're using latest version of ragas but the docs you're referring to are from stable version. Please refer to https://docs.ragas.io/en/latest/

**Comment by shahules786** [comment]
Oops, sorry. I am raising a fix for this https://github.com/explodinggradients/ragas/pull/473
