### ISSUE TITLE
 cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings'

### ISSUE THREAD

**Issue by chenyunsai** [explodinggradients/ragas#492]
This is my first time using ragas, but I encountered an error when importing this package: from ragas import evaluate.

**Comment by jjmachan** [comment]
which version of Ragas are you using?
this is mostly likely due to langchain, ragas miss-match

**Comment by chenyunsai** [comment]
Below is my version information:
ragas                      0.0.20
langchain                  0.0.200
langchain-community        0.0.13
langchain-core             0.1.13
langchainplus-sdk          0.0.20
langsmith                  0.0.83
openai                     1.0.1

**Comment by chenyunsai** [comment]
I upgrade my langchain version,this problme be solved~

**Comment by shahules786** [comment]
@chenyunsai thanks for the update, closing the issue on that remark.
