### ISSUE TITLE
OPENAI_API_KEY set in google cloud function cannot be found by RAGAS library

### ISSUE THREAD

**Issue by aarontxz** [explodinggradients/ragas#494]
**Describe the bug**
I am deploying a google cloud function using functions_framework, that takes in an OPENAI_API_KEY as a parameter and setting the OPENAI_API_KEY environment before calling the RAGAS evaluation. However I receive the message 

{"error":"OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable"} 

This only happens when I try to set the Environment Variable within the http function using os.environment["OPENAI_API_KEY"] = , if I set the OPENAI_API_KEY environment variable on the google cloud functions console environment variables it works, it also works when I edit the ragas library code and add os.environment["OPENAI_API_KEY"] = , in the _answer_relevance.py file inside the metrics folder.

**Comment by leticiacechinel** [comment]
I faced the same issue, apparently the problem is related to this  _answer_relevance.py file/metric indeed

**Comment by riyaj8888** [comment]
ragas.exceptions.OpenAIKeyNotFound: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable


i am using open-source llm but still i m getting this error.

**Comment by jjmachan** [comment]
tracking this here folks - this has been fixed for you in main and will add docs soon #503
