### ISSUE TITLE
TestsetGenerator runs into "Invalid json: Extra data"

### ISSUE THREAD

**Issue by tenshis** [explodinggradients/ragas#498]
**Describe the bug**
 **self.critic_llm.generate_text_with_hmpt** in the **_filter_context** function under **testset_generator.py** produces results that have additional symbols after the json part of the answer. Sometimes it even returns the rating for the example context about Albert Einstein, additionally to the actual rating. This leads to the next step, load_as_json, to fail, rendering all TestsetGenerator attempts useless, as none of the documents receive scores.

Ragas version: current main (1.0.23dev)
Python version: 3.11.7

**Code to Reproduce**
`results = self.critic_llm.generate_text_with_hmpt(prompts=[prompt])`
`output = results.generations[0][0].text.strip()`

output
'{"score":2.0, "is_table_present":true}**<|im_sep|>**'

`output = load_as_json(output)`

Invalid json: Extra data: line 1 column 39 (char 38)

**Expected behavior**
These two lines need to be more robust to handle possible LLM weirdness. For example, instead of simply stripping the text, grab everything within curly brackets or that looks like json. So instead of:

```
output = results.generations[0][0].text.strip()
output = load_as_json(output)
```

we could have:

```
import re
json_objects = re.findall(r'{[^}]*}', results.generations[0][0].text)
output = json_objects[-1].strip()
output = load_as_json(output)
```

**Comment by shahules786** [comment]
Hey @tenshis , can you update to the latest version and try using our improved version of this? https://docs.ragas.io/en/latest/concepts/testset_generation.html

**Comment by tenshis** [comment]
Hi shahules,

This is now working with the newest version (0.1.0rc1) and using gpt4
