### ISSUE TITLE
Latest tag Incompatible

### ISSUE THREAD

**Issue by kediaharshit9** [explodinggradients/ragas#499]
Doing a `poetry add ragas` installs version 0.0.22 
It downloads required langchain( +core + community), llamaindex and many other packages

But many things have changed in the dependencies, and existing imports fail for this version (at mltiple places, I am using TestsetGenerator).

I also see that the last release was made on Dec 12. Can anything be done regarding it?

**Comment by jjmachan** [comment]
closing this since its fixed now :)
