### ISSUE TITLE
Llama Index | Compatibility Issue

### ISSUE THREAD

**Issue by jordanparker6** [explodinggradients/ragas#501]
**Describe the bug**
The latest llama index is not compatible with the imports in the test_generator.py file.

Ragas version: 0.0.22
Python version: 3.11

**Error trace**

```
from llama_index.node_parser.simple import SimpleNodeParser
ModuleNotFoundError: No module named 'llama_index.node_parser.simple'
```

**Comment by jjmachan** [comment]
tracking this issue here #557 
closing this for now but will get the llamaindex issue sorted for you this week :)
