### ISSUE TITLE
OPENAI_API_KEY' environment variable

### ISSUE THREAD

**Issue by riyaj8888** [explodinggradients/ragas#502]
ragas.exceptions.OpenAIKeyNotFound: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable

i am using open-source llm but still i m getting this error.

tried with ragas==0.0.20/0.0.22

**Comment by riyaj8888** [comment]
still same error

**Comment by jjmachan** [comment]
will fix this #503

**Comment by jjmachan** [comment]
closing for now because the fix has been made and the documentation is tracking in the above PR.

really sorry about this guys but with v0.1 you'll have a much simpler experience (I hope 🤞🏽 )
