### ISSUE TITLE
context_precision, OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable

### ISSUE THREAD

**Issue by bellyqpp** [explodinggradients/ragas#505]
hello,there was something wrong.

from ragas.metrics import (
answer_relevancy,
faithfulness,
context_recall,
context_precision,
)
error information:cannot import name 'context_precision' from 'ragas.metrics' (c:\python\lib\site-packages\ragas\metrics_init_.py).

so ,in sep 2023,
from ragas.metrics import (
context_relevancy,
answer_relevancy,
faithfulness,
context_recall,
)

there have some changes. so I really want to know the difference. as the same ,i do not have ground_truth.

also  OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable.

**Comment by AugustDS** [comment]
Seems to be related to the pip version, if you install from source it works.

**Comment by riyaj8888** [comment]
even after installing from source

**Comment by riyaj8888** [comment]
make some stable release, every new release fucks up

**Comment by shahules786** [comment]
@riyaj8888 please provide a valid open-ai key, your issue must be resolved.

**Comment by riyaj8888** [comment]
Brother , I am using open source LLM.
Not open ai but still it's giving the same error.
I tried installing from source also

**Comment by Lanture1064** [comment]
In my occasion, the `evaluate()` somehow reaches `os.environ["OPENAI_API_KEY"]` and OpenAI API even after wrapping open source LLM instance and setting metrics, causing the problem.

**Comment by shahules786** [comment]
Hi @riyaj8888 @Lanture1064 Can you both please share the ragas version you're using? I would highly recommend you to shift to latest version by using `pip install ragas=="ragas==0.1.0rc1`

**Comment by Lanture1064** [comment]
@shahules786 Thx for reply, and yes I was using pip 0.0.22 version. Trying the newer 0.1.0 ver now

**Comment by jjmachan** [comment]
closing this because it has been fixed in the latest and will be released soon. Feel free to reopen if needed.

but the current usage pattern is that the `evaluate()` function takes to additional arguments `llm` and `embeddings`. The doc string explains their behaviour
```
    llm: BaseRagasLLM, optional
        The language model to use for the metrics. If not provided then ragas will use
        the default language model. This can be overridden by the llm specified in
        the metric level with `metric.llm`.
    embeddings: BaseRagasEmbeddings, optional
        The embeddings to use for the metrics. If not provided then ragas will use
        the default embeddings. This can be overridden by the embeddings specified in
        the metric level with `metric.embeddings`.
```

please feel free to share your suggestion here, I'm sorry we are not perfect but we will try our best to get there for you guys
