### ISSUE TITLE
Bug in Answer Similarity Calculation

### ISSUE THREAD

**Issue by LEMONATREE** [explodinggradients/ragas#506]
**Describe the bug**
Hi, I've noticed some change in the implementation of AnswerSimilarity in latest version of ragas

in v0.0.22, the implementation is 

def _score_batch(
        self: t.Self,
        dataset: Dataset,
        callbacks: t.Optional[Callbacks] = None,
        callback_group_name: str = "batch",
    ) -> list[float]:
        ground_truths, answers = dataset["ground_truths"], dataset["answer"]
        ground_truths = [item[0] for item in ground_truths]

and it change to

def _score(self, row: t.Dict, callbacks: Callbacks) -> float:
        assert self.embeddings is not None, "embeddings must be set"

        ground_truths, answers = row["ground_truths"], row["answer"]
        ground_truths = [item[0] for item in ground_truths]

row is the a sample in dataset, "ground_truths = [item[0] for item in ground_truths]" only take first character of str, 
so i suppose it is a bug

Ragas version:build from source
Python version:3.11

**Code to Reproduce**
Share code to reproduce the issue

**Error trace**

**Expected behavior**

**Additional context**

**Comment by AnnamariaGalante** [comment]
same issue, also for answer relevancy! it appens on version 0.0.22 but not in 0.0.21

**Comment by jjmachan** [comment]
We will add this in the documentation but in the meantime tagging @shahules786 so that he can share the reasoning behind it

We will add this as part of our v0.1 migration docs
