### ISSUE TITLE
ragas.exceptions.OpenAIKeyNotFound when I try the guide "Bring your own LLMs"

### ISSUE THREAD

**Issue by BNZhao** [explodinggradients/ragas#535]
When I try the guide: "Bring your own LLMs" to use ragas, if answer_relevancy is added to metrics, the following message is displayed: 
**ragas.exceptions.OpenAIKeyNotFound: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable**

How to fix it? I used ragas-0.0.22 with python=3.11.

**Comment by jjmachan** [comment]
should be fixed with #553 
could you check and reopen if not fixed?

**Comment by ng-tarun** [comment]
All of sudden, why this is coming up in ragas when using answer relevancy
