### ISSUE TITLE
RAGAS answer_relevancy integration with OpenAI broken

### ISSUE THREAD

**Issue by wolfman-numba1** [explodinggradients/ragas#536]
**Describe the bug**
answer_relevancy metric does not seem to work with open ai key when RAGAS is installed from pip (version 0.0.22)

Ragas version: 0.0.22
Python version: 3.11.7

**Code to Reproduce**
`data = {
        'question': [user_question],
        'answer': st.session_state.answer,
        'contexts' : st.session_state.context,
        'ground_truths': [[user_ground_truth]]
    }
    dataset = Dataset.from_dict(data)

    os.environ["OPENAI_API_KEY"] = open_ai_api_key

    from ragas.metrics import (
        faithfulness,
        answer_relevancy,
        context_precision,
        context_recall,
    )

    metrics = []
    for eval_type, eval_config in {
        "faithfulness": [eval_answer_faithfulness, faithfulness],
        "answer_relevancy": [eval_answer_relevancy, answer_relevancy],
        "context_precision": [eval_context_precision, context_precision],
        "context_recall": [eval_context_recall, context_recall],
    }.items():
        if eval_config[0]:
            metrics.append(eval_config[1])
    gpt4 = ChatOpenAI(model_name="gpt-4")

    faithfulness.llm.langchain_llm = gpt4
    answer_relevancy.llm.langchain_llm = gpt4
    context_precision.llm.langchain_llm = gpt4
    context_recall.llm.langchain_llm = gpt4
    result = evaluate(dataset, metrics)
    print(result)`

**Error trace**
`2024-01-31 15:51:30.524 Uncaught app exception
Traceback (most recent call last):
  File "/Users/paavramo/.pyenv/versions/3.11.7/envs/doco-bot/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/paavramo/Documents/QLD Treasury/doco-bot/cdk/lib/fargate/doco-bot/pages/Evaluation.py", line 189, in <module>
    result = evaluate(dataset, metrics)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paavramo/.pyenv/versions/3.11.7/envs/doco-bot/lib/python3.11/site-packages/ragas/evaluation.py", line 93, in evaluate
    [m.init_model() for m in metrics]
  File "/Users/paavramo/.pyenv/versions/3.11.7/envs/doco-bot/lib/python3.11/site-packages/ragas/evaluation.py", line 93, in <listcomp>
    [m.init_model() for m in metrics]
     ^^^^^^^^^^^^^^
  File "/Users/paavramo/.pyenv/versions/3.11.7/envs/doco-bot/lib/python3.11/site-packages/ragas/metrics/_answer_relevance.py", line 100, in init_model
    raise OpenAIKeyNotFound
ragas.exceptions.OpenAIKeyNotFound: OpenAI API key not found! Seems like your trying to use Ragas metrics with OpenAI endpoints. Please set 'OPENAI_API_KEY' environment variable`

**Expected behavior**
Should work as written. When i comment out the references to answer relevancy the solution works as is with no issues with the OpenAI key and I get back valid results.

**Comment by shahules786** [comment]
Hey @wolfman-numba1 , can you install the latest version from the source and try again?
please refer to docs.ragas.io/en/latest while doing so
