### ISSUE TITLE
ValueError: Dataset feature "contexts" should be of type Sequence[string], got <class 'datasets.features.features.Value'>

### ISSUE THREAD

**Issue by VpkPrasanna** [explodinggradients/ragas#543]
**Describe the bug**

Ragas version:
pre-release :ragas==0.1.0rc1
Python version: 3.10
**Code to Reproduce**
Share code to reproduce the issue
```python
data = {'question': "How to deposit a cheque issued to an associate in my business into my business account?",
        "answer":"The best way to deposit a cheque issued to an associate in your business into your business account is to open a business account with the bank. You will need a state-issued dba certificate from the county clerk's office as well as an Employer ID Number (EIN) issued by the IRS. Once you have opened the business account, you can have the associate sign the back of the cheque and deposit it into the business account",
        "contexts":['Just have the associate sign the back and then deposit it.  It\'s called a third party cheque and is perfectly legal.  I wouldn\'t be surprised if it has a longer hold period and, as always, you don\'t get the money if the cheque doesn\'t clear. Now, you may have problems if it\'s a large amount or you\'re not very well known at the bank.  In that case you can have the associate go to the bank and endorse it in front of the teller with some ID.  You don\'t even technically have to be there.  Anybody can deposit money to your account if they have the account number. He could also just deposit it in his account and write a cheque to the business."I have checked with Bank of America, and they say the ONLY way to cash (or deposit, or otherwise get access to the funds represented by a check made out to my business) is to open a business account. They tell me this is a Federal regulation, and every bank will say the same thing.  To do this, I need a state-issued ""dba"" certificate (from the county clerk\'s office) as well as an Employer ID Number (EIN) issued by the IRS. AND their CHEAPEST business banking account costs $15 / month. I think I can go to the bank that the check is drawn upon, and they will cash it, assuming I have documentation showing that I am the sole proprietor. But I\'m not sure.... What a racket!!"When a business asks me to make out a cheque to a person rather than the business name, I take that as a red flag. Frankly it usually means that the person doesn\'t want the money going through their business account for some reason - probably tax evasion. I\'m not saying you are doing that, but it is a frequent issue. If the company makes the cheque out to a person they may run the risk of being party to fraud. Worse still they only have your word for it that you actually own the company, and aren\'t ripping off your employer by pocketing their payment. Even worse, when the company is audited and finds that cheque, the person who wrote it will have to justify and document why they made it out to you or risk being charged with embezzlement. It\'s very much in their interests to make the cheque out to the company they did business with. Given that, you should really have an account in the name of your business. It\'s going to make your life much simpler in the long run.']}

df = pd.DataFrame(data)
dataset = Dataset.from_pandas(df=df)

result = evaluate(
    dataset,  # showing only 5 for demonstration
    metrics=[faithfulness,answer_relevancy,harmfulness],llm=chat,embeddings=hf_embeddings
)
```
**Error trace**
```
Traceback (most recent call last):
  File "ragas_evaluation.py", line 38, in <module>
    result = evaluate(
  File "/home/platformuser/geniq/rag/ragas_test/ragas_env/lib/python3.8/site-packages/ragas/evaluation.py", line 140, in evaluate
    validate_column_dtypes(dataset)
  File "/home/platformuser/geniq/rag/ragas_test/ragas_env/lib/python3.8/site-packages/ragas/validation.py", line 32, in validate_column_dtypes
    raise ValueError(
ValueError: Dataset feature "contexts" should be of type Sequence[string], got <class 'datasets.features.features.Value'>
```

**Expected behavior**

**Additional context**

**Comment by VpkPrasanna** [comment]
hi @jjmachan  thanks for it , and i saw the same docs few days back and i solved it .

**Comment by ananthanarayanan431** [comment]
from llama_index.core import SimpleDirectoryReader
from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core import VectorStoreIndex
from llama_index.core.settings import Settings
from llama_index.core import load_index_from_storage
from llama_index.core.storage import StorageContext
from llama_index.core import Document

from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple,reasoning,multi_context

from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
    answer_correctness,
    context_utilization,
)

from datasets import Dataset, Value, Sequence

from ragas.metrics.critique import harmfulness
from ragas.integrations.llama_index import evaluate
import ast

DATASET="./data.csv"
PATH="./STORE"

embeddings=OpenAIEmbedding()
Settings.embed_model=embeddings


class Evaluation:
    def __init__(self):
        self.generator_llm=OpenAI(model="gpt-4o-mini")
        self.critics_llm=OpenAI(model="gpt-4o-mini")
        self.evalutor_llm=OpenAI(model="gpt-4o-mini")
        self.embeddings=OpenAIEmbedding()

    
    def _RAGAS_(self):
        document = SimpleDirectoryReader(input_files=[r"file"]).load_data()

        generator=TestsetGenerator.from_llama_index(
            generator_llm=self.generator_llm,
            critic_llm=self.critics_llm,
            embeddings=self.embeddings,
        )

        testset=generator.generate_with_llamaindex_docs(
            documents=self.document,
            test_size=15,
            distributions={simple:0.25, reasoning:0.5, multi_context:0.25},
        )

        if not os.path.exists(PATH):
            vector_index=VectorStoreIndex.from_documents(documents=document)
            vector_index.storage_context.persist(persist_dir=PATH)
        else:
            storage_context=StorageContext.from_defaults(persist_dir=PATH)
            vector_index=load_index_from_storage(storage_context=storage_context)
            
        query_engine = vector_index.as_query_engine()

        testset_df = testset.to_pandas()
        testset_df.to_csv('answer.csv')

        questions = testset_df["question"].tolist()
        print(type(questions))
        print(questions)
        print("-"*100)
        ground_truth = testset_df["ground_truth"].tolist()
        print(type(ground_truth))
        print(questions)
        print("-"*100)

        data = {
            'question':[],
            'answer':[],
            'contexts':[],
            'ground_truth':ground_truth,
        }

        for val in questions:
            data['question'].append(val)
            answer = query_engine.query(val)
            data['answer'].append(answer.response)
            data["contexts"].append([node.node.get_content() for node in answer.source_nodes])

        
        dataset = Dataset.from_dict(data)

        metrics=[
            faithfulness,
            answer_relevancy,
            context_precision,
            context_utilization,
            context_recall,
            harmfulness,
            answer_correctness,
        ]

        result=evaluate(
            query_engine=query_engine,
            metrics=metrics,
            dataset=dataset,
            raise_exceptions=False,
        )
        ans=result.to_pandas()
        ans.to_csv('./val1.csv')

        with open("metrics.json", "w") as json_file:
            json.dump(result, json_file, indent=4)

        print(type(result))
        return result

if __name__=="__main__":
    obj=Evaluation()
    print(obj._RAGAS_())
    
Complete working code and It's working fine!
