### ISSUE TITLE
[Question] Does ragas now support async call?

### ISSUE THREAD

**Issue by hteeyeoh** [explodinggradients/ragas#551]

**Comment by jjmachan** [comment]
yes we do starting from v0.1 release happening next week
(but you can install from source to get a taste)

**Comment by hteeyeoh** [comment]
> yes we do starting from v0.1 release happening next week (but you can install from source to get a taste)

It will be available via pip install binaries packages also?

**Comment by jjmachan** [comment]
yes, will be out in a couple of hours

**Comment by hteeyeoh** [comment]
Thank you for the info. Hope to get a proper guidance/documentation for this as well :)

**Comment by jjmachan** [comment]
it actually works under-the-hood. You don't have to do anything. but will be updating the docs over the week

**Comment by hteeyeoh** [comment]
Cool. Thank you
