### ISSUE TITLE
Testset generation prompt customization

### ISSUE THREAD

**Issue by gleason-m** [explodinggradients/ragas#556]
The current SimpleEvolution seed question prompt uses a hardcoded Prompt. I have a usecase where I want to use a customized prompt to generate certain types of questions. The only way I see to accomplish this is at the moment is to derive a class based on SimpleEvolution and copy/paste `_aevolve` using a custom Prompt instead of the seed_question_prompt.

It would be nice to have the ability to inject or otherwise customize a prompt.

**Comment by jjmachan** [comment]
actually you can do it another way. just call SimpleEvolution with a different prompt like so

```py
from ragas.testset.evolutions import SimpleEvolution

simple = SimpleEvolution(seed_question_prompt=# your prompt)
``` 
note you will have init the rest of the attributes for `Evolution` and the `Prompt` object should be of the format https://docs.ragas.io/en/latest/concepts/prompts.html

**Comment by gleason-m** [comment]
Ahh, did not see this was added with this PR https://github.com/explodinggradients/ragas/pull/530

I'll pull latest. Thanks!
