### ISSUE TITLE
[R-257] [Feature Request] Llamaindex support

### ISSUE THREAD

**Issue by jjmachan** [explodinggradients/ragas#557]
the title says it all
but this is for ragas v0.1 😉 

<sub>[R-257](https://linear.app/exploding-gradients/issue/R-257/[feature-request]-llamaindex-support)</sub>

**Comment by jjmachan** [comment]
form where are you importing `llm = AzureOpenAI`? if its from llamaIndex that is the problem

**Comment by nariman-zk** [comment]
@jjmachan Yes you are right! It's being imported from llama-index.
So I should wait for this feature to be implemented!
Thanks!

**Comment by nshern** [comment]
> Hi: Is this feature being actively worked on? The downgrade of Llamaindex isn't an option for my project, but I would like to leverage Ragas if possible.

In the same boat and would love to use Ragas in my llamaindex project.

**Comment by owerbai** [comment]
> > 嗨：这个功能正在积极开发中吗？Llamaindex 的降级不是我的项目的一个选项，但如果可能的话，我想利用 Ragas。
> 
> 我在同一条船上，很想在我的 llamaindex 项目中使用 Ragas。

same to you

**Comment by lalehsg** [comment]
> > Hi: Is this feature being actively worked on? The downgrade of Llamaindex isn't an option for my project, but I would like to leverage Ragas if possible.
> 
> I am in the same boat and would love to use Ragas in my llamaindex project.

Same here! :-)

**Comment by nshern** [comment]
> > > Hi: Is this feature being actively worked on? The downgrade of Llamaindex isn't an option for my project, but I would like to leverage Ragas if possible.
> > 
> > 
> > I am in the same boat and would love to use Ragas in my llamaindex project.
> 
> Same here! :-)

FWIW I found that the built-in evaluation module is working perfectly fine. I am using the [correctness evaluator](https://docs.llamaindex.ai/en/stable/examples/evaluation/correctness_eval/)

**Comment by owerbai** [comment]
> > > > Hi: Is this feature being actively worked on? The downgrade of Llamaindex isn't an option for my project, but I would like to leverage Ragas if possible.
> > > 
> > > 
> > > I am in the same boat and would love to use Ragas in my llamaindex project.
> > 
> > 
> > Same here! :-)
> 
> FWIW I found that the built-in evaluation module is working perfectly fine. I am using the [correctness evaluator](https://docs.llamaindex.ai/en/stable/examples/evaluation/correctness_eval/)

谢谢你，我已经成功在我的llama-index项目中实现了

**Comment by jjmachan** [comment]
this will be out in the next release `v0.1.9`

My sincere apologies for not taking finishing this up earlier
