### ISSUE TITLE
Testset generation error on Bedrock

### ISSUE THREAD

**Issue by subha-aws** [explodinggradients/ragas#563]
**Describe the bug**

Ragas version: 0.1.0rc2.dev26+g6a88465
Python version: 3.10.13

**Code to Reproduce**
```py
###Add custom llms and embeddings
generator_llm = LangchainLLMWrapper(candidate_llm1)
critic_llm = LangchainLLMWrapper(judge_llm)
embeddings_model = LangchainEmbeddingsWrapper(titan_embeddings,RunConfig(max_retries=2, max_wait=30))

Change resulting question type distribution
testset_distribution = {
"simple": 0.25,
"reasoning": 0.5,
"multi_context": 0.0,
"conditional": 0.25,
}

splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=100)
keyphrase_extractor = keyphraseExtractor(llm=generator_llm)

docstore = InMemoryDocumentStore(
splitter=splitter,
embeddings=embeddings_model,
extractor=keyphrase_extractor,
)
test_generator = TestsetGenerator(
generator_llm=generator_llm,
critic_llm=critic_llm,
embeddings=titan_embeddings,
docstore=docstore
)

testset = test_generator.generate_with_langchain_docs(documents=documents,
test_size=10,
distributions=testset_distribution)
```

**Error trace**
```
/ragas/src/ragas/testset/docstore.py:250, in InMemoryDocumentStore.add_nodes(self, nodes, show_progress, desc)
248 for i, n in enumerate(nodes):
249 if i in nodes_to_embed.keys():
--> 250 n.embedding = results[nodes_to_embed[i]]
251 if i in nodes_to_extract.keys():
252 keyphrases = results[nodes_to_extract[i]]

IndexError: list index out of range
```

**Expected behavior**

**Additional context**
langchain documents.
Tried with diffrent chunk sizes and overlapps, different embedding configs and different bedrock models(cohere and titan text)
I am getting with any model on Bedrock "IndexError: list index out of range" happens exactly at 50% point all the time

**Comment by shahules786** [comment]
Hey @subha-aws , thanks for sharing this bug. I have also noticed this, and will fix is ASAP

**Comment by jjmachan** [comment]
hey @subha-aws can you update to v0.1. I don't think that fixes this issue but the error trace you gave is a bit misleading I think. Need the full trace for v0.1. If you could pass that that would be really helpful for us to reproduce :)

**Comment by jjmachan** [comment]
wow it seems like the error is coming from langchain because there are not callbacks used - very strange. could you add a callback to test it? please refer https://docs.ragas.io/en/stable/howtos/applications/tracing.html

**Comment by shahules786** [comment]
Hey @subha-aws Is this a new error? I have raised a fix for the earlier one you posted and was able to run test gen on bedrock
```
from langchain_community.chat_models import BedrockChat
from langchain_community.embeddings import BedrockEmbeddings
from ragas.embeddings.base import BaseRagasEmbeddings, LangchainEmbeddingsWrapper
from ragas.llms import BaseRagasLLM, LangchainLLMWrapper


config = {
   your-config
}

bedrock_model = BedrockChat(
    credentials_profile_name=config["credentials_profile_name"],
    region_name=config["region_name"],
    endpoint_url=f"https://bedrock-runtime.{config['region_name']}.amazonaws.com",
    model_id=config["model_id"],
    model_kwargs=config["model_kwargs"],
)
bedrock_model = LangchainLLMWrapper(bedrock_model)
# init the embeddings
bedrock_embeddings = BedrockEmbeddings(
    credentials_profile_name=config["credentials_profile_name"],
    region_name=config["region_name"],
)

bedrock_embeddings = LangchainEmbeddingsWrapper(bedrock_embeddings)


###Add custom llms and embeddings
generator_llm = bedrock_model
critic_llm = bedrock_model

from ragas.testset.extractor import KeyphraseExtractor
from langchain.text_splitter import TokenTextSplitter
from ragas.testset.docstore import InMemoryDocumentStore


splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=100)
keyphrase_extractor = KeyphraseExtractor(llm=generator_llm)
docstore = InMemoryDocumentStore(
splitter=splitter,
embeddings=bedrock_embeddings,
extractor=keyphrase_extractor,
)
from ragas.testset import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

test_generator = TestsetGenerator(
generator_llm=generator_llm,
critic_llm=critic_llm,
embeddings=bedrock_embeddings,
docstore=docstore,
)

testset = test_generator.generate_with_llamaindex_docs(documents=documents[:5],
test_size=10,distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})

```

**Comment by shahules786** [comment]
Hey @subha-aws once the PR is merged can you reinstall from source and try again?

**Comment by subha-aws** [comment]
> Hey @subha-aws once the PR is merged can you reinstall from source and try again?

Sure will test this out today. btw, I was using langchain documents not llama index. I will check them out either way!  Thank you!

**Comment by shahules786** [comment]
cool, feel free to close this issue if it works out for you. @subha-aws

**Comment by subha-aws** [comment]
@shahules786  , Can I add this to the documentation for Bedrock? I also have a notebook for bedrock for LLM comparison.

**Comment by shahules786** [comment]
Yes please @subha-aws . I think it would be best to add it [here](https://docs.ragas.io/en/stable/howtos/customisations/aws-bedrock.html)
Like I have added for [language adaptation](https://docs.ragas.io/en/stable/howtos/applications/use_prompt_adaptation.html), create a section for metrics and test generation. If you need clarity, happy to hoping a [call](https://calendly.com/shahules/30min)

**Comment by shahules786** [comment]
Let me know if you're working on it so that I can create an issue and assign it to you and make sure non one else is doing the same. @subha-aws

**Comment by subha-aws** [comment]
@shahules786  Yes please do.

**Comment by subha-aws** [comment]
> cool, feel free to close this issue if it works out for you. @subha-aws

Still no luck with latest from code @ 0.1.dev294+gc203801.d20240210'

strangely it ran once!!  ( I had not given a model Id for bedrock embeddings, is the embeddings needed?)

**Comment by subha-aws** [comment]
> cool, feel free to close this issue if it works out for you. @subha-aws

This works! Thank you

**Comment by Xiaoyuan-xyz** [comment]
Has this issue been closed?
I had the similar error and I was using the latest version of ragas, and I used LangchainLLMWrapper.

File "/home/admin1/miniconda3/envs/lccc/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 853, in agenerate
    isinstance(callbacks[0], (list, BaseCallbackManager))
IndexError: list index out of range

**Comment by dabincicode** [comment]
@subha-aws  Same issue. Please let me know if the issue has been resolved!

**Comment by Totoro8697** [comment]
@shahules786 hi, I am getting same error as well others. I am using generate_with_langchain_docs by the way.

**Comment by vecorro** [comment]
Hi,

I'm using Ragas v0.1.3 and I'm also getting the same error `IndexError: list index out of range` regardless of generating from LangChain or LlamaIndex documents. The error seems to be related to the DocumentStore population. Here is the stack trace:


```
ExceptionInRunner                         Traceback (most recent call last)
Cell In[3], line 32
     23 dataset_generator = TestsetGenerator(
     24     generator_llm=generator_llm,
     25     critic_llm=critic_llm,
     26     embeddings=langchain_emb,
     27     docstore=doc_store,
     28 )
     31 # RunConfig.max_workers=4
---> 32 dataset_generator.generate_with_langchain_docs(
     33     documents=lchain_docs[:50],
     34     test_size=10,
     35     distributions=dataset_distribution,
     36  #   run_config=RunConfig
     37 )   

File ~/miniconda3/envs/llm-env4/lib/python3.10/site-packages/ragas/testset/generator.py:152, in TestsetGenerator.generate_with_langchain_docs(self, documents, test_size, distributions, with_debugging_logs, is_async, raise_exceptions, run_config)
    141 def generate_with_langchain_docs(
    142     self,
    143     documents: t.Sequence[LCDocument],
   (...)
    150 ):
    151     # chunk documents and add to docstore
--> 152     self.docstore.add_documents(
    153         [Document.from_langchain_document(doc) for doc in documents]
    154     )
    156     return self.generate(
    157         test_size=test_size,
    158         distributions=distributions,
   (...)
    162         run_config=run_config,
    163     )

File ~/miniconda3/envs/llm-env4/lib/python3.10/site-packages/ragas/testset/docstore.py:215, in InMemoryDocumentStore.add_documents(self, docs, show_progress)
    210 # split documents with self.splitter into smaller nodes
    211 nodes = [
    212     Node.from_langchain_document(d)
    213     for d in self.splitter.transform_documents(docs)
    214 ]
--> 215 self.add_nodes(nodes, show_progress=show_progress)

File ~/miniconda3/envs/llm-env4/lib/python3.10/site-packages/ragas/testset/docstore.py:254, in InMemoryDocumentStore.add_nodes(self, nodes, show_progress)
    252 results = executor.results()
    253 if results == []:
--> 254     raise ExceptionInRunner()
    256 for i, n in enumerate(nodes):
    257     if i in nodes_to_embed.keys():

ExceptionInRunner: The runner thread which was running the jobs raised an exeception. Read the traceback above to debug it. You can also pass `raise_exceptions=False` incase you want to show only a warning message instead.
```




Here is my code from a Jupyter Notebook:
```
from langchain_community.llms import VLLMOpenAI
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.document_loaders import PyPDFDirectoryLoader
from langchain.text_splitter import TokenTextSplitter


from ragas.testset import TestsetGenerator
from ragas.testset.docstore import InMemoryDocumentStore
from ragas.testset.extractor import KeyphraseExtractor
from ragas.run_config import RunConfig
from ragas.embeddings.base import BaseRagasEmbeddings, LangchainEmbeddingsWrapper
from ragas.llms import BaseRagasLLM, LangchainLLMWrapper



PDF_FILES_PATH = "../../doc_collections"

# LLamaIndex embedding model
EMBEDDING_MODEL = "BAAI/bge-base-en-v1.5"
model_kwargs = {'device': 'cuda:0'}
encode_kwargs = {'normalize_embeddings': False}
langchain_emb = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

# LLM service settings
langchain_llm = VLLMOpenAI(
    openai_api_base="localhost/api/v1",
    model_name="WizardLM/WizardLM-70B-V1.0",
    temperature=0.1,
    max_tokens=512,
)

langchain_llm = LangchainLLMWrapper(langchain_llm)
langchain_emb = LangchainEmbeddingsWrapper(langchain_emb)


loader = PyPDFDirectoryLoader(path=PDF_FILES_PATH)
lchain_docs = loader.load()


# Add custom llms and embeddings
generator_llm = langchain_llm
critic_llm = langchain_llm

splitter = TokenTextSplitter(chunk_size=1024, chunk_overlap=20)
keyphrase_extractor = KeyphraseExtractor(llm=critic_llm)
doc_store = InMemoryDocumentStore(
    splitter=splitter,
    embeddings=langchain_emb,
    extractor=keyphrase_extractor,
)
dataset_distribution = {
    "simple": 0.5,
    "reasoning": 0.25,
    # "multi_context": 0.1,
    "conditional": 0.25,
}

dataset_generator = TestsetGenerator(
    generator_llm=generator_llm,
    critic_llm=critic_llm,
    embeddings=langchain_emb,
    docstore=doc_store,
)


# RunConfig.max_workers=4
dataset_generator.generate_with_langchain_docs(
    documents=lchain_docs[:50],
    test_size=10,
    distributions=dataset_distribution,
 #   run_config=RunConfig
)   

```

Thanks for any help to get over this error.

**Comment by sona-16** [comment]
I was trying to do "Synthetic test data generation" using RAGAS framework with the help of the below document.
 
"https://docs.ragas.io/en/stable/concepts/testset_generation.html"

I'm facing error. Please have a look on the below error. 

ragas.exceptions.ExceptionInRunner: The runner thread which was running the jobs raised an exeception. Read the traceback above to debug it. You can also pass `raise_exceptions=False` incase you want to show only a warning message instead.
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<as_completed.<locals>.sema_coro() running at C:\Users\sonaganesh.g\Desktop\RAGAS syhthetic data generation\syn\Lib\sit
e-packages\ragas\executor.py:38> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[as_completed.<locals>._on_completion() at C:\Users\sonaganesh.g\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py:618]>
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<as_completed.<locals>.sema_coro() running at C:\Users\sonaganesh.g\Desktop\RAGAS syhthetic data generation\syn\Lib\sit
e-packages\ragas\executor.py:38> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[as_completed.<locals>._on_completion() at C:\Users\sonaganesh.g\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py:618]>
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<as_completed.<locals>.sema_coro() running at C:\Users\sonaganesh.g\Desktop\RAGAS syhthetic data generation\syn\Lib\site-packages\ragas\executor.py:38> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[as_completed.<locals>._on_completion() at C:\Users\sonaganesh.g\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py:618]>

**Comment by sadaf0714** [comment]
I have a related error, below is the traceback:
WARNING:ragas.validation:passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`
Evaluating:  25%
 3/12 [00:05<00:11,  1.25s/it]
WARNING:ragas.llms.output_parser:Failed to parse output. Returning None.
WARNING:ragas.llms.output_parser:Failed to parse output. Returning None.
Exception in thread Thread-355:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/ragas/executor.py", line 96, in run
    results = self.loop.run_until_complete(self._aresults())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/ragas/executor.py", line 84, in _aresults
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ragas/executor.py", line 79, in _aresults
    r = await future
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/local/lib/python3.10/dist-packages/ragas/executor.py", line 38, in sema_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/ragas/executor.py", line 112, in wrapped_callable_async
    return counter, await callable(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ragas/metrics/base.py", line 116, in ascore
    raise e
  File "/usr/local/lib/python3.10/dist-packages/ragas/metrics/base.py", line 112, in ascore
    score = await self._ascore(row=row, callbacks=group_cm, is_async=is_async)
  File "/usr/local/lib/python3.10/dist-packages/ragas/metrics/_answer_relevance.py", line 167, in _ascore
    return self._calculate_score(answers, row)
  File "/usr/local/lib/python3.10/dist-packages/ragas/metrics/_answer_relevance.py", line 139, in _calculate_score
    cosine_sim = self.calculate_similarity(question, gen_questions)
  File "/usr/local/lib/python3.10/dist-packages/ragas/metrics/_answer_relevance.py", line 113, in calculate_similarity
    question_vec = np.asarray(self.embeddings.embed_query(question)).reshape(1, -1)
  File "/usr/local/lib/python3.10/dist-packages/langchain_google_vertexai/embeddings.py", line 391, in embed_query
    return self.embed([text], 1, "RETRIEVAL_QUERY")[0]
  File "/usr/local/lib/python3.10/dist-packages/langchain_google_vertexai/embeddings.py", line 363, in embed
    embeddings.extend(t.result())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain_google_vertexai/embeddings.py", line 194, in _get_embeddings_with_retry
    with telemetry.tool_context_manager(self._user_agent):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/root/.local/lib/python3.10/site-packages/google/cloud/aiplatform/telemetry.py", line 48, in tool_context_manager
    _pop_tool_name(tool_name)
  File "/root/.local/lib/python3.10/site-packages/google/cloud/aiplatform/telemetry.py", line 57, in _pop_tool_name
    raise RuntimeError(
RuntimeError: Tool context error detected. This can occur due to parallelization.
---------------------------------------------------------------------------
ExceptionInRunner                         Traceback (most recent call last)
<ipython-input-36-4e37e43ed01c> in <cell line: 1>()
----> 1 metrices = getMetrices(dataset)

2 frames
/usr/local/lib/python3.10/dist-packages/ragas/evaluation.py in evaluate(dataset, metrics, llm, embeddings, callbacks, is_async, run_config, raise_exceptions, column_map)
    211         results = executor.results()
    212         if results == []:
--> 213             raise ExceptionInRunner()
    214 
    215         # convert results to dataset_like

ExceptionInRunner: The runner thread which was running the jobs raised an exeception. Read the traceback above to debug it. You can also pass `raise_exceptions=False` incase you want to show only a warning message instead.

Please help me with this asap! @subha-aws
