### ISSUE TITLE
Add back support for Langchain Evalchains

### ISSUE THREAD

**Issue by jjmachan** [explodinggradients/ragas#567]
**Describe the Feature**
with V0.1, support for langchain EvalChain is broken, add that back in

**Comment by leehanchung** [comment]
Any ETA? Or some architecture/code scaffolds so at least I can help accelerate this?

**Comment by jjmachan** [comment]
hey @leehanchung , you could invoke (or ainvoke()`) it in a loop and create the dataset to evaluate.

refer this [notebook](https://colab.research.google.com/drive/1C1Epju1lVkXTQi2jBq1njrOrmkfg0eQS?usp=sharing). 


This might take some time for me to fix -worst case 2 weeks. I apologize for the hard time 🙁
