### ISSUE TITLE
Evaluate not working and set_run_config error 

### ISSUE THREAD

**Issue by rafikoham** [explodinggradients/ragas#586]
Hey guys, 

I'm trying to evaluate my RAG and I have a dataset that is well fitted for the evaluate function but unfortunalty I got this error : 

**AttributeError: 'list' object has no attribute 'set_run_config'**
and it comes from : **_[m.init(run_config) for m in metrics]_** (Line 179 from the evaluation.py) 

How can I solve it please?

**Comment by Senthselvi** [comment]
what is the solution for this error "Evaluation failed: 'CustomOllama' object has no attribute 'set_run_config'" Ragas?

**Comment by vardhman-saal** [comment]
what is the solution ?
