### ISSUE TITLE
Add tests for `llm.json_load`

### ISSUE THREAD

**Issue by jjmachan** [explodinggradients/ragas#606]
**Describe the Feature**
bugs like the one @pberger514 caught in #593 might occur down the road too. We need tests for these sections of code. The catch here is that these are tests which need LLM calls so have to add a new Pytest mark for this

**Comment by pberger514** [comment]
Happy to pick this one up.

**Comment by jjmachan** [comment]
assigned - feel free to give it a go 🙌🏽

**Comment by jjmachan** [comment]
we might need to colaborate to figure out the right pytest magic so that everything is easy to use from the CI. 

I think we will have to test this for a couple of models like OpenAI, Bedrock, Llama2 and Mistral, have it part of the CI

**Comment by pberger514** [comment]
@jjmachan I put a first pass in a draft. Let me know your thoughts, I'm happy to expand to other models if you think this works.
