### ISSUE TITLE
context_precision metrics changes?

### ISSUE THREAD

**Issue by hteeyeoh** [explodinggradients/ragas#629]
**Describe the bug**
I was trying to evaluate the metric "context_precision" using ragas. But I hit into below:
```
The metric [context_precision] that that is used requires the following additional columns ['ground_truth'] to be present in the dataset. Looks like you're trying to use 'context_precision' without ground_truth. Please use consider using  `context_utilization' instead.
```
As i remember in version 0.0.22 and even the documentation mentioned that context_precision is measured based on questions and context, it does not involved ground truth. But in latest version, it seems that not the case.

And also I bumped into issue of "'AzureChatOpenAI' object has no attribute 'set_run_config' when i using my own azure GPT4 as llm to parse into evaluate(). This, i did not faced when using version 0.0.22.

Seems like version 0.1.1 have lots of broken things.

Ragas version: 0.1.1
Python version: 3.10

**Comment by jjmachan** [comment]
are you seeing this warning anywhere?
```py
            logger.warning(
                "Using 'context_precision' without ground truth will be soon depreciated. Use 'context_utilization' instead"
            )
```

as for you second question could you share a code snippet so I can give you a fix?

**Comment by hteeyeoh** [comment]
Yes the warning i saw when i try to run the evaluate with context_precision metric without providing "ground_truth" just like what i have did using v0.0.22 but using latest version i saw that warning which i paste in my question.

For 2nd question, i just simply follow the guide mentioned in here: https://docs.ragas.io/en/v0.1.1/howtos/customisations/azure-openai.html using my azureopenai gpt as llm.
