### ISSUE TITLE
To disable usage tracking, just need to RAGAS_DO_NOT_TRACK=False in env variable?

### ISSUE THREAD

**Issue by hteeyeoh** [explodinggradients/ragas#630]
**Your Question**
Is it just directly set RAGAS_DO_NOT_TRACK=false in env variable to disable usage tracking? is it work if i install the ragas from pip?

**Comment by jjmachan** [comment]
yes it works how ever you install it - no worries at all 🙂 
you can read _analytics.py for more sets.
