### ISSUE TITLE
Text-to-SQL Support Evaluation ?

### ISSUE THREAD

**Issue by Putnug1122** [explodinggradients/ragas#651]
I have a use case for text-to-SQL with RAG using LangChain. Is there any example or guide to evaluate the SQL result? Is the metric the same as regular text RAG? Thanks in advance

**Comment by shahules786** [comment]
Hey bro @Putnug1122 apologies for the late reply. But this is something we would love to add to ragas. If  you're into text-SQL applications, I would love to pick you brain on it to formulate metrics.

**Comment by bcarvalho-via** [comment]
Popular text-to-SQL benchmarks like ([bird-sql](https://bird-bench.github.io/) and [spider](https://yale-lily.github.io/spider)) propose Execution Accuracy as the main metric since string similarity or exact match metrics often don't correlate to SQL correctness.

**Comment by shahules786** [comment]
@bcarvalho-via Sorry this is probably very late for you. But now we are adding more metrics to cover more use-cases into ragas including agentic workflows. So regarding SQL - 

we found out that metrics used to evaluate text to SQL pipelines can be broadly put into
1) Execution based: This approach executes the output query, collects the output, and compares the output rows with real rows using some ways (LLM-based or non-LLM-based)
2) Non-execution-based: executing every query to evaluate the pipeline can be expensive. So if there is a way to compare predicted_sql and reference_sql one could use that instead. Here also there are LLM-based and non-LLM-based ways to do it.
What do you think? I would like to hear your thoughts on what metrics might benefit you here.
