### ISSUE TITLE
getting error in _faithfulness metric

### ISSUE THREAD

**Issue by bhaskarturkar** [explodinggradients/ragas#654]
Getting below error for faithfulness metric after executing the code
from ragas import evaluate
```
result = evaluate(
    fiqa_eval["baseline"],
    metrics=[
        context_precision,
        faithfulness,
        answer_relevancy,
        context_recall,
        harmfulness,
    ],
)
result
```

![image](https://github.com/explodinggradients/ragas/assets/150421011/e6f46f02-b4d9-473f-8163-8c10c21085b2)
![image](https://github.com/explodinggradients/ragas/assets/150421011/26935f60-6f21-4e03-a549-1873533b7349)

**Comment by bhaskarturkar** [comment]
Hi @shahules786,  
I am getting this error for ragas version 0.1.2.

**Comment by daveyko** [comment]
i am also getting this error

here are the distributions

distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25}

interestingly this doesn't happen for non multi_context

**Comment by shahules786** [comment]
Hey @daveyko this is a different issue, your issue will be resolved once you update to the latest version.

**Comment by daveyko** [comment]
@shahules786 its happening to me on the latest version 0.1.2

**Comment by shahules786** [comment]
@daveyko are you facing the same issue as described above?

**Comment by daveyko** [comment]
yup same issue im getting 
assert isinstance(statements, dict), "Invalid JSON response"

in  
File "/Users/davidko/.pyenv/versions/3.10.13/lib/python3.10/site-packages/ragas/metrics/_faithfulness.py", line 190, in _ascore

**Comment by daveyko** [comment]
this is when i run evaluate
