### ISSUE TITLE
.to_pandas() method erases randomly some ground_truth answers in testset generation

### ISSUE THREAD

**Issue by AnnaKelmanson** [explodinggradients/ragas#663]
**Describe the bug**
[ragas_test.csv](https://github.com/explodinggradients/ragas/files/14418285/ragas_test.csv)

After generation of a testset and using to_pandas() some cells in ground_truth column turned out to be empty. Also it seems like it doesn't save info uniformly (in some cases question are in quotes, in some without them). I attach the csv.

Ragas version: source
Python version: 3.12.2

**Code to Reproduce**
```
def ragas_testset(file_path, num_ques):
    docs = load_documents(file_path)
    generator = TestsetGenerator.with_openai()

    distributions = {
        simple: 0.4,
        multi_context: 0.2,
        reasoning: 0.4
    }

    testset = generator.generate_with_langchain_docs(docs, num_ques, 
                                                    distributions,
                                                    with_debugging_logs=False,  
                                                    is_async=False,  
                                                    raise_exceptions=False)
    testset_df = testset.to_pandas()
    return testset_df
```

It should have returned a df without empty cells.

**Comment by shahules786** [comment]
Hey @AnnaKelmanson Some ground-truth rows turns about to be empty due some limitation of LLM itself. I can raise a PR to resolve the formating issue now.
