### ISSUE TITLE
Ground truth vs answer vs context 

### ISSUE THREAD

**Issue by Pranshul200** [explodinggradients/ragas#665]
Can anyone explain the difference between ground_truth and answer in more deep vs context

**Comment by jcarletgo** [comment]
Does https://docs.ragas.io/en/stable/howtos/applications/data_preparation.html or https://github.com/explodinggradients/ragas/issues/655 answer your question?

**Comment by shahules786** [comment]
Hi, Closing this PR due to lack of activity. I hope your doubt was resolved.
