### ISSUE TITLE
LlamaIndex ModuleNotFoundError

### ISSUE THREAD

**Issue by althoenm** [explodinggradients/ragas#669]
Getting a module not found error when trying to import `ragas.llama_index` as shown in the documentation. 

Ragas version: 0.1.2
Python version: 3.10.12

**Code to Reproduce**
`from ragas.llama_index import evaluate`

**Error trace**
```
ModuleNotFoundError: No module named 'ragas.llama_index'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File <command-467099862076163>, line 1
----> 1 from ragas.llama_index import evaluate

ModuleNotFoundError: No module named 'ragas.llama_index'
```

**Expected behavior**
Successful import of the `evaluate` module for use with LlamaIndex query engines as detailed [here](https://docs.ragas.io/en/latest/howtos/integrations/llamaindex.html)

**Comment by mribrgr** [comment]
I took a deep look into the history. For now it seems like llama_index support for evaluation got dropped with v0.1.0 where the necessary files were deleted. I am not sure about the reason and I am also highly confused why it's still in all of the docs, but hopefully a mod can help us here.
It's still possible to use the v0.0.22 for the evaluation. Of course there are newer features like adopt() missing.

**Comment by nshern** [comment]
Which versions of llamaindex and ragas am I required to use in order to make this work?

**Comment by jjmachan** [comment]
added it in the new version 
docs: https://docs.ragas.io/en/stable/howtos/integrations/llamaindex.html

**Comment by Senthselvi** [comment]
what is the solution? which version is working one?
