### ISSUE TITLE
POST Call to  https://t.explodinggradients.com:443?

### ISSUE THREAD

**Issue by gauravdd** [explodinggradients/ragas#675]
Hi,

I saw in my debug logs that there is POST call to https://t.explodinggradients.com:443.  Could you please tell me what is being sent? and how do I stop it?  if there is a setting or so?  We work on regulated environment and data, so this is important to know.

2024-02-28,17:04:59 urllib3.connectionpool:549 - DEBUG:https://t.explodinggradients.com:443 "POST / HTTP/1.1" 200 15

**Comment by stydxm** [comment]
set  `RAGAS_DEBUG_TRACKING` to true
read more [here](https://github.com/explodinggradients/ragas/blob/main/src/ragas/_analytics.py)  
duplicate #630

**Comment by gauravdd** [comment]
Thank you

**Comment by shahules786** [comment]
Hi @gauravdd @stydxm Just for additional info,  we do not track any sensitive information as you can verify in the code. The tracking is just to see how many samples are being evaluated. 
Closing the issue on that remark.

**Comment by dmvieira** [comment]
I think you should set `RAGAS_DO_NOT_TRACK = True` too
