### ISSUE TITLE
Support `langchain-google-genai`

### ISSUE THREAD

**Issue by joy13975** [explodinggradients/ragas#678]
**Describe the Feature**
Support Google Gemini API like how OpenAI API is supported as first class citizen.

**Why is the feature important for you?**
I need to test both OpenAI and Google Gemini APIs, but currently I need to repeat a big chunk of `TestsetGenerator.with_openai()` for the equivalent of `langchain-google-genai` code.

**Additional context**
`temperature` setting also corrected to prevent error described in #656

**Comment by joy13975** [comment]
PR raised: #677, but breaks Python <=3.8 so careful review is needed.

**Comment by RazHadas** [comment]
I have same error when using gemini an Ragas, any suggestions?

**Comment by nehas0326** [comment]
@RazHadas @joy13975 How have you used gemini with Ragas? I need this. Kindly help me out.

**Comment by anshupandey** [comment]
@nehas0326  here is an example of using gemini with Ragas: https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/use-cases/retrieval-augmented-generation/rag-evaluation/ragas_with_gemini.ipynb
