### ISSUE TITLE
answer_relevancy

### ISSUE THREAD

**Issue by Prashant0520** [explodinggradients/ragas#680]
**Your Question**
what model  is used by ragas for answer relevancy score calculation ? 
I didn't mentioned any model name or inference API till ragas generating an evaluation report ? 

**Additional context**

**If Rags follow this below steps to calculate the answer relevancy score what model is used to generate the question in step-1 and which embedding model is used for generating embeddings which in turn is used for calculating cosine similarity ?**

To calculate the relevance of the answer to the given question, we follow two steps:

Step 1: Reverse-engineer ‘n’ variants of the question from the generated answer using a Large Language Model (LLM). For instance, for the first answer, the LLM might generate the following possible questions:

Question 1: “In which part of Europe is France located?”

Question 2: “What is the geographical location of France within Europe?”

Question 3: “Can you identify the region of Europe where France is situated?”

Step 2: Calculate the mean cosine similarity between the generated questions and the actual question.
The underlying concept is that if the answer correctly addresses the question, it is highly probable that the original question can be reconstructed solely from the answer.

**Comment by shahules786** [comment]
Ragas by default uses gpt-3-5 and ada-2 embeddings. 
Please close the issue if it's clear :)
