### ISSUE TITLE
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by gowrijsuria** [explodinggradients/ragas#683]
Hi, 
I'm trying to use RAGAs library for synthetic test set generation, I do not have access to gpt4. The critic_lllm in TestsetGenerator.with_openai() uses gpt4 by default, so I changed it to gpt3.5. However, it throws the error gpt4 not available. 

I've attached the code with the error below. Pls let me know if there's a solution for this. Thank you!

Ragas version: 0.1.2
Python version: 3.9

**Code to Reproduce**
```
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

# generator with openai models
generator = TestsetGenerator.with_openai(generator_llm = "gpt-3.5-turbo-16k", critic_llm = "gpt-3.5-turbo-16k")

# generate testset
testset = generator.generate_with_langchain_docs(documents, test_size=10, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})
```

**Error trace**
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

If there are ways to generate the test set with open source LLMs, please help me with the same.

**Comment by shahules786** [comment]
Hey @gowrijsuria do you have access to gpt-4 model? Seems like you don't have it. Can you checkout customising test set generation document for using any llm of your choice? https://docs.ragas.io/en/latest/howtos/customisations/bring-your-own-llm-or-embs.html

**Comment by gowrijsuria** [comment]
I have access to gpt3.5 , hence I passed that as the param. However, it doesn't work. Pls check this issue
