### ISSUE TITLE
More verbose output in evaluate

### ISSUE THREAD

**Issue by alexjyong** [explodinggradients/ragas#686]
**Your Question**
Like I asked in https://github.com/explodinggradients/ragas/issues/108, is there a way to have more verbose output in evaluate?

It would be nice to see how ragas arrived to a score.

**Code Examples**
Currently, I can hack in this functionality by adding in a print statement here for faithfulness:

https://github.com/explodinggradients/ragas/blob/30c830377644dce94e410f3ce3a8aa4339bb74a9/src/ragas/metrics/_faithfulness.py#L201

But it would be nice to turn this on or off with a configuration option or something.

If not, I'd be happy to whip up a PR for this.

**Comment by shahules786** [comment]
Hey, please refer to callbacks and tracing for doing this https://docs.ragas.io/en/latest/howtos/applications/tracing.html
