### ISSUE TITLE
Any way to use llamaindex docstore nodes and embeddings?

### ISSUE THREAD

**Issue by asti009asti** [explodinggradients/ragas#687]
Is there a way to pass ragas llamaindex's StorageContext.docstore object to use already generated nodes and embeddings? When dealing with large number of really big documents - waiting for re-indexing is a problem. There's docstore parameter in TestsetGenerator class but I am confused with the documents parameter in generate_with_llamaindex_docs() method.
```
def get_docstore():
    config = load_toml_configs("data.toml")
    storage = config['data']['storage_path']
    storage_context = StorageContext.from_defaults(persist_dir=storage)
    return storage_context.docstore

def main():
    #...
    generator = TestsetGenerator.with_openai(
        docstore=get_docstore(),
        generator_llm=llm,
        critic_llm=critic_llm,
        embeddings=embeddings_llm
        )

    #...
    question_dataset = generator.generate_with_llamaindex_docs(
        documents=documents,
        test_size=number_of_questions,
        distributions=distributions,
        is_async=False,
        raise_exceptions=False
        )
```

**Comment by izikeros** [comment]
I would be also interested in reusing nodes/chunks and embedding that I already have in database.

Can we somehow "fuse" RAGAS test set generator to bypass documents loading, chunking, embedding and just inject nodes with embeddings and other things that are required to start generating?
