### ISSUE TITLE
Customizing Ragas Evaluation

### ISSUE THREAD

**Issue by Prashant0520** [explodinggradients/ragas#692]
I want to use my own llm model and embedding for ragas evaluation 
i follow ragas documentation but got this below error

Ragas version: 0.0.22 
Python version: 3.8.10

**Code**
langchain_llm = BaseLanguageModel(model=model_name, api_key = "*********")
langchain_embeddings = Embeddings(model=model_name)
result = evaluate(dataset=dataset,metrics=metrics,llm=langchain_llm,embeddings=langchain_embeddings)

**Error**               
"Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages".

**Comment by shahules786** [comment]
Hey, checkout https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html
