### ISSUE TITLE
TestsetGenerator for Azure OpenAI endpoints

### ISSUE THREAD

**Issue by Hungreeee** [explodinggradients/ragas#697]
**Your Question**
Hi there, I find the TestsetGenerator feature very interesting and would like to use it. But I can see that this feature is not yet available for Azure OpenAI endpoint users, right? Am I missing something?

**Comment by shahules786** [comment]
Hey PR #670 Addresses this issue. Will make a release this week :)

**Comment by Hungreeee** [comment]
Good to know!
