### ISSUE TITLE
Metric explainability in evaluate

### ISSUE THREAD

**Issue by peanutshawny** [explodinggradients/ragas#699]
**Describe the Feature**
Many metrics, such as answer relevance and faithfulness, utilize LLMs to generate intemediary results (ex., faithfulness claims, relevance questions from given answer) that are then evaluated and aggregated in a downstream step. Right now (to the best of my knowledge) these intermediary outputs can't be surfaced, so explainability is lacking. 

For example, given a faithfulness score of 0.75, it would be useful to surface 1) the claims that were extracted from the answer, and 2) the LLM rating for each claim.

**Why is the feature important for you?**
Surfacing these intermediary outputs can increase interpretability and give users a better experience in debugging and improving their own custom prompts that can be used to tune ragas to their particular use case. Ideally, this functionality should be implemented through the `evaluate` function and used like so:

```
   result = evaluate(
       dataset=dataset,
       metrics=metrics,
       explainability=True
   )
```

**Additional context**
I'm trying to use this library and it is difficult to explain or debug why a metric is a particular value.

**Comment by shahules786** [comment]
Hey @peanutshawny got your point. But we have something called callbacks which does moreover the same. Checkout out integration page https://docs.ragas.io/en/stable/howtos/integrations/index.html
to write custom callbacks https://python.langchain.com/docs/modules/callbacks/
You can log the intermediate results to almost any tracing and logging tool

**Comment by shahules786** [comment]
Feel free to reopen the issue, if you feel your issue was not addressed feel free to reopen.
