### ISSUE TITLE
Issue with TikToken Dependency 

### ISSUE THREAD

**Issue by MosheAbG** [explodinggradients/ragas#706]
Hello,

Firstly, thank you for this great framework and library!

I installed your package and followed your notebook on using Ragas with Azure Open AI, but am running into an "Exception In Runner" error with a traceback to 

requests.exceptions.httperror 503 server error service unavailable for url: https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken

I think that the error is caused by a security firewall on my side, but are there any parameters that can be set to avoid having to access the external page?

Thanks in advance!

**Comment by Saman28Khan** [comment]
Did you find solution for this?
I'm also facing the same issue

**Comment by MosheAbG** [comment]
I couldn't find a direct solution, but if you switch the embedding model to be an open source one, then it works fine.
