### ISSUE TITLE
About the prompt of AnswerRelevancy

### ISSUE THREAD

**Issue by Gaia-Wu** [explodinggradients/ragas#713]
Hi！When I try to evaluate my RAG application and computing AnswerRelevancy, I found a problem: 
The QUESTION_GEN  Prompt is written in English, so the results it generates are mostly in English. My data is not in English, so the generated results will also be in English.  Is there a bias when calculating the cosine similarity between generated questions (in English) and questions (not in English)?
would you like to modify Prompt to make the generated results adaptive to the language?（Just my opinion. Do you think it is necessary?）

**Comment by shahules786** [comment]
Hey, please use automatic language adaptation to use ragas in languages other than English 
https://docs.ragas.io/en/latest/howtos/applications/use_prompt_adaptation.html
or you can modify prompts
https://docs.ragas.io/en/latest/concepts/prompts.html
