### ISSUE TITLE
Evaluation stops after about 30 rows of data

### ISSUE THREAD

**Issue by LilianSilveira** [explodinggradients/ragas#717]
I'm running evaluation on a dataset using GPT 3.5 from Azure. It works well with a sample of the data, but when I try to pass a dataset with about 200 rows, the process never finishes and the progress bar freezes.
So I tried to split the data into chunks to avoid this problem. Yesterday it was working but today the evaluation is stoping in the second chunk (after around 30 - 40 rows). Does anyone know what could be going on?
No erros, it just freezes.

Code for chunking:

for _, chunk in df.groupby(chunks):
    print(f"Chunk {chunk}")
    print(f"-------------------------------")
    try:
        dataset_abi = Dataset.from_pandas(chunk)
        result_abi = evaluate(
            dataset_abi, metrics=metrics, llm=azure_model, embeddings=azure_embeddings)
        df_resultados_item = result_abi.to_pandas()
        resultado_df = pd.concat([resultado_df, df_resultados_item])
        resultado_df.to_excel(args.output_path, index=False)
        print('DF salved')
    except Exception as e:
        print(f"Erro {e}, item {chunk}")
        pass
print('End')

**Comment by Gaia-Wu** [comment]
Have you checked your key? Is there a limit on the number of requests?

**Comment by LilianSilveira** [comment]
I managed to resolve the issue by inserting a 'time.sleep(60)' between the chunks. There is a limit on API requests that I was not aware of. Thank you!
