### ISSUE TITLE
Clarification on Faithfulness

### ISSUE THREAD

**Issue by sprt-kmelchor** [explodinggradients/ragas#720]
[X] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

Hello,

I'd like to ask how the verdict scores in Faithfulness are implemented. From my understanding of the code there is a prompt that outlines examples on how statements should be generated. Then there's this: 1 = good, 0 = bad, -1 = no verdict/NULL as the value mappings. 

But when the Faithfulness score is computed, 'NULL' values are mapped as np.nan. And this throws an error where the Faithfulness score could not be computed correctly.

Here's the prompt verdict mapping.
`NLI_STATEMENTS_MESSAGE = Prompt(
    name="nli_statements",
    instruction="Natural language inference. Use only 'Yes' (1), 'No' (0) and 'Null' (-1) as verdict.",
    ...`

Here's the compute score snippet.
`faithful_statements = sum(
            verdict_score_map.get(
                statement_with_validation.get("verdict", "").lower(), np.nan
            )
            for statement_with_validation in output
        )`

ragas==0.1.3

**Comment by shahules786** [comment]
@sprt-kmelchor Is there an error trace?

**Comment by sprt-kmelchor** [comment]
Hi @shahules786, 

This is what the evaluation returns.

/Users/KMelchor/anaconda3/lib/python3.11/site-packages/ragas/evaluation.py:273: RuntimeWarning: Mean of empty slice
  value = np.nanmean(self.scores[cn])
{'faithfulness': nan}

I managed to overcome this error by changing the _compute_score mapping. If we follow the instruction in the prompt, no-verdict statements are mapped to -1. But when we look at _compute_score there is no mapping for -1. This is the mapping currently:

`verdict_score_map = {"1": 1, "0": 0, "null": np.nan}`

So when _compute_score encounters a -1 verdict, it couldn't map it and it uses the default value (which is set to np.nan). This throws the whole computation into disarray since there is at least 1 NaN when computing for `faithful_statements`. I added a "-1": -1 mapping to `verdict_score_map` and it resolved the issue. 

`verdict_score_map = {"1": 1, "0": 0, "-1": -1, "null": np.nan}`

I'd just like clarification if what I did or what I understand is correct or if this would have effects in other parts of ragas.

**Comment by sprt-kmelchor** [comment]
Hi @shahules786,

I've been looking at some of the recent Faithfulness issues and another one seems to have the same conclusion as me (NaNs are being caused by incorrect verdict mapping). You can close this if the PR from #736 pushes through. Thanks!
