### ISSUE TITLE
AttributeError: type object 'TestsetGenerator' has no attribute 'from_default'

### ISSUE THREAD

**Issue by gliu2023** [explodinggradients/ragas#723]
There is an error when load TestsetGenerator models:

from ragas.testset import TestsetGenerator
testsetgenerator = TestsetGenerator.from_default()

AttributeError: type object 'TestsetGenerator' has no attribute 'from_default'

Any suggestions?

**Comment by shahules786** [comment]
Hey @gliu2023 can you follow the updated test generation document here
https://docs.ragas.io/en/latest/getstarted/testset_generation.html
