### ISSUE TITLE
How to save intermediate evaluation results？

### ISSUE THREAD

**Issue by aligeniewcp22** [explodinggradients/ragas#726]
When I evaluated the last piece of data (Evaluating 99%), the program got stuck. I had to run the entire evaluation process from scratch. Can I cache the intermediate results locally, and then continue with the previous results when I evaluate again?

**Comment by shahules786** [comment]
That's interesting @aligeniewcp22 unfortunately we don't have that feature right now.

**Comment by Niggl0n** [comment]
I have the same problem. Evaluation is stuck at the very last step. Does happen to me quite frequently, indepentently of the total step of evaluations and/or metric used.
