### ISSUE TITLE
Test Generator without OpenAI

### ISSUE THREAD

**Issue by jaymon0703** [explodinggradients/ragas#727]
Can we use other LLMs to generate test sets?

**Comment by shahules786** [comment]
Yes, for example https://docs.ragas.io/en/stable/howtos/customisations/aws-bedrock.html#test-data-generation
You can pass any Langchain LLM to test generator class

**Comment by jaymon0703** [comment]
Thank you @shahules786!

I get this error when running the `evaluate` code cell in the docs: `AttributeError: 'ChatVertexAI' object has no attribute 'set_run_config'`

I am using `langchain 0.1.11` and `ragas 0.1.3`.
