### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by sociengineer** [explodinggradients/ragas#730]
**Describe the Feature**
Multilingual support 

**Why is the feature important for you?**
I'm Korean and really want to use RAGAS to evaluation Korean RAG applications.

**Additional context**
If your team guide us how to add codes to support multilingual, many contributor will be appreciated.

**Comment by shahules786** [comment]
Hey @sociengineer please refer to out language adaptation feature https://docs.ragas.io/en/stable/howtos/applications/use_prompt_adaptation.html

Feel free to reopen the issue if something doesn't work for you.
