### ISSUE TITLE
The robustness of RAGAS evaluation

### ISSUE THREAD

**Issue by aligeniewcp22** [explodinggradients/ragas#731]
I use the GPT-4-turbo-128k as the evaluator and Huggingface BAAI/BGE-m3 as the embedding model. And I do the inference for a part of samples in [Loogle](https://github.com/bigai-nlco/LooGLE). The output results are as following:
{'faithfulness': 0.5714, 'answer_relevancy': 0.7825, 'answer_correctness': 0.5348}
 {'faithfulness': 0.6734, 'answer_relevancy': 0.7039, 'answer_correctness': 0.5164}

Why do the results of the same evaluation indicators (Faithfulness/Answer Relevance/Answer Correctness) differ greatly under the same test data set (200 samples)? Do you have any official robustness testing results?

**Comment by shahules786** [comment]
Hi @aligeniewcp22 We are trying to improve this from our end. There is also issue #660 - For now, it's best to average 3 runs.
