### ISSUE TITLE
Evaluation taking forever to run

### ISSUE THREAD

**Issue by Hungreeee** [explodinggradients/ragas#734]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
I am running `evaluate()` on a data set with 1 single row. Even though it is estimated at **2 seconds**, it is taking **over 10 minutes** now (and continuing). Is this normal behaviour? 

**Code Examples**
I am using an Azure OpenAI model, which requires a little bit of special endpoint modifications to work. It works perfectly with `langchain` so far. Although I have no idea why the evaluation is taking that long, I suspect it's because of this?

The embedding model:
```
embedding_model = HuggingFaceEmbeddings(
  model_name=EMBEDDING_MODEL,
  model_kwargs={"device": "cuda"},
)
```

The LLM:
```
def update_base_url(request: httpx.Request):
  if request.url.path == "/chat/completions":
    request.url = request.url.copy_with(path="[different endpoint]")

llm = ChatOpenAI(
    default_headers={"Ocp-Apim-Subscription-Key": OPENAI_KEY},
    base_url=OPENAI_ENDPOINT,
    api_key=False,
    http_client=httpx.Client(
      event_hooks={
        "request": [update_base_url],
    }),
    max_retries=10,
  )
```

The evaluation:
```
result_df = evaluate(
  test_dataset,
  llm=llm,
  embeddings=embedding_model,
  metrics=[
    context_precision,
    context_recall,
    faithfulness,
    answer_similarity,
]).to_pandas()
```

**Additional context**

**Comment by ReyGunz** [comment]
I have noticed a similar issue... one of my evaluations runs smoothly, albeit a bit slower on the last sample, while my other takes forever on the last sample, even with just one sample in the dataset total; if I say sixteen, it runs through the first fifteen, then takes forever on the last.
