### ISSUE TITLE
Incorrect Faithfulness Value Mapping

### ISSUE THREAD

**Issue by pmbaumgartner** [explodinggradients/ragas#736]
https://github.com/explodinggradients/ragas/blob/e1e05f8844635f46f60564ae6e3ae406e7e070fb/src/ragas/metrics/_faithfulness.py#L153

Shouldn't this mapping instead be:

```python
 verdict_score_map = {"1": 1, "0": 0, "-1": np.nan} 
```

Since the prompt and examples tell the model to return a "-1" verdict if the statement is invalid?

**Comment by shahules786** [comment]
Oh, yes @pmbaumgartner I would have forgotten to change the mapping after changing the prompt for adaptation. Would you like to raise a PR on this?
