### ISSUE TITLE
Separate query and context encoding models

### ISSUE THREAD

**Issue by dkoterwa** [explodinggradients/ragas#737]
[X] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
Hi, I would like to use separate models from HuggingFace to prepare embeddings of context and queries. Is there any option to do so in the current version of Ragas?

**Additional context**
A perfect option would be to create two separate arguments (e.g. query_embeddings, context_embeddings, to be able to pass pre-computed embeddings by HuggingFace model into evaluation process).

**Comment by shahules786** [comment]
Hey @dkoterwa We don't have that now. I would love to know why you would like to do that?

**Comment by dkoterwa** [comment]
Some of the metrics require to create an embedding of question, e.g. Answer Relevance. There are dense retrievers (such as DRAGON) which have separate encoders to produce embeddings for query/context. That's why using them with ragas may not be aligned with the reasoning behind training those retrievers.
