### ISSUE TITLE
Can ragas use LLMs in Ollama?

### ISSUE THREAD

**Issue by Shihui628** [explodinggradients/ragas#738]
I have deployed several LLMs in ollama, can I evaluate by LLMs in ollama using RAGAs?

**Comment by shahules786** [comment]
Yes https://docs.ragas.io/en/latest/howtos/customisations/bring-your-own-llm-or-embs.html @Shihui628

**Comment by Shihui628** [comment]
> Yes https://docs.ragas.io/en/latest/howtos/customisations/bring-your-own-llm-or-embs.html @Shihui628

thank you! really enjoy this nice tool

successfully use ragas with ollama by simple code:

`from langchain_community.chat_models import ChatOllama
from langchain_community.embeddings import OllamaEmbeddings

ollama_llm = "mistral"
model = ChatOllama(model=ollama_llm)
embeddings_ollama = OllamaEmbeddings(model="mistral") `

**Comment by Shihui628** [comment]
thank you! really enjoy this nice tool

successfully use ragas with ollama by simple code:

`from langchain_community.chat_models import ChatOllama
from langchain_community.embeddings import OllamaEmbeddings

ollama_llm = "mistral"
model = ChatOllama(model=ollama_llm)
embeddings_ollama = OllamaEmbeddings(model="mistral") `

**Comment by elmoOreo** [comment]
With Ollama I am running into this error, AttributeError: 'Ollama' object has no attribute 'set_run_config'

**Comment by Sohammhatre10** [comment]
@Shihui628 I'm getting this issue for the same
https://github.com/explodinggradients/ragas/issues/1466
