### ISSUE TITLE
Use local LLMs

### ISSUE THREAD

**Issue by seanbenhur** [explodinggradients/ragas#74]
Hi, Thanks for this amazing framework

I would like to know is there any support for using locally trained LLMs, I see that currently we can change the LLM with Langchain, but I don't want to use langchain and use a local LLM like Llama 2

**Comment by jjmachan** [comment]
Hey @seanbenhur! We're glad you like it 😊 

how are you planning to use Llama2? I would recommend using via langchain because there is a lot of support for it in the community something like this could help [Llama 2 in LangChain — FIRST Open Source Conversational Agent! - YouTube](https://www.youtube.com/watch?v=6iHVJyX2e50)

but let me know if that is not what you have in mind. Also, why are you trying to move away from langchain?

**Comment by seanbenhur** [comment]
Thanks for the prompt response, I was thinking of using Llama without langchain since I feel langchain is an extra dependency for the project

**Comment by jjmachan** [comment]
got it. Unfortunately, that is not possible right now and we don't plan to add it to the roadmap. There is also another issue which is that we have not tested Llama2's performance for evaluation so we wouldn't recommend using it for evaluation in critical applications.

hope you understand...

**Comment by seanbenhur** [comment]
Sure No problems!

I tried to use Llama with Langchain without using OpenAI, but now I am getting error since I didn't pass the OAI key on the importing stage itself

```
`ValidationError                           Traceback (most recent call last)
Cell In[39], line 6
      4 import torch
      5 from langchain.llms import HuggingFacePipeline
----> 6 from ragas.metrics import Faithfulness
      9 DATASET_PATH = "explodinggradients/ragas-wikiqa"
     10 MODEL_PATH = "llama-2-7b-chat-hf"

File ~/.local/lib/python3.8/site-packages/ragas/__init__.py:1
----> 1 from ragas.evaluation import evaluate
      3 try:
      4     from ._version import version as __version__

File ~/.local/lib/python3.8/site-packages/ragas/evaluation.py:9
      6 from datasets import Dataset, concatenate_datasets
      8 from ragas._analytics import EvaluationEvent, track
----> 9 from ragas.metrics.base import Metric
     10 from ragas.metrics.critique import AspectCritique
     11 from ragas.validation import validate_column_dtypes, validate_evaluation_modes

File ~/.local/lib/python3.8/site-packages/ragas/metrics/__init__.py:2
      1 from ragas.metrics.answer_relevance import AnswerRelevancy, answer_relevancy
----> 2 from ragas.metrics.context_relevance import ContextRelevancy, context_relevancy
      3 from ragas.metrics.critique import AspectCritique
      4 from ragas.metrics.faithfulnes import Faithfulness, faithfulness

File ~/.local/lib/python3.8/site-packages/ragas/metrics/context_relevance.py:173
    168             scores.append(agr_score * np.mean(overlap_scores))
    170         return dataset.add_column(f"{self.name}", scores)  # type: ignore
--> 173 context_relevancy = ContextRelevancy()

File <string>:4, in __init__(self, batch_size, llm, name, evaluation_mode, strictness, agreement_metric, model_name)

File ~/.local/lib/python3.8/site-packages/ragas/metrics/base.py:69, in _llm_factory()
     68 def _llm_factory():
---> 69     return ChatOpenAI(model_name="gpt-3.5-turbo-16k")

File ~/.local/lib/python3.8/site-packages/langchain/load/serializable.py:74, in Serializable.__init__(self, **kwargs)
     73 def __init__(self, **kwargs: Any) -> None:
---> 74     super().__init__(**kwargs)
     75     self._lc_kwargs = kwargs

File ~/.local/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)`
```

**Comment by jjmachan** [comment]
this is because the metrics are still using OAI endpoints. Can you refer [custom llm guide](https://github.com/explodinggradients/ragas/blob/main/docs/guides/llms.ipynb) already? it will show you how to change the LLM. In case it does not work can you share the code and ragas,python versions?

**Comment by seanbenhur** [comment]
Yes I referred the above nb, the issue is I get the error, when I import the metric

from ragas.metrics import Faithfulness

**Comment by jjmachan** [comment]
ohh my apologies. I'll fix that bug (thanks a lot for bringing it to our attention ❤️ ). In the meantime could you set the env-var with some random text as a workaround till we release the fix?

**Comment by arikupe** [comment]
Hello @jjmachan! Thanks for the great work :) 

I've run into another bug while trying to use a local LLM. I cannot compute either `ContextRelevancy` or `AnswerRelevancy` when using a langchain BaseLLM, due to this Exception in line 36 in `ragas.metrics.llms`:

```
20      def generate(
21          prompts: list[ChatPromptTemplate],
22          llm: BaseLLM | BaseChatModel,
23          n: t.Optional[int] = None,
24          temperature: float = 0,
25          callbacks: t.Optional[Callbacks] = None,
26      ) -> LLMResult:
27          old_n = None
28          n_swapped = False
29          llm.temperature = temperature
30          if n is not None:
31               if isinstance(llm, OpenAI) or isinstance(llm, ChatOpenAI):
32                    old_n = llm.n
33                    llm.n = n
34                    n_swapped = True
35               else:
36  --->           raise Exception(
37                     f"n={n} was passed to generate but the LLM {llm} does not support it."
38                     " Raise an issue if you want support for {llm}."
39                )
```

The issue arises because when `ContextRelevancy` and `AnswerRelevancy` call this function they pass in `n=self.strictness`, eg in `ragas.metrics.answer_relevance`:

```
75        results = generate(
76            prompts,
77            self.llm,
78            n=self.strictness,
79            temperature=self.temperature,
80            callbacks=batch_group,
81        )
```

However `strictness` must be an integer due to both class's post_init:
```
54    def __post_init__(self: t.Self):
55        self.temperature = 0.2 if self.strictness > 0 else 0
```

Passing `strictness=None` would resolve the Exception issue but yields another error due to the post_init integer comparison.

Is there any scope to change the Exception to allow for n=0 or similar (eg change line 30 in `ragas.metrics.llms` to `if n is not None and n>0`?

If not, we are currently unable to use these metrics with a non-OpenAI LLM

**Comment by ishaan-jaff** [comment]
@seanbenhur made a PR for this: https://github.com/explodinggradients/ragas/pull/118
