### ISSUE TITLE
Hard coded path when saving filters

### ISSUE THREAD

**Issue by jimgoo** [explodinggradients/ragas#742]
This hard coded path was breaking the demos for me since `/Users/shahules/Myprojects/ragas/experiments/{filename}.json` didn't exist on my machine. I just replaced it with `{filename}.json` and everything worked.

https://github.com/explodinggradients/ragas/blob/7ba0c28b07cd5742c7067697d898efd7a4638d49/src/ragas/testset/filters.py#L29

**Comment by shahules786** [comment]
Hey @jimgoo damn, that was very poor review from my side, it was an experimental branch that somehow got mixed up. Just fixing it now.
