### ISSUE TITLE
Inconsistency between documentation and column validation step

### ISSUE THREAD

**Issue by lsantosq** [explodinggradients/ragas#746]
Hi,

So based on the updated ragas documentation, it says that `ground_truth` is a `list[list]`. ([here](https://docs.ragas.io/en/stable/howtos/applications/data_preparation.html)). 

However, even if I converted the evaluation dataset to use such a key, I got the following error:

```
ValueError: Dataset feature "ground_truth" should be of type string
```

I did a bit of investigation, and it seems in the step to validate the types of the columns, `ground_truth` is added to the same check as `question` and `answer`, which are expected to be strings. See image and I also link the code line [here](https://github.com/explodinggradients/ragas/blob/746d723b4ca16faf697b048bba70b6fcad2f449a/src/ragas/validation.py#L43).

Therefore, I am a bit confused now. I open a similar issue (#655 ) previously, but I believe I was not clear there.

Am I missing something? 🤔 

![image](https://github.com/explodinggradients/ragas/assets/57979150/7c00cc53-b3c2-41a1-a9f9-a06c18ce5a0b)

I am using `ragas==0.1.3`.

Thanks!!

**Comment by shahules786** [comment]
Hey @lsantosq thanks for sharing this with us. Ground truth in an older version of ragas was list[str] but now we use str. The doc was out of date. Just raised a PR to fix this.

**Comment by shahules786** [comment]
If you think the PR resolves your confusion, feel free to close the issue @lsantosq
