### ISSUE TITLE
ImportError: cannot import name 'LangchainLLM' from 'ragas.llms'

### ISSUE THREAD

**Issue by HRUSHI1212** [explodinggradients/ragas#756]
I am using llama2 model for synthetic data generation and evaluation.

''' 
    
    def chat_factory() -> BaseChatModel:

    llm = HuggingFaceHub(
        repo_id="meta-llama/Llama-2-7b-chat-hf",
        task="text-generation",
        huggingfacehub_api_token='#################',
        model_kwargs={
            "max_new_tokens": 512,
            "top_k": 30,
            "temperature": 0.1,
            "repetition_penalty": 1.03,
        },
    )
    chat = ChatHuggingFace(llm=llm)
    return chat
'''

  '''
     from ragas.testset.generator import TestsetGenerator
     from ragas.llms import LangchainLLM
     from ragas.embeddings import embedding_factory
     from langchain_core.language_models import BaseLanguageModel
  
  
    generator_llm=LangchainLLM(llm= chat_factory())
    critic_llm = LangchainLLM(llm= chat_factory())
    embeddings_model = embedding_factory()
  
  
    testset_distribution = {
        "simple": 1.0,
        "reasoning": 0.0,
        "multi_context": 0.0,
        "conditional": 0.0,
    }
  
  
    chat_qa = 0.2
  
  
    test_generator = TestsetGenerator(
        generator_llm=generator_llm,
        critic_llm=critic_llm,
        embeddings_model=embeddings_model,
        testset_distribution=testset_distribution,
        chat_qa=chat_qa,
    )

'''

Ragas version:0.1.2
Python version:3.10.12

i am getting error while running this above snippet

**Comment by cloudyuyuyu** [comment]
try 

from ragas.llms import LangchainLLMWrapper

**Comment by salvatoresaporito** [comment]
I get the same error 
`ImportError: cannot import name 'LangchainLLM' from 'ragas.llms' `

Using `LangchainLLMWrapper` as dropin replacement.
`TypeError: LangchainLLMWrapper.__init__() got an unexpected keyword argument 'llm'`

ragas.version: '0.1.8.dev13+gc5eac53'
langchain '0.1.17'
```
inference_server_url = "http://localhost:8080/v1"
# create vLLM Langchain instance
chat = ChatOpenAI(
    model="meta-llama/Meta-Llama-3-8B",
    openai_api_key="no-key",
    openai_api_base=inference_server_url,
    max_tokens=5,
    temperature=0,
)

# use the Ragas LangchainLLM wrapper to create a RagasLLM instance
vllm = LangchainLLMWrapper(llm=chat)
```

**Comment by Manel-Hik** [comment]
Hi,
I'm facing the same error
Did you find a solution please?

**Comment by mridulBanik112** [comment]
vllm = LangchainLLMWrapper(langchain_llm=chat)

**Comment by jjmachan** [comment]
closing this since @mridulBanik112 suggested the right solution. 

you can also just use it as
```py
vllm = LangchainLLMWrapper(chat)
```

to simplify it.
