### ISSUE TITLE
Are the Context Precision Examples and Calculation Correct?

### ISSUE THREAD

**Issue by pmbaumgartner** [explodinggradients/ragas#757]
[x] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
When calculating context precision, don't you need to provide each sentence/statement in the context individually in the prompt rather than all joined together? Right now all of the examples in the prompt for context precision concatenate the context strings into a single string. This means when calculating the context, the denominator is always going to be 1 because there's only 1 document in the context, which is the entire context.

**Code Examples**
https://github.com/explodinggradients/ragas/blob/c7302724a6203966c7d0c16db8f09ed5ce2a1a75/src/ragas/metrics/_context_precision.py#L19-L54

**Additional context**
Anything else you want to share with us?

**Comment by shahules786** [comment]
Hey @pmbaumgartner context precision is computed over multiple chunks. So denominator here is the number of retrieved contexts which can be one or more as you set in your RAG.

**Comment by pmbaumgartner** [comment]
That makes sense for the calculation, but I'm still a bit lost. I think I'm confused because that data structure is _different_ than what's provided in the few-shot examples. If it were the same as the calculation, I would expect to see one "example" per document/sentence in the context, not the entire context concatenated together. Does that make sense? 

I'm not sure it actually matters for the performance of the LLM on this task, but the mismatch here is a bit confusing.

**Comment by shahules786** [comment]
Can you check the calculation example of [context_precision](https://docs.ragas.io/en/stable/concepts/metrics/context_precision.html) and see if the code makes sense to you then?
