### ISSUE TITLE
What are the specific inputs and corresponding outputs used in the evaluation?

### ISSUE THREAD

**Issue by hanlv15** [explodinggradients/ragas#760]
How should I obtain specific inputs and outputs? Because I encountered strange results, I wanted to find the reason from specific user inputs and LLM outputs. The model I am using is GPT-3.5 packaged in Langchain.

**Comment by shahules786** [comment]
Hey @hanlv15 this is totally possible if you're using any tracing tools. for example https://docs.ragas.io/en/stable/howtos/integrations/index.html and https://docs.ragas.io/en/stable/howtos/applications/tracing.html
