### ISSUE TITLE
Evaluation of RAG pipeline using RAGAS

### ISSUE THREAD

**Issue by shasy4911** [explodinggradients/ragas#763]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
I want to evaluate the RAG pipeline using RAGAS. Using below code as reference to implement the metrics, but I don't understand that without passing explicit OpenAI key, contexts how are the metrics getting calculated?

**Code Examples**
from langchain.document_loaders import WebBaseLoader
from langchain.indexes import VectorstoreIndexCreator
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI

# load the Wikipedia page and create index
loader = WebBaseLoader("https://en.wikipedia.org/wiki/New_York_City")
index = VectorstoreIndexCreator().from_loaders([loader])

# create the QA chain
llm = ChatOpenAI()
qa_chain = RetrievalQA.from_chain_type(
    llm, retriever=index.vectorstore.as_retriever(), return_source_documents=True
)

# testing it out
question = "How did New York City get its name?"
result = qa_chain({"query": question})
result["result"]

# output
# 'New York City got its name in 1664 when it was renamed after the Duke of York, who later became King James II of England. The city was originally called New Amsterdam by Dutch colonists and was renamed New York when it came under British control.'

from ragas.metrics import faithfulness, answer_relevancy, context_relevancy, context_recall
from ragas.langchain import RagasEvaluatorChain

# make eval chains
eval_chains = {
    m.name: RagasEvaluatorChain(metric=m)
    for m in [faithfulness, answer_relevancy, context_relevancy]
}

# evaluate
for name, eval_chain in eval_chains.items():
    print('name:',name)
    print('eval_chain:',eval_chain)
    score_name = f"{name}_score"
    print(f"{score_name}: {eval_chain(result)[score_name]}")

**Additional context**
Anything else you want to share with us?

**Comment by prnvsharma4** [comment]
@dosu-bot can you help here?
