### ISSUE TITLE
Mistral-8x7b answer_correctness metric prompt fix

### ISSUE THREAD

**Issue by AlexisGitHu** [explodinggradients/ragas#770]
[X ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
Is there any prompt modification such that Mistral-8x7b does not give nan when evaluating answer_correctness metric?

**Code Examples**
I do not have any code snippets as answer_correctness does not prompt any warning or message, it just outputs None.

**Additional context**
The exact model I'm using is: mistralai/Mixtral-8x7B-Instruct-v0.1

**Comment by kanzyai-emirarditi** [comment]
Have you tried setting the raise_exceptions parameter to True?
