### ISSUE TITLE
ModuleNotFoundError: No module named 'ragas.testset'; 'ragas' is not a package

### ISSUE THREAD

**Issue by WoutDeRijck** [explodinggradients/ragas#779]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
Just trying to import the package while pip show ragas correctly shows the package

Ragas version: 0.1.4
Python version: 3.10.11

**Code to Reproduce**
from ragas.testset.generator import TestsetGenerator
from ragas.testset.evolutions import simple, reasoning, multi_context

**Error trace**
Traceback (most recent call last):
  File "/Users/x/Documents/x/test/ragas.py", line 7, in <module>
    import ragas
  File "/Users/x/Documents/x/test/ragas.py", line 11, in <module>
    from ragas.testset.generator import TestsetGenerator
ModuleNotFoundError: No module named 'ragas.testset'; 'ragas' is not a package

**Additional context**
I just installed the package (working in VSCode)

**Comment by jeremyadamsfisher** [comment]
I get this error with a fresh install of Python 3.11. How did you resolve this?

```

**Comment by Rugved2204** [comment]
Hi I am facing the same issue. 
Python 3.10.12 and Ragas 0.1.10
Traceback (most recent call last):
  File "/home/ubuntu/scp-analyzer/rag-old/ragas.py", line 2, in <module>
    from ragas.testset.generator import TestsetGenerator
  File "/home/ubuntu/scp-analyzer/rag-old/ragas.py", line 2, in <module>
    from ragas.testset.generator import TestsetGenerator
ModuleNotFoundError: No module named 'ragas.testset'; 'ragas' is not a package

**Comment by llvll0hsen** [comment]
same issue on python 3.11
