### ISSUE TITLE
QA Chains and Bring Your Own LLMs and Embeddings

### ISSUE THREAD

**Issue by 1234AP1234** [explodinggradients/ragas#780]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
How can I evaluate my RAG (Retrieval-Augmented Generation) built with Transformers and using embeddings from Hugging Face? In the documentation, I see how to evaluate with your own LLM and your embeddings, as well as how to integrate RAGs with Chain, but not how to do both at the same time. I don't want to use the OpenAI API.

**Code Examples**
qa = RetrievalQA.from_chain_type(
    llm=llm,chain_type='stuff',
    retriever=vectorstore.as_retriever(search_kwargs={"k":2})
)

embed_model_id = "distiluse-base-multilingual-cased-v1"

device = f"cuda:{cuda.current_device()}" if cuda.is_available() else "cpu"

embed_model = HuggingFaceEmbeddings(
    model_name=embed_model_id,
    model_kwargs={"device": device},
    encode_kwargs={"device": device, "batch_size": 32}
)

**Comment by shahules786** [comment]
Yes, ofc.
please checkout https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html

Feel free to open the issue if it's not working for you.

**Comment by 1234AP1234** [comment]
I continue without knowing how to do it

**Comment by 1234AP1234** [comment]
@dosu-bot can you help me?
