### ISSUE TITLE
Politely ask about the roadmap

### ISSUE THREAD

**Issue by muruan01** [explodinggradients/ragas#783]
**Your Question**
Hi, team. I learned about the other evaluation projects and I'm curious about your roadmap: do you have any plan about the tracking, for example, the RAG methods contain retrival, rank and generation, if ragas can track these(including all the retrival context) and display to the users, that will be very helpful.

**Additional context**
https://github.com/Arize-ai/phoenix, other project to refer to.

Thanks very much

**Comment by shahules786** [comment]
Hey bro @muruan01 thanks for the FR, I am marking it to consider for future releases. We have a discord community in which we will plan monthly office hours to plan roadmaps.
