### ISSUE TITLE
Context_relevancy metric returns 1 unexpectedly

### ISSUE THREAD

**Issue by lalehsg** [explodinggradients/ragas#791]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
I noticed that when my RAG system can not retrieve a relevant context for a question from my evaluation set, ie the returned context is empty or just ['N'], the computed context_relevancy by the library is 1.

Ragas version:
ragas==0.1.5

Python version:

**Code to Reproduce**
```
dct = {'question': 'What is the role of WWSE Finance?',
 'answer': '1. Based on the context provided, there is no information given about a company or entity named "WWSE Finance." Therefore, I cannot provide a detailed step-by-step answer about its role.\n2. Without further context or information, it is impossible to determine what WWSE Finance does, what industry it operates in, or what responsibilities and functions it has.\n3. In order to provide an accurate answer, I would need more context or information about WWSE Finance, such as its mission statement, services offered, or relevant news articles.\n\nIn summary, I don\'t know the role of WWSE Finance because there is not enough information provided in the context.',
 'contexts': ['N'],
 'ground_truth': "WWSE Finance supports internal studios in their creation of great games and improving the company's bottom line by analyzing and predicting future scenarios or by recording and reporting past financial transactions. Its aim is to play an integral part in the internal studio business, whether through scenario planning with a studio team or managing month's bills or expenses."}

ds = Dataset.from_dict(dct)

fiqa_eval = DatasetDict({"baseline": ds})

chat_model = ChatDatabricks(endpoint=...)

from ragas import evaluate
result = evaluate(fiqa_eval["baseline"], metrics=metrics, embeddings=fast_embeddings, llm = chat_model)
result

```

**Error trace**

**Expected behavior**
I expect that in these cases the context_relevancy returns as 0 because technically there's no retrieved context. 

**Additional context**

**Comment by shahules786** [comment]
Hey @lalehsg Context_relevancy metric is deprecated and we don't maintain it anymore. As you must have seen the warning.

**Comment by lalehsg** [comment]
got it! thanks!

**Comment by Syed-Mujeeb** [comment]
@shahules786 I still see, context relevancy in [documentation](https://docs.ragas.io/en/latest/concepts/metrics/context_relevancy.html) may I know in which version we are going to deprecate context relevancy metric
