### ISSUE TITLE
Faithfulness return NaN when it should be zero

### ISSUE THREAD

**Issue by lalehsg** [explodinggradients/ragas#794]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
when no context is retrieved and the llm answer starts with "i'm sorry..." or "i'm unable...", the metric score become NaN
 

**Expected behavior**
I believe in these cases we the score should be zero.

**Comment by shahules786** [comment]
Hey @lalehsg This is intentional. Since the system refuses to answer it does not make sense to score it. We can't say it's less faithful or fully faithful in this situation therefore it's NaN

**Comment by lalehsg** [comment]
ok so I see inconsistent results for the same samples with GPT4 and GPT3.5 turbo for faithfulness. GPT3.5 is returning 0 and 0.33 in 2 such samples. GPT4 is returning NaN for both cases. curious!
