### ISSUE TITLE
Generating Synthetic data from existing document Index (ChromaDB, Qdrant, etc)

### ISSUE THREAD

**Issue by satadda** [explodinggradients/ragas#823]
**Describe the Feature**
A class to generate synthetic questions or dataset from existing document store or Index.

**Why is the feature important for you?**
This will reduce LLM calls and re-processing of the data/documents which are already embedded

**Comment by shahules786** [comment]
Hey @satadda thanks for raising this. This is a feature we are actively considering - will roll out in next stable release :)
