### ISSUE TITLE
Why did the Kernal crashing issue get removed?

### ISSUE THREAD

**Issue by davidzimmerman19** [explodinggradients/ragas#824]
Why did the Kernal crashing issue get removed? Was this fixed? The issue wasn't changed to close but just disappeared.

**Comment by shahules786** [comment]
Hey @davidzimmerman19 which issue is this? We don't delete any issues. The user might have deleted it.

**Comment by davidzimmerman19** [comment]
It was regarding a kernal crash in jupyter notebooks when attempting to generate test data with local LLMs. There were comments saying there were other related issues and that it was being worked on. The original poster must have deleted it for some reason.
