### ISSUE TITLE
Testset generation example from documentation does not generate 'answer' column

### ISSUE THREAD

**Issue by xdurfina** [explodinggradients/ragas#846]
**Question:**
1. The code example does not generate answers in testset generation example. Am I understanding something wrong?
2. Which prompt is used for answer generation? 

**Code example:**
https://docs.ragas.io/en/stable/getstarted/testset_generation.html#data-generation

**Comment by crystlbat** [comment]
I too am facing the same issue; I have tried out initiating the critic and generator with gpt4 and gpt3.5 instances with temperatures 0.7 and 0.2 respectively. Followed the exact example from the above documentation..

**Comment by raffy4284** [comment]
Facing the same issue as well...

**Comment by dianavintila** [comment]
+ 1

**Comment by chong-w** [comment]
Me too, only below column generated :
question | contexts | ground_truth | evolution_type | metadata | episode_done

**Comment by lukschack** [comment]
Same here. Followed documentation closely, but using Claude 3 Haiku via Bedrock. The question generation works as expected but not the 'answer' creation.

**Comment by sdiazben** [comment]
+1

**Comment by manojpraba** [comment]
I too facing the same issue, using Azure open AI api to create test data, answer column is missing.
![image](https://github.com/explodinggradients/ragas/assets/37367345/8972ed5f-89a9-447c-b197-ed76d2dc457f)

**Comment by ayoubazaouyat** [comment]
+1

**Comment by jjmachan** [comment]
@xdurfina @crystlbat @raffy4284 @dianavintila @chong-w @lukschack @sdiazben @manojpraba @ayoubazaouyat were you folks able to figure this out?

it is an error in the documentation from our end. I will fix this shortly

really sorry about the delay and thanks for pointing it out!

**Comment by jjmachan** [comment]
also fix docs for [Compare Embeddings for retriever | Ragas](https://docs.ragas.io/en/stable/howtos/applications/compare_embeddings.html)
