### ISSUE TITLE
[R-241] docs on how to custumize LLMs in test set generation

### ISSUE THREAD

**Issue by projects-g** [explodinggradients/ragas#856]
[x] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
Was anyone able to generate synthetic dataset using a custom LLM ? The documentation completely skips over the specifics here. It just asks us to either create a langchain instance (supported models are only few) and wrap it around new wrappers OR base them out of BaseRagasLLM 
https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html#llms

But when you do that, you also have to define agenerate_prompt, agenerate_text, generate_prompt and generate_text. We dont know when these functions are called by the test set generation and what to return at each function, etc. Its all a black box with no examples. My experiments tend to repeat multiple times with no output and just fails after a while.

**Code Examples**
This community speaks code. Share your code snippets to help us understand your question better.

**Additional context**
Anything else you want to share with us? 

<sub>[R-241](https://linear.app/exploding-gradients/issue/R-241/docs-on-how-to-custumize-llms-in-test-set-generation)</sub>

**Comment by WGS-note** [comment]
hi，have you solved it?

**Comment by Zzrjin** [comment]
Any news about the solutions now? Facing the same problem.

**Comment by jjmachan** [comment]
@projects-g @WGS-note @Zzrjin extremely sorry about the delay but we had improved the docs for this

take a look at https://docs.ragas.io/en/stable/howtos/customisations/bring-your-own-llm-or-embs.html#test-set-generation

and it should help

closing this for now but feel free to comment below if you have any issues and I'll reopen
