### ISSUE TITLE
openai.UnprocessableEntityError: Error code: 422

### ISSUE THREAD

**Issue by marion2016** [explodinggradients/ragas#861]
[ ] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**

Ragas version:
Python version:

**Code to Reproduce**
Share code to reproduce the issue

**Error trace**
openai.UnprocessableEntityError: Error code: 422 - {'detail': [{'type': 'string_type', 'loc': ['body', 'input', 'list[str]', 0], 'msg': 'Input should be a valid string', 'input': [791, 1561, 9635, 33617, 617, 2834, 279, 7445, 20904, 264, 3335, 4848, 3115], 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}, {'type': 'string_type', 'loc': ['body', 'input', 'str'], 'msg': 'Input should be a valid string', 'input': [[791, 1561, 9635, 33617, 617, 2834, 279, 7445, 20904, 264, 3335, 4848, 3115]], 'url': 'https://errors.pydantic.dev/2.6/v/string_type'}]}

**Expected behavior**

**Additional context**

**Comment by tuncK** [comment]
Same here.
