### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by itech001** [explodinggradients/ragas#862]
how to call torch.cuda.empty_cache() to free gpu cache?

**Comment by itech001** [comment]
Is it possible to free gpu cache after every metics or every llm query?

**Comment by jjmachan** [comment]
could you please provide a bit more context to tackle this
- which ragas version
- what you're trying to accomplish, code snippet

it would help us answer and solve your question better :)
