### ISSUE TITLE
[R-238] Answer relevance metrics does not require embedding match if answer is non-commital

### ISSUE THREAD

**Issue by rajib76** [explodinggradients/ragas#864]
**Describe the Feature**
The answer relevance metrics multiplies the cosine similarity with noncommittal. So, if we check the answer is noncommittal, we do not need to call the embedding model

**Why is the feature important for you?**
It will improve the performance of the metrics

**Additional context**
None

<sub>[R-238](https://linear.app/exploding-gradients/issue/R-238/answer-relevance-metrics-does-not-require-embedding-match-if-answer-is)</sub>

**Comment by jjmachan** [comment]
that is a smart point - thanks @rajib76 for suggesting that 🙂 

we will be working on this but let me know if you want to take a stab at it - we can work on this together too

**Comment by rajib76** [comment]
I can take a stab at it Jithin. Let me check the code. I am ok to work with you on this.

**Comment by rajib76** [comment]
I am thinking to make the change as below. But I am not able to find the documentation on how I can build the code and test it.

    def _calculate_score(
        self, answers: t.Sequence[AnswerRelevanceClassification], row: t.Dict
    ) -> float:
        question = row["question"]
        gen_questions = [answer.question for answer in answers]
        committal = np.any([answer.noncommittal for answer in answers])
        if all(q == "" for q in gen_questions):
            logger.warning(
                "Invalid JSON response. Expected dictionary with key 'question'"
            )
            score = np.nan
        else:
            # Changes by Rajib #
            if not committal:
                score = 0
            else:
                cosine_sim = self.calculate_similarity(question, gen_questions)
                score = cosine_sim.mean()
            # Changes by Rajib #
            # 
            # cosine_sim = self.calculate_similarity(question, gen_questions)
            # score = cosine_sim.mean() * int(not committal)

**Comment by jjmachan** [comment]
shahul would be the best person to take this forward
