### ISSUE TITLE
[R-236] testset hard negatives

### ISSUE THREAD

**Issue by PrathamSoni** [explodinggradients/ragas#868]
**Describe the Feature**
Use similarity to also give similar nodes for a given node so each question has a set of hard negatives against it

**Why is the feature important for you?**
Improve dataset.

**Additional context**
N/A

<sub>[R-236](https://linear.app/exploding-gradients/issue/R-236/testset-hard-negatives)</sub>

**Comment by jjmachan** [comment]
this is something we have been thinking for a while too - very important feature too

Thanks for proposing this @PrathamSoni 🙂 
btw while we are developing would love to get some early feedback from you if possible - would you be able to help us with that Pratham?

**Comment by PrathamSoni** [comment]
Yes of course!

**Comment by PrathamSoni** [comment]
any updates on this
