### ISSUE TITLE
[R-234] docs: update and fix documentation

### ISSUE THREAD

**Issue by mancaldel** [explodinggradients/ragas#870]
Some of the pages in the documentation are out of date or incorrect and it make it difficult to have a general idea about the capabilities of the library. Here are a few examples:
- [References/Metrics](https://docs.ragas.io/en/stable/references/metrics.html): the summary at the beginning does not include all implemented metrics, missing 4/10 (AspectCritique, ContextRelevancy, ContextUtilization, Faithfulness). Also, there is no info about the definition of the last metrics in the list.
- [Concepts/metrics](https://docs.ragas.io/en/stable/concepts/metrics/index.html#ragas-metrics): also missing some metrics, 2/10 in the page (AspectCritique, ContextUtilization), and 1/10 in the side bar (ContextUtilization)
- [Integrations](https://docs.ragas.io/en/stable/references/integrations/index.html): friendly reminder that the page is empty.

Thanks!

<sub>[R-234](https://linear.app/exploding-gradients/issue/R-234/docs-update-and-fix-documentation)</sub>

**Comment by jjmachan** [comment]
Hey @mancaldel 

thank you for keeping us honest - will be updating these shortly Manuel 🙂
