### ISSUE TITLE
Difference between context_utilization metric and context_relevancy metrics?

### ISSUE THREAD

**Issue by hteeyeoh** [explodinggradients/ragas#872]
Initially context_precision work without ground truth. This have been updated where now context_precision required ground truth. Below log observed when we try to use context_utilization metrics:
Using 'context_precision' without ground truth will be soon depreciated. Use 'context_utilization' instead

Just curious what the difference between context_utilization as compared to context_relevancy as not much documentation info found for context_utilization metrics.

And also now using "context_utilization" will show the above "warning" logs, is it expected?

**Comment by jjmachan** [comment]
`context_precision` helps you answer the question "what is the signal to noise ratio of the contexts my retriever retrieved". the key is how signal is calculated
1. for `context_precision` signal is from ground_truth
2. for `context_utilisation` the signal is from the answer generated. Basically it shows how much information was actually used by the llm to generate the given answer from all the context that was provided.

I hope it answer the questions 🙂

**Comment by hteeyeoh** [comment]
Ok Thanks for the information. So now i will use context_utilization metric to calculate the score between context and the answer generated by llm.
