### ISSUE TITLE
[R-258] Question about official docs of Context Precision.

### ISSUE THREAD

**Issue by AxelJongoPark** [explodinggradients/ragas#895]
What I understood is that Following case is calculation of Context Precision at K=2.

For that case, Last part's denominator must be 2 not 1.

Is this right?

If i didn't understand well, could you explain more about this?? 
Following is what i'm thinking.

1. precision at 1
FP at 1 =1, TP at 1 =0 -> precision at 1 = 0
2. precision at 2
FP at 2 =1 , TP at 1 =1 -> precision at 2 = 1/2 =0.5 (since we consider top 2 resulte in context chunk items)
3 finally, we have
Context Precision at K=2 is
(1/2)x(preicision at 1 x indicator at 1 + preicision at 2x indicator at 2) = (1/2)x(0x1+0.5x1)=0.25

thanks.  

![ragas_docs](https://github.com/explodinggradients/ragas/assets/131431642/8d2dcfaf-a8de-4b63-a252-ca4cdb3f3a8e)

<sub>[R-258](https://linear.app/exploding-gradients/issue/R-258/question-about-official-docs-of-context-precision)</sub>

**Comment by AxelJongoPark** [comment]
> Hi, do you understand? I have this confusion too.

No.. I'm stuck in same situation.

**Comment by jjmachan** [comment]
hey @WGS-note and @AxelJongoPark, thank you for bringing this up 🙌🏽 

@shahules786 could you help them out?

**Comment by shahules786** [comment]
Metrics were updated as part of v0.2. Please check it out https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/context_precision/
