### ISSUE TITLE
Prevent hallucination in candidate sentence extraction

### ISSUE THREAD

**Issue by shahules786** [explodinggradients/ragas#90]
For measuring context_relevancy, the LLM tries to extract sentences from a given context that is actually useful to answer the question. But in this process, there is a slight chance that the LLM might hallucinate and give out a sentence that is not exactly present in the given context.

- It would be good to have some kind of [check](https://github.com/explodinggradients/ragas/blob/1cda1c7dea115fad524fa90a3273070169dd6868/src/ragas/metrics/context_relevance.py#L185) to ensure that only sentences present in the given context are selected by the LLM. 

- Another way to look at it is to change the [prompt](https://github.com/explodinggradients/ragas/blob/1cda1c7dea115fad524fa90a3273070169dd6868/src/ragas/metrics/context_relevance.py#L18) so that the LLM outputs the indices of candidate sentences from a given context. This could bypass the need for an extra check.

**Comment by SangeethaVenkatesan** [comment]
Would like to work on this issue!
