### ISSUE TITLE
Duplicate reference

### ISSUE THREAD

**Issue by CvH2020** [explodinggradients/ragas#903]
https://github.com/explodinggradients/ragas/blame/65b77f5d8a300107ab964de6af060a8207dff260/src/ragas/validation.py#L31

Shouldn't it be referenced like this: 
ds.features[column_names].dtype
not with two times feature(s) ?

Eg. this for me works:
ds.features["contexts"].dtype == "string"

while as it is implemented atm throws an undesired error:
ds.features["contexts"].feature.dtype == "string"

**Comment by jjmachan** [comment]
hey @CvH2020 - welcome to the community 🙂 

could you give me some more information about this though 
1. ragas, dataset version
2. trace of the error message
3. anything else you feel will help us 

I ran the code you suggested which throws list not string for contexts
