### ISSUE TITLE
Faithfulness vs. context recall

### ISSUE THREAD

**Issue by ishaan-mehta** [explodinggradients/ragas#913]
[x] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
What is the difference, conceptually, between faithfulness and context recall? Not sure I understand the semantic difference between (1) claims in answer derived from context / total claims in context, and (2) number of statments in answer attributable to context / total statements in answer.

Is one preferred over the other? Is one more stable?

**Code Examples**
N/A

**Additional context**
N/A

**Comment by Red-Caesar** [comment]
I'm not an expert, but the picture from this [video](https://www.youtube.com/live/dt1Iobn_Hw0?si=KGiFvaNvN7qcpsFg&t=3137) helped me to understand the difference between rag metrics. So, I hope this will bring some clarity to you as well.
![image](https://github.com/explodinggradients/ragas/assets/80523757/c450e61b-2c84-4758-90b9-cd430334c7b5)

**Comment by ishaan-mehta** [comment]
Ah whoops, I see context recall is based on ground truth rather than the generated answer. Thanks!
