### ISSUE TITLE
LLM generates trimmed JSON for context recall and faithfulness metrics

### ISSUE THREAD

**Issue by franchukpetro** [explodinggradients/ragas#914]
Hey,

First of all, thanks for a great tool, it's really helpful!

I was evaluating my RAG pipeline using own test set and Palm (bison@002) model from VertexAI. I noticed that for context recall and faithfulness metrics resulted in a lots of NaNs in the results, so I dive deeper to define what is wrong with those records. It turned out that LLM under the hood was generating invalid, trimmed jsons (a few statements were included, but third-forth statement was just cut in the middle), which furtherly weren't parsed sucessfully.

It seems like for some reason LLM stops generating the output JSON needed for metrics computation. I checked the output seqlen of Palm - it's at least 1024, while those JSONs were around 100 tokens, so I don't think that it is the reason.

Is that some other constraint on output seqlen, or just that is the nature of LLM-based evaluation, and I need to expect that sometimes results will be NaNs because of inconsistent output format in generated text?

ragas version: 0.1.7
Python version: 3.11.9

**Comment by Red-Caesar** [comment]
Like a user, I have two suggestions regarding the issue: 
1. The max_tokens provided is not sufficient to complete the response. 
3. This is an real issue with LLMs that sometimes occurs. In such cases, you can contact the developer and provide them with the prompt that caused the truncated output. This will be helpful for them as they will have more information and may be able to fix the issue. Additionally, you can also try modifying the prompt slightly. Sometimes, even small changes can help (e.g., writing some words in uppercase or removing a word or sentence).

**Comment by franchukpetro** [comment]
Hi @Red-Caesar,

Thanks for the response!

You are right, I had an opportunity to play with it a bit more, and tried explicilty setting bigger `max_output_tokens` parameter for my LLM (specifically, 2048 for `text-bison` model), and that resolved almost all NaNs for context recall and faithfulness metrics.

I just checked that default `max_output_tokens` for `ChatVertexAI` model is 128 tokens, so I guess that was the main source of issue.

Thanks for the help, closing the issue.
