### ISSUE TITLE
[BUG] running ragas evaluate tries to post results to local langsmith

### ISSUE THREAD

**Issue by mikeldking** [explodinggradients/ragas#92]
I don't have any langchain env vars set but I am getting a network error as seen below.

<img width="1873" alt="Screenshot 2023-08-11 at 6 04 23 PM" src="https://github.com/explodinggradients/ragas/assets/5640648/6a9265fd-54f9-4f19-b8d7-c2c40ce17be5">

**Comment by jjmachan** [comment]
hmm this is interesting, most likely due to something with langchain's end but to confirm could you give me your langchain version, python version and ragas version

let me see if I can reproduce this 

Thanks a ton for raising the issue @mikeldking :)

**Comment by mikeldking** [comment]
> langchain==0.0.265
> ragas==0.0.10
> langsmith==0.0.22

**Comment by jjmachan** [comment]
are you still facing these issue consistently ?

**Comment by mikeldking** [comment]
> are you still facing these issue consistently ?

It's not blocking, it just shows up next to the progress bars

**Comment by sam-h-bean** [comment]
@jjmachan this is pretty annoying and pervasive for us. Are we planning on fixing?
