### ISSUE TITLE
Ragas llama_index integration as shown doesn't work for custom LLMs

### ISSUE THREAD

**Issue by pliablepixels** [explodinggradients/ragas#954]
[X] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
[This document](https://docs.ragas.io/en/latest/howtos/integrations/llamaindex.html) describes how to use Llama index w/OpenAI and Ragas. And [this] shows how we can use a custom LLM but via langchain.

Can you please provide an example of how one can use llama_index without needing LangChain and using a [custom LLM ](https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom/)?

**Code Examples**
I made _some_ progress using"

```
evaluate (data, metrics, llm=LangchainLLMWrapper(mycustomLLM), embeddings=LangchainEmbeddingsWrapper(my_embedding))
```

But halfway through eval it compains of unimplemented methods like  `ragas has no attribute generate_prompt`. I'm not sure what needs to be done, and what unimplemented methods may show up in the future.

**Comment by jjmachan** [comment]
this should fix this https://docs.ragas.io/en/stable/howtos/integrations/llamaindex.html

extremely sorry about the late response
