### ISSUE TITLE
Grammar and punctuation improvements in critique prompts

### ISSUE THREAD

**Issue by ruankie** [explodinggradients/ragas#971]
[x] I have checked the [documentation](https://docs.ragas.io/) and related resources and couldn't resolve my bug.

**Describe the bug**
I've noticed a few grammar and punctuation issues in the [critique prompts](https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/critique.py). The verbs need to be in their base form to match the auxiliary verbs "does" and "is," and one sentence is missing a question mark. Fixing these will make the questions clearer and more consistent.

Ragas version: Latest (on `main` branch)
Python version: N/A

**Comment by ruankie** [comment]
Please assign me. I'll make a PR soon for this.

**Comment by jjmachan** [comment]
thanks @ruankie for taking this up and fixing it 🙂 

btw are you on our discord channel, would love to add you to our contributors group if you want (just as a thank you for the PR)

closing this for now!

**Comment by ruankie** [comment]
Hey @jjmachan, glad this PR helped.
That would be great, thanks!
I am not on your Discord server at the moment. Can you please send a link?
