### ISSUE TITLE
[R-262] ImportError: llama_index must be installed to use this function. Please, install it with `pip install llama_index`.

### ISSUE THREAD

**Issue by Prabhjot410** [explodinggradients/ragas#991]
[ ] I checked the [documentation](https://docs.ragas.io/) and related resources and couldn't find an answer to my question.

**Your Question**
I am following ragas official document for testset generation. I am using custom llm (huggingfacepipeline) and huggingface embedding model, but whenever I am running this code, I am getting this error : ImportError: llama_index must be installed to use this function. Please, install it with `pip install llama_index`.

**Code Examples**
generator = TestsetGenerator.from_langchain(
    generator_llm,
    critic_llm,
    embeddings
)

# generate testset
testset = generator.generate_with_langchain_docs(overall, test_size=10, distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25})

**Additional context**
I have already install llama_index and ragas version 0.0.22. 

How can I solve this problem ?

<sub>[R-262](https://linear.app/exploding-gradients/issue/R-262/importerror-llama-index-must-be-installed-to-use-this-function-please)</sub>

**Comment by jjmachan** [comment]
that is a bug and we will fix that for you 🙂 

thanks for reporting this ❤️
