### ISSUE TITLE
[R-282] use callbacks to trace reasoning of `Prompt`

### ISSUE THREAD

**Issue by JinSeoung-Oh** [explodinggradients/ragas#992]
Hi, at first, I want to say thanks this wonderful work.

Actually, I want save the reason of evaluation.
I mean, line 69 to line 106 at https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/_answer_correctness.py
Actually, it already has save function and it seems save line 69~106.
Ah, of course it is example, but I think this module generate something like this line.
I just want to save it

But I tried use this save function, it returned 'None'

So, how can I save this?
I have to build new module for this?

Thanks!

<sub>[R-282](https://linear.app/exploding-gradients/issue/R-282/use-callbacks-to-trace-reasoning-of-prompt)</sub>

**Comment by jjmachan** [comment]
hey @JinSeoung-Oh thank you for raising this issue - that is indeed a good suggestion!

can I ask you a couple of questions to better understand this?
1. where and how would you like to save this? Would just text be enough? are you expecting it to be part of the `Result` object?
2. are you using any Tracing tools? If you are, the reasoning is actually saved for you automatically today
3. how will you visualize the saved data, there will be a lot of data points to go through.

**Comment by kengelbrecht** [comment]
@jjmachan I have been looking for such a feature as well (for faithfulness metric, though). I would like to see the statements and respective verdict for two reasons: 

1. I would like to roughly evaluate if the numbers returned by the evaluate function are based on reasonable extracted statements and verdicts. 
2. I am considering to add those details to a labeling task such that annotators get hints as to possible errors. 

I reckoned the information would be available if I use fallbacks, but this is a fairly complex setup especially given the early stage of my investigations. Referring to the [getting started example](https://docs.ragas.io/en/stable/getstarted/evaluation.html#get-started-evaluation), if the information could be returned as part of the result of the `evaluate` function, so `result.to_pandas()` then would add it to the dataframe, that would be a handy solution for me.

**Comment by jjmachan** [comment]
@kengelbrecht got it! will use this issue to track this

**Comment by vitika1** [comment]
Hi @jjmachan any update on this? The issue is resolved but I can't see the reasoning returned by `evaluate` function. Please let me know if I am missing anything.

**Comment by vitika1** [comment]
Also, if that has not be been implemented yet, is the solution is to modify the prompts to include reasoning?

**Comment by vitika1** [comment]
@jjmachan thanks for the response.

We don't want to rely on tracing as we have to store+send the data somewhere.

I can't find any `trace` property inside the `EvaluationResult` object, is that what you meant?

**Comment by JinSeoung-Oh** [comment]
Ah, I totally forgot it. 
I solved this problem built custom evaluate function.
I cannot share my code, because my company used it.

Have to check Result class in eval.
Thanks!
